// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: xponder/common.proto

package sctexponder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bit field enumeration for reset types.
type ScteResetTypeE int32

const (
	ScteResetTypeE_SCTE_SOFT_RESET    ScteResetTypeE = 1 // b0
	ScteResetTypeE_SCTE_HARD_RESET    ScteResetTypeE = 2 // b1
	ScteResetTypeE_SCTE_NV_RESET      ScteResetTypeE = 4 // b2
	ScteResetTypeE_SCTE_FACTORY_RESET ScteResetTypeE = 8 // b3
)

// Enum value maps for ScteResetTypeE.
var (
	ScteResetTypeE_name = map[int32]string{
		1: "SCTE_SOFT_RESET",
		2: "SCTE_HARD_RESET",
		4: "SCTE_NV_RESET",
		8: "SCTE_FACTORY_RESET",
	}
	ScteResetTypeE_value = map[string]int32{
		"SCTE_SOFT_RESET":    1,
		"SCTE_HARD_RESET":    2,
		"SCTE_NV_RESET":      4,
		"SCTE_FACTORY_RESET": 8,
	}
)

func (x ScteResetTypeE) Enum() *ScteResetTypeE {
	p := new(ScteResetTypeE)
	*p = x
	return p
}

func (x ScteResetTypeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScteResetTypeE) Descriptor() protoreflect.EnumDescriptor {
	return file_xponder_common_proto_enumTypes[0].Descriptor()
}

func (ScteResetTypeE) Type() protoreflect.EnumType {
	return &file_xponder_common_proto_enumTypes[0]
}

func (x ScteResetTypeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ScteResetTypeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ScteResetTypeE(num)
	return nil
}

// Deprecated: Use ScteResetTypeE.Descriptor instead.
func (ScteResetTypeE) EnumDescriptor() ([]byte, []int) {
	return file_xponder_common_proto_rawDescGZIP(), []int{0}
}

type ScteEvPriorityE int32

const (
	ScteEvPriorityE_SCTE_EV_EMERGENCY ScteEvPriorityE = 1
	ScteEvPriorityE_SCTE_EV_ALERT     ScteEvPriorityE = 2
	ScteEvPriorityE_SCTE_EV_CRITICAL  ScteEvPriorityE = 3
	ScteEvPriorityE_SCTE_EV_ERROR     ScteEvPriorityE = 4
	ScteEvPriorityE_SCTE_EV_WARNING   ScteEvPriorityE = 5
	ScteEvPriorityE_SCTE_EV_NOTICE    ScteEvPriorityE = 6
	ScteEvPriorityE_SCTE_EV_INFO      ScteEvPriorityE = 7
	ScteEvPriorityE_SCTE_EV_DEBUG     ScteEvPriorityE = 8
)

// Enum value maps for ScteEvPriorityE.
var (
	ScteEvPriorityE_name = map[int32]string{
		1: "SCTE_EV_EMERGENCY",
		2: "SCTE_EV_ALERT",
		3: "SCTE_EV_CRITICAL",
		4: "SCTE_EV_ERROR",
		5: "SCTE_EV_WARNING",
		6: "SCTE_EV_NOTICE",
		7: "SCTE_EV_INFO",
		8: "SCTE_EV_DEBUG",
	}
	ScteEvPriorityE_value = map[string]int32{
		"SCTE_EV_EMERGENCY": 1,
		"SCTE_EV_ALERT":     2,
		"SCTE_EV_CRITICAL":  3,
		"SCTE_EV_ERROR":     4,
		"SCTE_EV_WARNING":   5,
		"SCTE_EV_NOTICE":    6,
		"SCTE_EV_INFO":      7,
		"SCTE_EV_DEBUG":     8,
	}
)

func (x ScteEvPriorityE) Enum() *ScteEvPriorityE {
	p := new(ScteEvPriorityE)
	*p = x
	return p
}

func (x ScteEvPriorityE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScteEvPriorityE) Descriptor() protoreflect.EnumDescriptor {
	return file_xponder_common_proto_enumTypes[1].Descriptor()
}

func (ScteEvPriorityE) Type() protoreflect.EnumType {
	return &file_xponder_common_proto_enumTypes[1]
}

func (x ScteEvPriorityE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ScteEvPriorityE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ScteEvPriorityE(num)
	return nil
}

// Deprecated: Use ScteEvPriorityE.Descriptor instead.
func (ScteEvPriorityE) EnumDescriptor() ([]byte, []int) {
	return file_xponder_common_proto_rawDescGZIP(), []int{1}
}

var File_xponder_common_proto protoreflect.FileDescriptor

const file_xponder_common_proto_rawDesc = "" +
	"\n" +
	"\x14xponder/common.proto\x12\fscte.xponder*h\n" +
	"\x11scte_reset_type_e\x12\x13\n" +
	"\x0fSCTE_SOFT_RESET\x10\x01\x12\x13\n" +
	"\x0fSCTE_HARD_RESET\x10\x02\x12\x11\n" +
	"\rSCTE_NV_RESET\x10\x04\x12\x16\n" +
	"\x12SCTE_FACTORY_RESET\x10\b*\xb5\x01\n" +
	"\x12scte_ev_priority_e\x12\x15\n" +
	"\x11SCTE_EV_EMERGENCY\x10\x01\x12\x11\n" +
	"\rSCTE_EV_ALERT\x10\x02\x12\x14\n" +
	"\x10SCTE_EV_CRITICAL\x10\x03\x12\x11\n" +
	"\rSCTE_EV_ERROR\x10\x04\x12\x13\n" +
	"\x0fSCTE_EV_WARNING\x10\x05\x12\x12\n" +
	"\x0eSCTE_EV_NOTICE\x10\x06\x12\x10\n" +
	"\fSCTE_EV_INFO\x10\a\x12\x11\n" +
	"\rSCTE_EV_DEBUG\x10\bB3Z1github.com/enshure/scte-go/xponder_go;sctexponder"

var (
	file_xponder_common_proto_rawDescOnce sync.Once
	file_xponder_common_proto_rawDescData []byte
)

func file_xponder_common_proto_rawDescGZIP() []byte {
	file_xponder_common_proto_rawDescOnce.Do(func() {
		file_xponder_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xponder_common_proto_rawDesc), len(file_xponder_common_proto_rawDesc)))
	})
	return file_xponder_common_proto_rawDescData
}

var file_xponder_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_xponder_common_proto_goTypes = []any{
	(ScteResetTypeE)(0),  // 0: scte.xponder.scte_reset_type_e
	(ScteEvPriorityE)(0), // 1: scte.xponder.scte_ev_priority_e
}
var file_xponder_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xponder_common_proto_init() }
func file_xponder_common_proto_init() {
	if File_xponder_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xponder_common_proto_rawDesc), len(file_xponder_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xponder_common_proto_goTypes,
		DependencyIndexes: file_xponder_common_proto_depIdxs,
		EnumInfos:         file_xponder_common_proto_enumTypes,
	}.Build()
	File_xponder_common_proto = out.File
	file_xponder_common_proto_goTypes = nil
	file_xponder_common_proto_depIdxs = nil
}
