// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: xponder/controller.proto

package sctexponder

import (
	common_go "github.com/enshure/scte-go/common_go"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupId int32

const (
	GroupId_SYSTEM_STATUS        GroupId = 3
	GroupId_IDENTIFICATION       GroupId = 4
	GroupId_VENDOR               GroupId = 5
	GroupId_VERSION_SUMMARY      GroupId = 6
	GroupId_SENSOR_STATUS        GroupId = 8
	GroupId_SYSTEM_CFG           GroupId = 11
	GroupId_LOCATION             GroupId = 12
	GroupId_MANAGED_DEVICE       GroupId = 13
	GroupId_INFO_MODEL_SUPPORT   GroupId = 14
	GroupId_RESET_CAPABILITIES   GroupId = 20
	GroupId_RESET_HISTORY_STATUS GroupId = 21
	GroupId_RESET                GroupId = 22
	GroupId_DISABLE_AUTO_REBOOT  GroupId = 23
	GroupId_ENABLE_AUTO_REBOOT   GroupId = 24
	GroupId_RESET_NOTIFICATION   GroupId = 25
	GroupId_EVENT_CAPABILITIES   GroupId = 30
	GroupId_EVENT_STATUS         GroupId = 31
	GroupId_EVENT_LOG            GroupId = 32
	GroupId_EVENT_REPORTING_CFG  GroupId = 33
	GroupId_SYSLOG               GroupId = 34
	GroupId_EVENT_SYSLOG_STATUS  GroupId = 35
	GroupId_EVENT_THROTTLE_CFG   GroupId = 36
	GroupId_SYSLOG_SERVER_CFG    GroupId = 37
	GroupId_RESET_EVENT_LOG      GroupId = 38
	GroupId_SENSOR_DESCRIPTOR    GroupId = 40
	GroupId_SENSOR_READING       GroupId = 41
)

// Enum value maps for GroupId.
var (
	GroupId_name = map[int32]string{
		3:  "SYSTEM_STATUS",
		4:  "IDENTIFICATION",
		5:  "VENDOR",
		6:  "VERSION_SUMMARY",
		8:  "SENSOR_STATUS",
		11: "SYSTEM_CFG",
		12: "LOCATION",
		13: "MANAGED_DEVICE",
		14: "INFO_MODEL_SUPPORT",
		20: "RESET_CAPABILITIES",
		21: "RESET_HISTORY_STATUS",
		22: "RESET",
		23: "DISABLE_AUTO_REBOOT",
		24: "ENABLE_AUTO_REBOOT",
		25: "RESET_NOTIFICATION",
		30: "EVENT_CAPABILITIES",
		31: "EVENT_STATUS",
		32: "EVENT_LOG",
		33: "EVENT_REPORTING_CFG",
		34: "SYSLOG",
		35: "EVENT_SYSLOG_STATUS",
		36: "EVENT_THROTTLE_CFG",
		37: "SYSLOG_SERVER_CFG",
		38: "RESET_EVENT_LOG",
		40: "SENSOR_DESCRIPTOR",
		41: "SENSOR_READING",
	}
	GroupId_value = map[string]int32{
		"SYSTEM_STATUS":        3,
		"IDENTIFICATION":       4,
		"VENDOR":               5,
		"VERSION_SUMMARY":      6,
		"SENSOR_STATUS":        8,
		"SYSTEM_CFG":           11,
		"LOCATION":             12,
		"MANAGED_DEVICE":       13,
		"INFO_MODEL_SUPPORT":   14,
		"RESET_CAPABILITIES":   20,
		"RESET_HISTORY_STATUS": 21,
		"RESET":                22,
		"DISABLE_AUTO_REBOOT":  23,
		"ENABLE_AUTO_REBOOT":   24,
		"RESET_NOTIFICATION":   25,
		"EVENT_CAPABILITIES":   30,
		"EVENT_STATUS":         31,
		"EVENT_LOG":            32,
		"EVENT_REPORTING_CFG":  33,
		"SYSLOG":               34,
		"EVENT_SYSLOG_STATUS":  35,
		"EVENT_THROTTLE_CFG":   36,
		"SYSLOG_SERVER_CFG":    37,
		"RESET_EVENT_LOG":      38,
		"SENSOR_DESCRIPTOR":    40,
		"SENSOR_READING":       41,
	}
)

func (x GroupId) Enum() *GroupId {
	p := new(GroupId)
	*p = x
	return p
}

func (x GroupId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupId) Descriptor() protoreflect.EnumDescriptor {
	return file_xponder_controller_proto_enumTypes[0].Descriptor()
}

func (GroupId) Type() protoreflect.EnumType {
	return &file_xponder_controller_proto_enumTypes[0]
}

func (x GroupId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *GroupId) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = GroupId(num)
	return nil
}

// Deprecated: Use GroupId.Descriptor instead.
func (GroupId) EnumDescriptor() ([]byte, []int) {
	return file_xponder_controller_proto_rawDescGZIP(), []int{0}
}

type GroupSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       *GroupId               `protobuf:"varint,1,opt,name=group_id,json=groupId,enum=scte.xponder.GroupId" json:"group_id,omitempty"`
	Index         *uint32                `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSelector) Reset() {
	*x = GroupSelector{}
	mi := &file_xponder_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSelector) ProtoMessage() {}

func (x *GroupSelector) ProtoReflect() protoreflect.Message {
	mi := &file_xponder_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSelector.ProtoReflect.Descriptor instead.
func (*GroupSelector) Descriptor() ([]byte, []int) {
	return file_xponder_controller_proto_rawDescGZIP(), []int{0}
}

func (x *GroupSelector) GetGroupId() GroupId {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return GroupId_SYSTEM_STATUS
}

func (x *GroupSelector) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

type ControllerGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*GroupSelector       `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerGetRequest) Reset() {
	*x = ControllerGetRequest{}
	mi := &file_xponder_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerGetRequest) ProtoMessage() {}

func (x *ControllerGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xponder_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerGetRequest.ProtoReflect.Descriptor instead.
func (*ControllerGetRequest) Descriptor() ([]byte, []int) {
	return file_xponder_controller_proto_rawDescGZIP(), []int{1}
}

func (x *ControllerGetRequest) GetGroups() []*GroupSelector {
	if x != nil {
		return x.Groups
	}
	return nil
}

type ControllerGetGroupResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	GroupId      *GroupId               `protobuf:"varint,1,opt,name=group_id,json=groupId,enum=scte.xponder.GroupId" json:"group_id,omitempty"`
	Index        *uint32                `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	ErrorTag     *common_go.ErrorTagE   `protobuf:"varint,3,opt,name=error_tag,json=errorTag,enum=scte.common.ErrorTagE" json:"error_tag,omitempty"`
	ErrorMessage *string                `protobuf:"bytes,4,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControllerGetGroupResponse_SystemStatus
	//	*ControllerGetGroupResponse_Identification
	//	*ControllerGetGroupResponse_Vendor
	//	*ControllerGetGroupResponse_VersionSummary
	//	*ControllerGetGroupResponse_SystemCfg
	//	*ControllerGetGroupResponse_Location
	//	*ControllerGetGroupResponse_ResetCapabilities
	//	*ControllerGetGroupResponse_ResetHistoryStatus
	//	*ControllerGetGroupResponse_Reset_
	//	*ControllerGetGroupResponse_DisableAutoReboot
	//	*ControllerGetGroupResponse_EnableAutoReboot
	//	*ControllerGetGroupResponse_EventCapabilities
	//	*ControllerGetGroupResponse_EventStatus
	//	*ControllerGetGroupResponse_EventLog
	//	*ControllerGetGroupResponse_EventReportingCfg
	//	*ControllerGetGroupResponse_Sensors
	//	*ControllerGetGroupResponse_SensorDescriptors
	//	*ControllerGetGroupResponse_SensorsData
	//	*ControllerGetGroupResponse_ManagedDevice
	//	*ControllerGetGroupResponse_InfoModelSupport
	//	*ControllerGetGroupResponse_ResetNotification
	//	*ControllerGetGroupResponse_Syslog
	//	*ControllerGetGroupResponse_EventSyslogStatus
	//	*ControllerGetGroupResponse_EventThrottleCfg
	//	*ControllerGetGroupResponse_SyslogServerCfg
	//	*ControllerGetGroupResponse_ResetEventLog
	Payload       isControllerGetGroupResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerGetGroupResponse) Reset() {
	*x = ControllerGetGroupResponse{}
	mi := &file_xponder_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerGetGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerGetGroupResponse) ProtoMessage() {}

func (x *ControllerGetGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xponder_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerGetGroupResponse.ProtoReflect.Descriptor instead.
func (*ControllerGetGroupResponse) Descriptor() ([]byte, []int) {
	return file_xponder_controller_proto_rawDescGZIP(), []int{2}
}

func (x *ControllerGetGroupResponse) GetGroupId() GroupId {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return GroupId_SYSTEM_STATUS
}

func (x *ControllerGetGroupResponse) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *ControllerGetGroupResponse) GetErrorTag() common_go.ErrorTagE {
	if x != nil && x.ErrorTag != nil {
		return *x.ErrorTag
	}
	return common_go.ErrorTagE(0)
}

func (x *ControllerGetGroupResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *ControllerGetGroupResponse) GetPayload() isControllerGetGroupResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetSystemStatus() *common_go.SystemStatus {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_SystemStatus); ok {
			return x.SystemStatus
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetIdentification() *common_go.Identification {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_Identification); ok {
			return x.Identification
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetVendor() *common_go.Vendor {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_Vendor); ok {
			return x.Vendor
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetVersionSummary() *common_go.VersionSummary {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_VersionSummary); ok {
			return x.VersionSummary
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetSystemCfg() *common_go.SystemCfg {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_SystemCfg); ok {
			return x.SystemCfg
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetLocation() *common_go.Location {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_Location); ok {
			return x.Location
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetResetCapabilities() *ResetCapabilities {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_ResetCapabilities); ok {
			return x.ResetCapabilities
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetResetHistoryStatus() *ResetHistoryStatus {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_ResetHistoryStatus); ok {
			return x.ResetHistoryStatus
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetReset_() *Reset {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_Reset_); ok {
			return x.Reset_
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetDisableAutoReboot() *DisableAutoReboot {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_DisableAutoReboot); ok {
			return x.DisableAutoReboot
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetEnableAutoReboot() *EnableAutoReboot {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_EnableAutoReboot); ok {
			return x.EnableAutoReboot
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetEventCapabilities() *common_go.EventCapabilities {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_EventCapabilities); ok {
			return x.EventCapabilities
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetEventStatus() *common_go.EventStatus {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_EventStatus); ok {
			return x.EventStatus
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetEventLog() *common_go.EventLog {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_EventLog); ok {
			return x.EventLog
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetEventReportingCfg() *common_go.EventReportingCfg {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_EventReportingCfg); ok {
			return x.EventReportingCfg
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetSensors() *common_go.Sensors {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_Sensors); ok {
			return x.Sensors
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetSensorDescriptors() *common_go.SensorDescriptors {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_SensorDescriptors); ok {
			return x.SensorDescriptors
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetSensorsData() *common_go.SensorsData {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_SensorsData); ok {
			return x.SensorsData
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetManagedDevice() *ManagedDevice {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_ManagedDevice); ok {
			return x.ManagedDevice
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetInfoModelSupport() *InfoModelSupport {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_InfoModelSupport); ok {
			return x.InfoModelSupport
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetResetNotification() *ResetNotification {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_ResetNotification); ok {
			return x.ResetNotification
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetSyslog() *common_go.Syslog {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_Syslog); ok {
			return x.Syslog
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetEventSyslogStatus() *common_go.EventSyslogStatus {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_EventSyslogStatus); ok {
			return x.EventSyslogStatus
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetEventThrottleCfg() *common_go.EventThrottleCfg {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_EventThrottleCfg); ok {
			return x.EventThrottleCfg
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetSyslogServerCfg() *common_go.SyslogServerCfg {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_SyslogServerCfg); ok {
			return x.SyslogServerCfg
		}
	}
	return nil
}

func (x *ControllerGetGroupResponse) GetResetEventLog() *common_go.ResetEventLog {
	if x != nil {
		if x, ok := x.Payload.(*ControllerGetGroupResponse_ResetEventLog); ok {
			return x.ResetEventLog
		}
	}
	return nil
}

type isControllerGetGroupResponse_Payload interface {
	isControllerGetGroupResponse_Payload()
}

type ControllerGetGroupResponse_SystemStatus struct {
	SystemStatus *common_go.SystemStatus `protobuf:"bytes,12,opt,name=system_status,json=systemStatus,oneof"`
}

type ControllerGetGroupResponse_Identification struct {
	Identification *common_go.Identification `protobuf:"bytes,13,opt,name=identification,oneof"`
}

type ControllerGetGroupResponse_Vendor struct {
	Vendor *common_go.Vendor `protobuf:"bytes,14,opt,name=vendor,oneof"`
}

type ControllerGetGroupResponse_VersionSummary struct {
	VersionSummary *common_go.VersionSummary `protobuf:"bytes,15,opt,name=version_summary,json=versionSummary,oneof"`
}

type ControllerGetGroupResponse_SystemCfg struct {
	SystemCfg *common_go.SystemCfg `protobuf:"bytes,19,opt,name=system_cfg,json=systemCfg,oneof"`
}

type ControllerGetGroupResponse_Location struct {
	Location *common_go.Location `protobuf:"bytes,20,opt,name=location,oneof"`
}

type ControllerGetGroupResponse_ResetCapabilities struct {
	ResetCapabilities *ResetCapabilities `protobuf:"bytes,21,opt,name=reset_capabilities,json=resetCapabilities,oneof"`
}

type ControllerGetGroupResponse_ResetHistoryStatus struct {
	ResetHistoryStatus *ResetHistoryStatus `protobuf:"bytes,22,opt,name=reset_history_status,json=resetHistoryStatus,oneof"`
}

type ControllerGetGroupResponse_Reset_ struct {
	Reset_ *Reset `protobuf:"bytes,23,opt,name=reset,oneof"`
}

type ControllerGetGroupResponse_DisableAutoReboot struct {
	DisableAutoReboot *DisableAutoReboot `protobuf:"bytes,24,opt,name=disable_auto_reboot,json=disableAutoReboot,oneof"`
}

type ControllerGetGroupResponse_EnableAutoReboot struct {
	EnableAutoReboot *EnableAutoReboot `protobuf:"bytes,25,opt,name=enable_auto_reboot,json=enableAutoReboot,oneof"`
}

type ControllerGetGroupResponse_EventCapabilities struct {
	EventCapabilities *common_go.EventCapabilities `protobuf:"bytes,26,opt,name=event_capabilities,json=eventCapabilities,oneof"`
}

type ControllerGetGroupResponse_EventStatus struct {
	EventStatus *common_go.EventStatus `protobuf:"bytes,27,opt,name=event_status,json=eventStatus,oneof"`
}

type ControllerGetGroupResponse_EventLog struct {
	EventLog *common_go.EventLog `protobuf:"bytes,28,opt,name=event_log,json=eventLog,oneof"`
}

type ControllerGetGroupResponse_EventReportingCfg struct {
	EventReportingCfg *common_go.EventReportingCfg `protobuf:"bytes,29,opt,name=event_reporting_cfg,json=eventReportingCfg,oneof"`
}

type ControllerGetGroupResponse_Sensors struct {
	Sensors *common_go.Sensors `protobuf:"bytes,32,opt,name=sensors,oneof"`
}

type ControllerGetGroupResponse_SensorDescriptors struct {
	SensorDescriptors *common_go.SensorDescriptors `protobuf:"bytes,33,opt,name=sensor_descriptors,json=sensorDescriptors,oneof"`
}

type ControllerGetGroupResponse_SensorsData struct {
	SensorsData *common_go.SensorsData `protobuf:"bytes,34,opt,name=sensors_data,json=sensorsData,oneof"`
}

type ControllerGetGroupResponse_ManagedDevice struct {
	ManagedDevice *ManagedDevice `protobuf:"bytes,40,opt,name=managed_device,json=managedDevice,oneof"`
}

type ControllerGetGroupResponse_InfoModelSupport struct {
	InfoModelSupport *InfoModelSupport `protobuf:"bytes,41,opt,name=info_model_support,json=infoModelSupport,oneof"`
}

type ControllerGetGroupResponse_ResetNotification struct {
	ResetNotification *ResetNotification `protobuf:"bytes,43,opt,name=reset_notification,json=resetNotification,oneof"`
}

type ControllerGetGroupResponse_Syslog struct {
	Syslog *common_go.Syslog `protobuf:"bytes,44,opt,name=syslog,oneof"`
}

type ControllerGetGroupResponse_EventSyslogStatus struct {
	EventSyslogStatus *common_go.EventSyslogStatus `protobuf:"bytes,45,opt,name=event_syslog_status,json=eventSyslogStatus,oneof"`
}

type ControllerGetGroupResponse_EventThrottleCfg struct {
	EventThrottleCfg *common_go.EventThrottleCfg `protobuf:"bytes,46,opt,name=event_throttle_cfg,json=eventThrottleCfg,oneof"`
}

type ControllerGetGroupResponse_SyslogServerCfg struct {
	SyslogServerCfg *common_go.SyslogServerCfg `protobuf:"bytes,47,opt,name=syslog_server_cfg,json=syslogServerCfg,oneof"`
}

type ControllerGetGroupResponse_ResetEventLog struct {
	ResetEventLog *common_go.ResetEventLog `protobuf:"bytes,48,opt,name=reset_event_log,json=resetEventLog,oneof"`
}

func (*ControllerGetGroupResponse_SystemStatus) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_Identification) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_Vendor) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_VersionSummary) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_SystemCfg) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_Location) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_ResetCapabilities) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_ResetHistoryStatus) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_Reset_) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_DisableAutoReboot) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_EnableAutoReboot) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_EventCapabilities) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_EventStatus) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_EventLog) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_EventReportingCfg) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_Sensors) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_SensorDescriptors) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_SensorsData) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_ManagedDevice) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_InfoModelSupport) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_ResetNotification) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_Syslog) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_EventSyslogStatus) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_EventThrottleCfg) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_SyslogServerCfg) isControllerGetGroupResponse_Payload() {}

func (*ControllerGetGroupResponse_ResetEventLog) isControllerGetGroupResponse_Payload() {}

type ControllerGetResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Groups        []*ControllerGetGroupResponse `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerGetResponse) Reset() {
	*x = ControllerGetResponse{}
	mi := &file_xponder_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerGetResponse) ProtoMessage() {}

func (x *ControllerGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xponder_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerGetResponse.ProtoReflect.Descriptor instead.
func (*ControllerGetResponse) Descriptor() ([]byte, []int) {
	return file_xponder_controller_proto_rawDescGZIP(), []int{3}
}

func (x *ControllerGetResponse) GetGroups() []*ControllerGetGroupResponse {
	if x != nil {
		return x.Groups
	}
	return nil
}

type ControllerSetRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	GroupId *GroupId               `protobuf:"varint,1,opt,name=group_id,json=groupId,enum=scte.xponder.GroupId" json:"group_id,omitempty"`
	Index   *uint32                `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControllerSetRequest_SystemCfg
	//	*ControllerSetRequest_Location
	//	*ControllerSetRequest_Reset_
	//	*ControllerSetRequest_DisableAutoReboot
	//	*ControllerSetRequest_EnableAutoReboot
	//	*ControllerSetRequest_EventReportingCfg
	//	*ControllerSetRequest_EventThrottleCfg
	//	*ControllerSetRequest_SyslogServerCfg
	//	*ControllerSetRequest_ResetEventLog
	Payload       isControllerSetRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerSetRequest) Reset() {
	*x = ControllerSetRequest{}
	mi := &file_xponder_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerSetRequest) ProtoMessage() {}

func (x *ControllerSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xponder_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerSetRequest.ProtoReflect.Descriptor instead.
func (*ControllerSetRequest) Descriptor() ([]byte, []int) {
	return file_xponder_controller_proto_rawDescGZIP(), []int{4}
}

func (x *ControllerSetRequest) GetGroupId() GroupId {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return GroupId_SYSTEM_STATUS
}

func (x *ControllerSetRequest) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *ControllerSetRequest) GetPayload() isControllerSetRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControllerSetRequest) GetSystemCfg() *common_go.SystemCfg {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSetRequest_SystemCfg); ok {
			return x.SystemCfg
		}
	}
	return nil
}

func (x *ControllerSetRequest) GetLocation() *common_go.Location {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSetRequest_Location); ok {
			return x.Location
		}
	}
	return nil
}

func (x *ControllerSetRequest) GetReset_() *Reset {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSetRequest_Reset_); ok {
			return x.Reset_
		}
	}
	return nil
}

func (x *ControllerSetRequest) GetDisableAutoReboot() *DisableAutoReboot {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSetRequest_DisableAutoReboot); ok {
			return x.DisableAutoReboot
		}
	}
	return nil
}

func (x *ControllerSetRequest) GetEnableAutoReboot() *EnableAutoReboot {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSetRequest_EnableAutoReboot); ok {
			return x.EnableAutoReboot
		}
	}
	return nil
}

func (x *ControllerSetRequest) GetEventReportingCfg() *common_go.EventReportingCfg {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSetRequest_EventReportingCfg); ok {
			return x.EventReportingCfg
		}
	}
	return nil
}

func (x *ControllerSetRequest) GetEventThrottleCfg() *common_go.EventThrottleCfg {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSetRequest_EventThrottleCfg); ok {
			return x.EventThrottleCfg
		}
	}
	return nil
}

func (x *ControllerSetRequest) GetSyslogServerCfg() *common_go.SyslogServerCfg {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSetRequest_SyslogServerCfg); ok {
			return x.SyslogServerCfg
		}
	}
	return nil
}

func (x *ControllerSetRequest) GetResetEventLog() *common_go.ResetEventLog {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSetRequest_ResetEventLog); ok {
			return x.ResetEventLog
		}
	}
	return nil
}

type isControllerSetRequest_Payload interface {
	isControllerSetRequest_Payload()
}

type ControllerSetRequest_SystemCfg struct {
	SystemCfg *common_go.SystemCfg `protobuf:"bytes,10,opt,name=system_cfg,json=systemCfg,oneof"`
}

type ControllerSetRequest_Location struct {
	Location *common_go.Location `protobuf:"bytes,11,opt,name=location,oneof"`
}

type ControllerSetRequest_Reset_ struct {
	Reset_ *Reset `protobuf:"bytes,12,opt,name=reset,oneof"`
}

type ControllerSetRequest_DisableAutoReboot struct {
	DisableAutoReboot *DisableAutoReboot `protobuf:"bytes,13,opt,name=disable_auto_reboot,json=disableAutoReboot,oneof"`
}

type ControllerSetRequest_EnableAutoReboot struct {
	EnableAutoReboot *EnableAutoReboot `protobuf:"bytes,14,opt,name=enable_auto_reboot,json=enableAutoReboot,oneof"`
}

type ControllerSetRequest_EventReportingCfg struct {
	EventReportingCfg *common_go.EventReportingCfg `protobuf:"bytes,15,opt,name=event_reporting_cfg,json=eventReportingCfg,oneof"`
}

type ControllerSetRequest_EventThrottleCfg struct {
	EventThrottleCfg *common_go.EventThrottleCfg `protobuf:"bytes,40,opt,name=event_throttle_cfg,json=eventThrottleCfg,oneof"`
}

type ControllerSetRequest_SyslogServerCfg struct {
	SyslogServerCfg *common_go.SyslogServerCfg `protobuf:"bytes,41,opt,name=syslog_server_cfg,json=syslogServerCfg,oneof"`
}

type ControllerSetRequest_ResetEventLog struct {
	ResetEventLog *common_go.ResetEventLog `protobuf:"bytes,42,opt,name=reset_event_log,json=resetEventLog,oneof"`
}

func (*ControllerSetRequest_SystemCfg) isControllerSetRequest_Payload() {}

func (*ControllerSetRequest_Location) isControllerSetRequest_Payload() {}

func (*ControllerSetRequest_Reset_) isControllerSetRequest_Payload() {}

func (*ControllerSetRequest_DisableAutoReboot) isControllerSetRequest_Payload() {}

func (*ControllerSetRequest_EnableAutoReboot) isControllerSetRequest_Payload() {}

func (*ControllerSetRequest_EventReportingCfg) isControllerSetRequest_Payload() {}

func (*ControllerSetRequest_EventThrottleCfg) isControllerSetRequest_Payload() {}

func (*ControllerSetRequest_SyslogServerCfg) isControllerSetRequest_Payload() {}

func (*ControllerSetRequest_ResetEventLog) isControllerSetRequest_Payload() {}

type ControllerSetResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	GroupId      *GroupId               `protobuf:"varint,1,opt,name=group_id,json=groupId,enum=scte.xponder.GroupId" json:"group_id,omitempty"`
	Index        *uint32                `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	Result       *bool                  `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
	ErrorTag     *common_go.ErrorTagE   `protobuf:"varint,4,opt,name=error_tag,json=errorTag,enum=scte.common.ErrorTagE" json:"error_tag,omitempty"`
	ErrorMessage *string                `protobuf:"bytes,5,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ControllerSetResponse_SystemCfg
	//	*ControllerSetResponse_Location
	//	*ControllerSetResponse_Reset_
	//	*ControllerSetResponse_DisableAutoReboot
	//	*ControllerSetResponse_EnableAutoReboot
	//	*ControllerSetResponse_EventReportingCfg
	//	*ControllerSetResponse_EventThrottleCfg
	//	*ControllerSetResponse_SyslogServerCfg
	//	*ControllerSetResponse_ResetEventLog
	Payload       isControllerSetResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerSetResponse) Reset() {
	*x = ControllerSetResponse{}
	mi := &file_xponder_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerSetResponse) ProtoMessage() {}

func (x *ControllerSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xponder_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerSetResponse.ProtoReflect.Descriptor instead.
func (*ControllerSetResponse) Descriptor() ([]byte, []int) {
	return file_xponder_controller_proto_rawDescGZIP(), []int{5}
}

func (x *ControllerSetResponse) GetGroupId() GroupId {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return GroupId_SYSTEM_STATUS
}

func (x *ControllerSetResponse) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *ControllerSetResponse) GetResult() bool {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return false
}

func (x *ControllerSetResponse) GetErrorTag() common_go.ErrorTagE {
	if x != nil && x.ErrorTag != nil {
		return *x.ErrorTag
	}
	return common_go.ErrorTagE(0)
}

func (x *ControllerSetResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *ControllerSetResponse) GetPayload() isControllerSetResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControllerSetResponse) GetSystemCfg() *common_go.SystemCfg {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSetResponse_SystemCfg); ok {
			return x.SystemCfg
		}
	}
	return nil
}

func (x *ControllerSetResponse) GetLocation() *common_go.Location {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSetResponse_Location); ok {
			return x.Location
		}
	}
	return nil
}

func (x *ControllerSetResponse) GetReset_() *Reset {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSetResponse_Reset_); ok {
			return x.Reset_
		}
	}
	return nil
}

func (x *ControllerSetResponse) GetDisableAutoReboot() *DisableAutoReboot {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSetResponse_DisableAutoReboot); ok {
			return x.DisableAutoReboot
		}
	}
	return nil
}

func (x *ControllerSetResponse) GetEnableAutoReboot() *EnableAutoReboot {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSetResponse_EnableAutoReboot); ok {
			return x.EnableAutoReboot
		}
	}
	return nil
}

func (x *ControllerSetResponse) GetEventReportingCfg() *common_go.EventReportingCfg {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSetResponse_EventReportingCfg); ok {
			return x.EventReportingCfg
		}
	}
	return nil
}

func (x *ControllerSetResponse) GetEventThrottleCfg() *common_go.EventThrottleCfg {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSetResponse_EventThrottleCfg); ok {
			return x.EventThrottleCfg
		}
	}
	return nil
}

func (x *ControllerSetResponse) GetSyslogServerCfg() *common_go.SyslogServerCfg {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSetResponse_SyslogServerCfg); ok {
			return x.SyslogServerCfg
		}
	}
	return nil
}

func (x *ControllerSetResponse) GetResetEventLog() *common_go.ResetEventLog {
	if x != nil {
		if x, ok := x.Payload.(*ControllerSetResponse_ResetEventLog); ok {
			return x.ResetEventLog
		}
	}
	return nil
}

type isControllerSetResponse_Payload interface {
	isControllerSetResponse_Payload()
}

type ControllerSetResponse_SystemCfg struct {
	SystemCfg *common_go.SystemCfg `protobuf:"bytes,10,opt,name=system_cfg,json=systemCfg,oneof"`
}

type ControllerSetResponse_Location struct {
	Location *common_go.Location `protobuf:"bytes,11,opt,name=location,oneof"`
}

type ControllerSetResponse_Reset_ struct {
	Reset_ *Reset `protobuf:"bytes,12,opt,name=reset,oneof"`
}

type ControllerSetResponse_DisableAutoReboot struct {
	DisableAutoReboot *DisableAutoReboot `protobuf:"bytes,13,opt,name=disable_auto_reboot,json=disableAutoReboot,oneof"`
}

type ControllerSetResponse_EnableAutoReboot struct {
	EnableAutoReboot *EnableAutoReboot `protobuf:"bytes,14,opt,name=enable_auto_reboot,json=enableAutoReboot,oneof"`
}

type ControllerSetResponse_EventReportingCfg struct {
	EventReportingCfg *common_go.EventReportingCfg `protobuf:"bytes,15,opt,name=event_reporting_cfg,json=eventReportingCfg,oneof"`
}

type ControllerSetResponse_EventThrottleCfg struct {
	EventThrottleCfg *common_go.EventThrottleCfg `protobuf:"bytes,40,opt,name=event_throttle_cfg,json=eventThrottleCfg,oneof"`
}

type ControllerSetResponse_SyslogServerCfg struct {
	SyslogServerCfg *common_go.SyslogServerCfg `protobuf:"bytes,41,opt,name=syslog_server_cfg,json=syslogServerCfg,oneof"`
}

type ControllerSetResponse_ResetEventLog struct {
	ResetEventLog *common_go.ResetEventLog `protobuf:"bytes,42,opt,name=reset_event_log,json=resetEventLog,oneof"`
}

func (*ControllerSetResponse_SystemCfg) isControllerSetResponse_Payload() {}

func (*ControllerSetResponse_Location) isControllerSetResponse_Payload() {}

func (*ControllerSetResponse_Reset_) isControllerSetResponse_Payload() {}

func (*ControllerSetResponse_DisableAutoReboot) isControllerSetResponse_Payload() {}

func (*ControllerSetResponse_EnableAutoReboot) isControllerSetResponse_Payload() {}

func (*ControllerSetResponse_EventReportingCfg) isControllerSetResponse_Payload() {}

func (*ControllerSetResponse_EventThrottleCfg) isControllerSetResponse_Payload() {}

func (*ControllerSetResponse_SyslogServerCfg) isControllerSetResponse_Payload() {}

func (*ControllerSetResponse_ResetEventLog) isControllerSetResponse_Payload() {}

var File_xponder_controller_proto protoreflect.FileDescriptor

const file_xponder_controller_proto_rawDesc = "" +
	"\n" +
	"\x18xponder/controller.proto\x12\fscte.xponder\x1a\x14xponder/common.proto\x1a\x1acommon/device_common.proto\x1a\x19common/error_common.proto\x1a\x19common/event_common.proto\x1a\x1acommon/sensor_common.proto\x1a\x1acommon/system_common.proto\x1a\x1bcommon/version_common.proto\x1a\x14xponder/system.proto\x1a\x13xponder/reset.proto\x1a\x14xponder/events.proto\"W\n" +
	"\rGroupSelector\x120\n" +
	"\bgroup_id\x18\x01 \x01(\x0e2\x15.scte.xponder.GroupIdR\agroupId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\"K\n" +
	"\x14ControllerGetRequest\x123\n" +
	"\x06groups\x18\x01 \x03(\v2\x1b.scte.xponder.GroupSelectorR\x06groups\"\xd5\x0f\n" +
	"\x1aControllerGetGroupResponse\x120\n" +
	"\bgroup_id\x18\x01 \x01(\x0e2\x15.scte.xponder.GroupIdR\agroupId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x125\n" +
	"\terror_tag\x18\x03 \x01(\x0e2\x18.scte.common.error_tag_eR\berrorTag\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12@\n" +
	"\rsystem_status\x18\f \x01(\v2\x19.scte.common.SystemStatusH\x00R\fsystemStatus\x12E\n" +
	"\x0eidentification\x18\r \x01(\v2\x1b.scte.common.IdentificationH\x00R\x0eidentification\x12-\n" +
	"\x06vendor\x18\x0e \x01(\v2\x13.scte.common.VendorH\x00R\x06vendor\x12F\n" +
	"\x0fversion_summary\x18\x0f \x01(\v2\x1b.scte.common.VersionSummaryH\x00R\x0eversionSummary\x127\n" +
	"\n" +
	"system_cfg\x18\x13 \x01(\v2\x16.scte.common.SystemCfgH\x00R\tsystemCfg\x123\n" +
	"\blocation\x18\x14 \x01(\v2\x15.scte.common.LocationH\x00R\blocation\x12P\n" +
	"\x12reset_capabilities\x18\x15 \x01(\v2\x1f.scte.xponder.ResetCapabilitiesH\x00R\x11resetCapabilities\x12T\n" +
	"\x14reset_history_status\x18\x16 \x01(\v2 .scte.xponder.ResetHistoryStatusH\x00R\x12resetHistoryStatus\x12+\n" +
	"\x05reset\x18\x17 \x01(\v2\x13.scte.xponder.ResetH\x00R\x05reset\x12Q\n" +
	"\x13disable_auto_reboot\x18\x18 \x01(\v2\x1f.scte.xponder.DisableAutoRebootH\x00R\x11disableAutoReboot\x12N\n" +
	"\x12enable_auto_reboot\x18\x19 \x01(\v2\x1e.scte.xponder.EnableAutoRebootH\x00R\x10enableAutoReboot\x12O\n" +
	"\x12event_capabilities\x18\x1a \x01(\v2\x1e.scte.common.EventCapabilitiesH\x00R\x11eventCapabilities\x12=\n" +
	"\fevent_status\x18\x1b \x01(\v2\x18.scte.common.EventStatusH\x00R\veventStatus\x124\n" +
	"\tevent_log\x18\x1c \x01(\v2\x15.scte.common.EventLogH\x00R\beventLog\x12P\n" +
	"\x13event_reporting_cfg\x18\x1d \x01(\v2\x1e.scte.common.EventReportingCfgH\x00R\x11eventReportingCfg\x120\n" +
	"\asensors\x18  \x01(\v2\x14.scte.common.SensorsH\x00R\asensors\x12O\n" +
	"\x12sensor_descriptors\x18! \x01(\v2\x1e.scte.common.SensorDescriptorsH\x00R\x11sensorDescriptors\x12=\n" +
	"\fsensors_data\x18\" \x01(\v2\x18.scte.common.SensorsDataH\x00R\vsensorsData\x12D\n" +
	"\x0emanaged_device\x18( \x01(\v2\x1b.scte.xponder.ManagedDeviceH\x00R\rmanagedDevice\x12N\n" +
	"\x12info_model_support\x18) \x01(\v2\x1e.scte.xponder.InfoModelSupportH\x00R\x10infoModelSupport\x12P\n" +
	"\x12reset_notification\x18+ \x01(\v2\x1f.scte.xponder.ResetNotificationH\x00R\x11resetNotification\x12-\n" +
	"\x06syslog\x18, \x01(\v2\x13.scte.common.SyslogH\x00R\x06syslog\x12P\n" +
	"\x13event_syslog_status\x18- \x01(\v2\x1e.scte.common.EventSyslogStatusH\x00R\x11eventSyslogStatus\x12M\n" +
	"\x12event_throttle_cfg\x18. \x01(\v2\x1d.scte.common.EventThrottleCfgH\x00R\x10eventThrottleCfg\x12J\n" +
	"\x11syslog_server_cfg\x18/ \x01(\v2\x1c.scte.common.SyslogServerCfgH\x00R\x0fsyslogServerCfg\x12D\n" +
	"\x0freset_event_log\x180 \x01(\v2\x1a.scte.common.ResetEventLogH\x00R\rresetEventLogB\t\n" +
	"\apayload\"Y\n" +
	"\x15ControllerGetResponse\x12@\n" +
	"\x06groups\x18\x01 \x03(\v2(.scte.xponder.ControllerGetGroupResponseR\x06groups\"\xda\x05\n" +
	"\x14ControllerSetRequest\x120\n" +
	"\bgroup_id\x18\x01 \x01(\x0e2\x15.scte.xponder.GroupIdR\agroupId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x127\n" +
	"\n" +
	"system_cfg\x18\n" +
	" \x01(\v2\x16.scte.common.SystemCfgH\x00R\tsystemCfg\x123\n" +
	"\blocation\x18\v \x01(\v2\x15.scte.common.LocationH\x00R\blocation\x12+\n" +
	"\x05reset\x18\f \x01(\v2\x13.scte.xponder.ResetH\x00R\x05reset\x12Q\n" +
	"\x13disable_auto_reboot\x18\r \x01(\v2\x1f.scte.xponder.DisableAutoRebootH\x00R\x11disableAutoReboot\x12N\n" +
	"\x12enable_auto_reboot\x18\x0e \x01(\v2\x1e.scte.xponder.EnableAutoRebootH\x00R\x10enableAutoReboot\x12P\n" +
	"\x13event_reporting_cfg\x18\x0f \x01(\v2\x1e.scte.common.EventReportingCfgH\x00R\x11eventReportingCfg\x12M\n" +
	"\x12event_throttle_cfg\x18( \x01(\v2\x1d.scte.common.EventThrottleCfgH\x00R\x10eventThrottleCfg\x12J\n" +
	"\x11syslog_server_cfg\x18) \x01(\v2\x1c.scte.common.SyslogServerCfgH\x00R\x0fsyslogServerCfg\x12D\n" +
	"\x0freset_event_log\x18* \x01(\v2\x1a.scte.common.ResetEventLogH\x00R\rresetEventLogB\t\n" +
	"\apayload\"\xcf\x06\n" +
	"\x15ControllerSetResponse\x120\n" +
	"\bgroup_id\x18\x01 \x01(\x0e2\x15.scte.xponder.GroupIdR\agroupId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12\x16\n" +
	"\x06result\x18\x03 \x01(\bR\x06result\x125\n" +
	"\terror_tag\x18\x04 \x01(\x0e2\x18.scte.common.error_tag_eR\berrorTag\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x127\n" +
	"\n" +
	"system_cfg\x18\n" +
	" \x01(\v2\x16.scte.common.SystemCfgH\x00R\tsystemCfg\x123\n" +
	"\blocation\x18\v \x01(\v2\x15.scte.common.LocationH\x00R\blocation\x12+\n" +
	"\x05reset\x18\f \x01(\v2\x13.scte.xponder.ResetH\x00R\x05reset\x12Q\n" +
	"\x13disable_auto_reboot\x18\r \x01(\v2\x1f.scte.xponder.DisableAutoRebootH\x00R\x11disableAutoReboot\x12N\n" +
	"\x12enable_auto_reboot\x18\x0e \x01(\v2\x1e.scte.xponder.EnableAutoRebootH\x00R\x10enableAutoReboot\x12P\n" +
	"\x13event_reporting_cfg\x18\x0f \x01(\v2\x1e.scte.common.EventReportingCfgH\x00R\x11eventReportingCfg\x12M\n" +
	"\x12event_throttle_cfg\x18( \x01(\v2\x1d.scte.common.EventThrottleCfgH\x00R\x10eventThrottleCfg\x12J\n" +
	"\x11syslog_server_cfg\x18) \x01(\v2\x1c.scte.common.SyslogServerCfgH\x00R\x0fsyslogServerCfg\x12D\n" +
	"\x0freset_event_log\x18* \x01(\v2\x1a.scte.common.ResetEventLogH\x00R\rresetEventLogB\t\n" +
	"\apayload*\x9a\x04\n" +
	"\aGroupId\x12\x11\n" +
	"\rSYSTEM_STATUS\x10\x03\x12\x12\n" +
	"\x0eIDENTIFICATION\x10\x04\x12\n" +
	"\n" +
	"\x06VENDOR\x10\x05\x12\x13\n" +
	"\x0fVERSION_SUMMARY\x10\x06\x12\x11\n" +
	"\rSENSOR_STATUS\x10\b\x12\x0e\n" +
	"\n" +
	"SYSTEM_CFG\x10\v\x12\f\n" +
	"\bLOCATION\x10\f\x12\x12\n" +
	"\x0eMANAGED_DEVICE\x10\r\x12\x16\n" +
	"\x12INFO_MODEL_SUPPORT\x10\x0e\x12\x16\n" +
	"\x12RESET_CAPABILITIES\x10\x14\x12\x18\n" +
	"\x14RESET_HISTORY_STATUS\x10\x15\x12\t\n" +
	"\x05RESET\x10\x16\x12\x17\n" +
	"\x13DISABLE_AUTO_REBOOT\x10\x17\x12\x16\n" +
	"\x12ENABLE_AUTO_REBOOT\x10\x18\x12\x16\n" +
	"\x12RESET_NOTIFICATION\x10\x19\x12\x16\n" +
	"\x12EVENT_CAPABILITIES\x10\x1e\x12\x10\n" +
	"\fEVENT_STATUS\x10\x1f\x12\r\n" +
	"\tEVENT_LOG\x10 \x12\x17\n" +
	"\x13EVENT_REPORTING_CFG\x10!\x12\n" +
	"\n" +
	"\x06SYSLOG\x10\"\x12\x17\n" +
	"\x13EVENT_SYSLOG_STATUS\x10#\x12\x16\n" +
	"\x12EVENT_THROTTLE_CFG\x10$\x12\x15\n" +
	"\x11SYSLOG_SERVER_CFG\x10%\x12\x13\n" +
	"\x0fRESET_EVENT_LOG\x10&\x12\x15\n" +
	"\x11SENSOR_DESCRIPTOR\x10(\x12\x12\n" +
	"\x0eSENSOR_READING\x10)B=Z;github.com/enshure/scte-go/xponder_go;sctexponder"

var (
	file_xponder_controller_proto_rawDescOnce sync.Once
	file_xponder_controller_proto_rawDescData []byte
)

func file_xponder_controller_proto_rawDescGZIP() []byte {
	file_xponder_controller_proto_rawDescOnce.Do(func() {
		file_xponder_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xponder_controller_proto_rawDesc), len(file_xponder_controller_proto_rawDesc)))
	})
	return file_xponder_controller_proto_rawDescData
}

var file_xponder_controller_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xponder_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_xponder_controller_proto_goTypes = []any{
	(GroupId)(0),                        // 0: scte.xponder.GroupId
	(*GroupSelector)(nil),               // 1: scte.xponder.GroupSelector
	(*ControllerGetRequest)(nil),        // 2: scte.xponder.ControllerGetRequest
	(*ControllerGetGroupResponse)(nil),  // 3: scte.xponder.ControllerGetGroupResponse
	(*ControllerGetResponse)(nil),       // 4: scte.xponder.ControllerGetResponse
	(*ControllerSetRequest)(nil),        // 5: scte.xponder.ControllerSetRequest
	(*ControllerSetResponse)(nil),       // 6: scte.xponder.ControllerSetResponse
	(common_go.ErrorTagE)(0),            // 7: scte.common.error_tag_e
	(*common_go.SystemStatus)(nil),      // 8: scte.common.SystemStatus
	(*common_go.Identification)(nil),    // 9: scte.common.Identification
	(*common_go.Vendor)(nil),            // 10: scte.common.Vendor
	(*common_go.VersionSummary)(nil),    // 11: scte.common.VersionSummary
	(*common_go.SystemCfg)(nil),         // 12: scte.common.SystemCfg
	(*common_go.Location)(nil),          // 13: scte.common.Location
	(*ResetCapabilities)(nil),           // 14: scte.xponder.ResetCapabilities
	(*ResetHistoryStatus)(nil),          // 15: scte.xponder.ResetHistoryStatus
	(*Reset)(nil),                       // 16: scte.xponder.Reset
	(*DisableAutoReboot)(nil),           // 17: scte.xponder.DisableAutoReboot
	(*EnableAutoReboot)(nil),            // 18: scte.xponder.EnableAutoReboot
	(*common_go.EventCapabilities)(nil), // 19: scte.common.EventCapabilities
	(*common_go.EventStatus)(nil),       // 20: scte.common.EventStatus
	(*common_go.EventLog)(nil),          // 21: scte.common.EventLog
	(*common_go.EventReportingCfg)(nil), // 22: scte.common.EventReportingCfg
	(*common_go.Sensors)(nil),           // 23: scte.common.Sensors
	(*common_go.SensorDescriptors)(nil), // 24: scte.common.SensorDescriptors
	(*common_go.SensorsData)(nil),       // 25: scte.common.SensorsData
	(*ManagedDevice)(nil),               // 26: scte.xponder.ManagedDevice
	(*InfoModelSupport)(nil),            // 27: scte.xponder.InfoModelSupport
	(*ResetNotification)(nil),           // 28: scte.xponder.ResetNotification
	(*common_go.Syslog)(nil),            // 29: scte.common.Syslog
	(*common_go.EventSyslogStatus)(nil), // 30: scte.common.EventSyslogStatus
	(*common_go.EventThrottleCfg)(nil),  // 31: scte.common.EventThrottleCfg
	(*common_go.SyslogServerCfg)(nil),   // 32: scte.common.SyslogServerCfg
	(*common_go.ResetEventLog)(nil),     // 33: scte.common.ResetEventLog
}
var file_xponder_controller_proto_depIdxs = []int32{
	0,  // 0: scte.xponder.GroupSelector.group_id:type_name -> scte.xponder.GroupId
	1,  // 1: scte.xponder.ControllerGetRequest.groups:type_name -> scte.xponder.GroupSelector
	0,  // 2: scte.xponder.ControllerGetGroupResponse.group_id:type_name -> scte.xponder.GroupId
	7,  // 3: scte.xponder.ControllerGetGroupResponse.error_tag:type_name -> scte.common.error_tag_e
	8,  // 4: scte.xponder.ControllerGetGroupResponse.system_status:type_name -> scte.common.SystemStatus
	9,  // 5: scte.xponder.ControllerGetGroupResponse.identification:type_name -> scte.common.Identification
	10, // 6: scte.xponder.ControllerGetGroupResponse.vendor:type_name -> scte.common.Vendor
	11, // 7: scte.xponder.ControllerGetGroupResponse.version_summary:type_name -> scte.common.VersionSummary
	12, // 8: scte.xponder.ControllerGetGroupResponse.system_cfg:type_name -> scte.common.SystemCfg
	13, // 9: scte.xponder.ControllerGetGroupResponse.location:type_name -> scte.common.Location
	14, // 10: scte.xponder.ControllerGetGroupResponse.reset_capabilities:type_name -> scte.xponder.ResetCapabilities
	15, // 11: scte.xponder.ControllerGetGroupResponse.reset_history_status:type_name -> scte.xponder.ResetHistoryStatus
	16, // 12: scte.xponder.ControllerGetGroupResponse.reset:type_name -> scte.xponder.Reset
	17, // 13: scte.xponder.ControllerGetGroupResponse.disable_auto_reboot:type_name -> scte.xponder.DisableAutoReboot
	18, // 14: scte.xponder.ControllerGetGroupResponse.enable_auto_reboot:type_name -> scte.xponder.EnableAutoReboot
	19, // 15: scte.xponder.ControllerGetGroupResponse.event_capabilities:type_name -> scte.common.EventCapabilities
	20, // 16: scte.xponder.ControllerGetGroupResponse.event_status:type_name -> scte.common.EventStatus
	21, // 17: scte.xponder.ControllerGetGroupResponse.event_log:type_name -> scte.common.EventLog
	22, // 18: scte.xponder.ControllerGetGroupResponse.event_reporting_cfg:type_name -> scte.common.EventReportingCfg
	23, // 19: scte.xponder.ControllerGetGroupResponse.sensors:type_name -> scte.common.Sensors
	24, // 20: scte.xponder.ControllerGetGroupResponse.sensor_descriptors:type_name -> scte.common.SensorDescriptors
	25, // 21: scte.xponder.ControllerGetGroupResponse.sensors_data:type_name -> scte.common.SensorsData
	26, // 22: scte.xponder.ControllerGetGroupResponse.managed_device:type_name -> scte.xponder.ManagedDevice
	27, // 23: scte.xponder.ControllerGetGroupResponse.info_model_support:type_name -> scte.xponder.InfoModelSupport
	28, // 24: scte.xponder.ControllerGetGroupResponse.reset_notification:type_name -> scte.xponder.ResetNotification
	29, // 25: scte.xponder.ControllerGetGroupResponse.syslog:type_name -> scte.common.Syslog
	30, // 26: scte.xponder.ControllerGetGroupResponse.event_syslog_status:type_name -> scte.common.EventSyslogStatus
	31, // 27: scte.xponder.ControllerGetGroupResponse.event_throttle_cfg:type_name -> scte.common.EventThrottleCfg
	32, // 28: scte.xponder.ControllerGetGroupResponse.syslog_server_cfg:type_name -> scte.common.SyslogServerCfg
	33, // 29: scte.xponder.ControllerGetGroupResponse.reset_event_log:type_name -> scte.common.ResetEventLog
	3,  // 30: scte.xponder.ControllerGetResponse.groups:type_name -> scte.xponder.ControllerGetGroupResponse
	0,  // 31: scte.xponder.ControllerSetRequest.group_id:type_name -> scte.xponder.GroupId
	12, // 32: scte.xponder.ControllerSetRequest.system_cfg:type_name -> scte.common.SystemCfg
	13, // 33: scte.xponder.ControllerSetRequest.location:type_name -> scte.common.Location
	16, // 34: scte.xponder.ControllerSetRequest.reset:type_name -> scte.xponder.Reset
	17, // 35: scte.xponder.ControllerSetRequest.disable_auto_reboot:type_name -> scte.xponder.DisableAutoReboot
	18, // 36: scte.xponder.ControllerSetRequest.enable_auto_reboot:type_name -> scte.xponder.EnableAutoReboot
	22, // 37: scte.xponder.ControllerSetRequest.event_reporting_cfg:type_name -> scte.common.EventReportingCfg
	31, // 38: scte.xponder.ControllerSetRequest.event_throttle_cfg:type_name -> scte.common.EventThrottleCfg
	32, // 39: scte.xponder.ControllerSetRequest.syslog_server_cfg:type_name -> scte.common.SyslogServerCfg
	33, // 40: scte.xponder.ControllerSetRequest.reset_event_log:type_name -> scte.common.ResetEventLog
	0,  // 41: scte.xponder.ControllerSetResponse.group_id:type_name -> scte.xponder.GroupId
	7,  // 42: scte.xponder.ControllerSetResponse.error_tag:type_name -> scte.common.error_tag_e
	12, // 43: scte.xponder.ControllerSetResponse.system_cfg:type_name -> scte.common.SystemCfg
	13, // 44: scte.xponder.ControllerSetResponse.location:type_name -> scte.common.Location
	16, // 45: scte.xponder.ControllerSetResponse.reset:type_name -> scte.xponder.Reset
	17, // 46: scte.xponder.ControllerSetResponse.disable_auto_reboot:type_name -> scte.xponder.DisableAutoReboot
	18, // 47: scte.xponder.ControllerSetResponse.enable_auto_reboot:type_name -> scte.xponder.EnableAutoReboot
	22, // 48: scte.xponder.ControllerSetResponse.event_reporting_cfg:type_name -> scte.common.EventReportingCfg
	31, // 49: scte.xponder.ControllerSetResponse.event_throttle_cfg:type_name -> scte.common.EventThrottleCfg
	32, // 50: scte.xponder.ControllerSetResponse.syslog_server_cfg:type_name -> scte.common.SyslogServerCfg
	33, // 51: scte.xponder.ControllerSetResponse.reset_event_log:type_name -> scte.common.ResetEventLog
	52, // [52:52] is the sub-list for method output_type
	52, // [52:52] is the sub-list for method input_type
	52, // [52:52] is the sub-list for extension type_name
	52, // [52:52] is the sub-list for extension extendee
	0,  // [0:52] is the sub-list for field type_name
}

func init() { file_xponder_controller_proto_init() }
func file_xponder_controller_proto_init() {
	if File_xponder_controller_proto != nil {
		return
	}
	file_xponder_common_proto_init()
	file_xponder_system_proto_init()
	file_xponder_reset_proto_init()
	file_xponder_events_proto_init()
	file_xponder_controller_proto_msgTypes[2].OneofWrappers = []any{
		(*ControllerGetGroupResponse_SystemStatus)(nil),
		(*ControllerGetGroupResponse_Identification)(nil),
		(*ControllerGetGroupResponse_Vendor)(nil),
		(*ControllerGetGroupResponse_VersionSummary)(nil),
		(*ControllerGetGroupResponse_SystemCfg)(nil),
		(*ControllerGetGroupResponse_Location)(nil),
		(*ControllerGetGroupResponse_ResetCapabilities)(nil),
		(*ControllerGetGroupResponse_ResetHistoryStatus)(nil),
		(*ControllerGetGroupResponse_Reset_)(nil),
		(*ControllerGetGroupResponse_DisableAutoReboot)(nil),
		(*ControllerGetGroupResponse_EnableAutoReboot)(nil),
		(*ControllerGetGroupResponse_EventCapabilities)(nil),
		(*ControllerGetGroupResponse_EventStatus)(nil),
		(*ControllerGetGroupResponse_EventLog)(nil),
		(*ControllerGetGroupResponse_EventReportingCfg)(nil),
		(*ControllerGetGroupResponse_Sensors)(nil),
		(*ControllerGetGroupResponse_SensorDescriptors)(nil),
		(*ControllerGetGroupResponse_SensorsData)(nil),
		(*ControllerGetGroupResponse_ManagedDevice)(nil),
		(*ControllerGetGroupResponse_InfoModelSupport)(nil),
		(*ControllerGetGroupResponse_ResetNotification)(nil),
		(*ControllerGetGroupResponse_Syslog)(nil),
		(*ControllerGetGroupResponse_EventSyslogStatus)(nil),
		(*ControllerGetGroupResponse_EventThrottleCfg)(nil),
		(*ControllerGetGroupResponse_SyslogServerCfg)(nil),
		(*ControllerGetGroupResponse_ResetEventLog)(nil),
	}
	file_xponder_controller_proto_msgTypes[4].OneofWrappers = []any{
		(*ControllerSetRequest_SystemCfg)(nil),
		(*ControllerSetRequest_Location)(nil),
		(*ControllerSetRequest_Reset_)(nil),
		(*ControllerSetRequest_DisableAutoReboot)(nil),
		(*ControllerSetRequest_EnableAutoReboot)(nil),
		(*ControllerSetRequest_EventReportingCfg)(nil),
		(*ControllerSetRequest_EventThrottleCfg)(nil),
		(*ControllerSetRequest_SyslogServerCfg)(nil),
		(*ControllerSetRequest_ResetEventLog)(nil),
	}
	file_xponder_controller_proto_msgTypes[5].OneofWrappers = []any{
		(*ControllerSetResponse_SystemCfg)(nil),
		(*ControllerSetResponse_Location)(nil),
		(*ControllerSetResponse_Reset_)(nil),
		(*ControllerSetResponse_DisableAutoReboot)(nil),
		(*ControllerSetResponse_EnableAutoReboot)(nil),
		(*ControllerSetResponse_EventReportingCfg)(nil),
		(*ControllerSetResponse_EventThrottleCfg)(nil),
		(*ControllerSetResponse_SyslogServerCfg)(nil),
		(*ControllerSetResponse_ResetEventLog)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xponder_controller_proto_rawDesc), len(file_xponder_controller_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xponder_controller_proto_goTypes,
		DependencyIndexes: file_xponder_controller_proto_depIdxs,
		EnumInfos:         file_xponder_controller_proto_enumTypes,
		MessageInfos:      file_xponder_controller_proto_msgTypes,
	}.Build()
	File_xponder_controller_proto = out.File
	file_xponder_controller_proto_goTypes = nil
	file_xponder_controller_proto_depIdxs = nil
}
