// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: xponder/events.proto

package sctexponder

import (
	common_go "github.com/enshure/scte-go/common_go"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Symbols defined in public import of common/event_common.proto.

type EventPriorityE = common_go.EventPriorityE

const EventPriorityE_EVENT_PRIORITY_EMERGENCY = common_go.EventPriorityE_EVENT_PRIORITY_EMERGENCY
const EventPriorityE_EVENT_PRIORITY_ALERT = common_go.EventPriorityE_EVENT_PRIORITY_ALERT
const EventPriorityE_EVENT_PRIORITY_CRITICAL = common_go.EventPriorityE_EVENT_PRIORITY_CRITICAL
const EventPriorityE_EVENT_PRIORITY_ERROR = common_go.EventPriorityE_EVENT_PRIORITY_ERROR
const EventPriorityE_EVENT_PRIORITY_WARNING = common_go.EventPriorityE_EVENT_PRIORITY_WARNING
const EventPriorityE_EVENT_PRIORITY_NOTICE = common_go.EventPriorityE_EVENT_PRIORITY_NOTICE
const EventPriorityE_EVENT_PRIORITY_INFO = common_go.EventPriorityE_EVENT_PRIORITY_INFO
const EventPriorityE_EVENT_PRIORITY_DEBUG = common_go.EventPriorityE_EVENT_PRIORITY_DEBUG

var EventPriorityE_name = common_go.EventPriorityE_name
var EventPriorityE_value = common_go.EventPriorityE_value

type EventTransitionE = common_go.EventTransitionE

const EventTransitionE_EVENT_TRANSITION_ASSERT = common_go.EventTransitionE_EVENT_TRANSITION_ASSERT
const EventTransitionE_EVENT_TRANSITION_CLEAR = common_go.EventTransitionE_EVENT_TRANSITION_CLEAR
const EventTransitionE_EVENT_TRANSITION_NOTIFICATION_ONLY = common_go.EventTransitionE_EVENT_TRANSITION_NOTIFICATION_ONLY

var EventTransitionE_name = common_go.EventTransitionE_name
var EventTransitionE_value = common_go.EventTransitionE_value

type EventDefinition = common_go.EventDefinition
type EventCapabilities = common_go.EventCapabilities
type EventStatus = common_go.EventStatus
type Event = common_go.Event
type EventLog = common_go.EventLog
type EventNotification = common_go.EventNotification
type EventThrottleCfg = common_go.EventThrottleCfg

const Default_EventThrottleCfg_Write = common_go.Default_EventThrottleCfg_Write

type EventReportingCfg = common_go.EventReportingCfg

const Default_EventReportingCfg_Reporting = common_go.Default_EventReportingCfg_Reporting
const Default_EventReportingCfg_Write = common_go.Default_EventReportingCfg_Write

var File_xponder_events_proto protoreflect.FileDescriptor

const file_xponder_events_proto_rawDesc = "" +
	"\n" +
	"\x14xponder/events.proto\x12\fscte.xponder\x1a\x19common/event_common.protoB3Z1github.com/enshure/scte-go/xponder_go;sctexponderP\x00"

var file_xponder_events_proto_goTypes = []any{}
var file_xponder_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_xponder_events_proto_init() }
func file_xponder_events_proto_init() {
	if File_xponder_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xponder_events_proto_rawDesc), len(file_xponder_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xponder_events_proto_goTypes,
		DependencyIndexes: file_xponder_events_proto_depIdxs,
	}.Build()
	File_xponder_events_proto = out.File
	file_xponder_events_proto_goTypes = nil
	file_xponder_events_proto_depIdxs = nil
}
