// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: xponder/system.proto

package sctexponder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoModelSupport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Index *uint32                `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Beid  []byte                 `protobuf:"bytes,2,opt,name=beid" json:"beid,omitempty"`
	Name  *string                `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	// Following information_model_id values are supported:
	// - transponder - "opt.scte.transponder.v1"
	// - amplifier - "opt.scte.amp.v1"
	InformationModelId *string `protobuf:"bytes,4,opt,name=information_model_id,json=informationModelId" json:"information_model_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InfoModelSupport) Reset() {
	*x = InfoModelSupport{}
	mi := &file_xponder_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoModelSupport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoModelSupport) ProtoMessage() {}

func (x *InfoModelSupport) ProtoReflect() protoreflect.Message {
	mi := &file_xponder_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoModelSupport.ProtoReflect.Descriptor instead.
func (*InfoModelSupport) Descriptor() ([]byte, []int) {
	return file_xponder_system_proto_rawDescGZIP(), []int{0}
}

func (x *InfoModelSupport) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *InfoModelSupport) GetBeid() []byte {
	if x != nil {
		return x.Beid
	}
	return nil
}

func (x *InfoModelSupport) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *InfoModelSupport) GetInformationModelId() string {
	if x != nil && x.InformationModelId != nil {
		return *x.InformationModelId
	}
	return ""
}

type ManagedDevices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoModels    []*InfoModelSupport    `protobuf:"bytes,1,rep,name=info_models,json=infoModels" json:"info_models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagedDevices) Reset() {
	*x = ManagedDevices{}
	mi := &file_xponder_system_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedDevices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedDevices) ProtoMessage() {}

func (x *ManagedDevices) ProtoReflect() protoreflect.Message {
	mi := &file_xponder_system_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedDevices.ProtoReflect.Descriptor instead.
func (*ManagedDevices) Descriptor() ([]byte, []int) {
	return file_xponder_system_proto_rawDescGZIP(), []int{1}
}

func (x *ManagedDevices) GetInfoModels() []*InfoModelSupport {
	if x != nil {
		return x.InfoModels
	}
	return nil
}

var File_xponder_system_proto protoreflect.FileDescriptor

const file_xponder_system_proto_rawDesc = "" +
	"\n" +
	"\x14xponder/system.proto\x12\fscte.xponder\"\x82\x01\n" +
	"\x10InfoModelSupport\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04beid\x18\x02 \x01(\fR\x04beid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x120\n" +
	"\x14information_model_id\x18\x04 \x01(\tR\x12informationModelId\"Q\n" +
	"\x0eManagedDevices\x12?\n" +
	"\vinfo_models\x18\x01 \x03(\v2\x1e.scte.xponder.InfoModelSupportR\n" +
	"infoModelsBG\n" +
	"\x10org.scte.xponderP\x01Z1github.com/enshure/scte-go/xponder_go;sctexponder"

var (
	file_xponder_system_proto_rawDescOnce sync.Once
	file_xponder_system_proto_rawDescData []byte
)

func file_xponder_system_proto_rawDescGZIP() []byte {
	file_xponder_system_proto_rawDescOnce.Do(func() {
		file_xponder_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xponder_system_proto_rawDesc), len(file_xponder_system_proto_rawDesc)))
	})
	return file_xponder_system_proto_rawDescData
}

var file_xponder_system_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_xponder_system_proto_goTypes = []any{
	(*InfoModelSupport)(nil), // 0: scte.xponder.InfoModelSupport
	(*ManagedDevices)(nil),   // 1: scte.xponder.ManagedDevices
}
var file_xponder_system_proto_depIdxs = []int32{
	0, // 0: scte.xponder.ManagedDevices.info_models:type_name -> scte.xponder.InfoModelSupport
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_xponder_system_proto_init() }
func file_xponder_system_proto_init() {
	if File_xponder_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xponder_system_proto_rawDesc), len(file_xponder_system_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_xponder_system_proto_goTypes,
		DependencyIndexes: file_xponder_system_proto_depIdxs,
		MessageInfos:      file_xponder_system_proto_msgTypes,
	}.Build()
	File_xponder_system_proto = out.File
	file_xponder_system_proto_goTypes = nil
	file_xponder_system_proto_depIdxs = nil
}
