// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: common/api.proto

package sctecommon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope-level response status for a processed Msg.
type ResponseStatus int32

const (
	ResponseStatus_RESPONSE_STATUS_SUCCESS ResponseStatus = 0
	ResponseStatus_RESPONSE_STATUS_FAILED  ResponseStatus = 1
)

// Enum value maps for ResponseStatus.
var (
	ResponseStatus_name = map[int32]string{
		0: "RESPONSE_STATUS_SUCCESS",
		1: "RESPONSE_STATUS_FAILED",
	}
	ResponseStatus_value = map[string]int32{
		"RESPONSE_STATUS_SUCCESS": 0,
		"RESPONSE_STATUS_FAILED":  1,
	}
)

func (x ResponseStatus) Enum() *ResponseStatus {
	p := new(ResponseStatus)
	*p = x
	return p
}

func (x ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_api_proto_enumTypes[0].Descriptor()
}

func (ResponseStatus) Type() protoreflect.EnumType {
	return &file_common_api_proto_enumTypes[0]
}

func (x ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ResponseStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ResponseStatus(num)
	return nil
}

// Deprecated: Use ResponseStatus.Descriptor instead.
func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_api_proto_rawDescGZIP(), []int{0}
}

// Envelope-level result returned with a Msg response.
type Result struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall success or failure of processing the Msg envelope.
	Status *ResponseStatus `protobuf:"varint,1,req,name=status,enum=scte.common.ResponseStatus" json:"status,omitempty"`
	// Optional implementation-specific status or error code.
	Code *uint32 `protobuf:"varint,2,opt,name=code" json:"code,omitempty"`
	// Optional human-readable status or error detail.
	Message       *string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_common_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_common_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_common_api_proto_rawDescGZIP(), []int{0}
}

func (x *Result) GetStatus() ResponseStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ResponseStatus_RESPONSE_STATUS_SUCCESS
}

func (x *Result) GetCode() uint32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *Result) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_common_api_proto protoreflect.FileDescriptor

const file_common_api_proto_rawDesc = "" +
	"\n" +
	"\x10common/api.proto\x12\vscte.common\"l\n" +
	"\x06Result\x124\n" +
	"\x06status\x18\x01 \x02(\x0e2\x1c.scte.common.response_statusR\x06status\x12\x12\n" +
	"\x04code\x18\x02 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage*J\n" +
	"\x0fresponse_status\x12\x1b\n" +
	"\x17RESPONSE_STATUS_SUCCESS\x10\x00\x12\x1a\n" +
	"\x16RESPONSE_STATUS_FAILED\x10\x01BD\n" +
	"\x0forg.scte.commonP\x01Z/github.com/enshure/scte-go/common_go;sctecommon"

var (
	file_common_api_proto_rawDescOnce sync.Once
	file_common_api_proto_rawDescData []byte
)

func file_common_api_proto_rawDescGZIP() []byte {
	file_common_api_proto_rawDescOnce.Do(func() {
		file_common_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_api_proto_rawDesc), len(file_common_api_proto_rawDesc)))
	})
	return file_common_api_proto_rawDescData
}

var file_common_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_api_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_api_proto_goTypes = []any{
	(ResponseStatus)(0), // 0: scte.common.response_status
	(*Result)(nil),      // 1: scte.common.Result
}
var file_common_api_proto_depIdxs = []int32{
	0, // 0: scte.common.Result.status:type_name -> scte.common.response_status
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_api_proto_init() }
func file_common_api_proto_init() {
	if File_common_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_api_proto_rawDesc), len(file_common_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_api_proto_goTypes,
		DependencyIndexes: file_common_api_proto_depIdxs,
		EnumInfos:         file_common_api_proto_enumTypes,
		MessageInfos:      file_common_api_proto_msgTypes,
	}.Build()
	File_common_api_proto = out.File
	file_common_api_proto_goTypes = nil
	file_common_api_proto_depIdxs = nil
}
