// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: common/device_common.proto

package sctecommon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceLocationTypeE int32

const (
	DeviceLocationTypeE_UNKNOWN           DeviceLocationTypeE = 0
	DeviceLocationTypeE_AERIAL            DeviceLocationTypeE = 1
	DeviceLocationTypeE_UNDERGROUND       DeviceLocationTypeE = 2
	DeviceLocationTypeE_INDOOR_COMMERCIAL DeviceLocationTypeE = 3
	DeviceLocationTypeE_RESIDENTIAL       DeviceLocationTypeE = 4
	DeviceLocationTypeE_OTHER             DeviceLocationTypeE = 10
)

// Enum value maps for DeviceLocationTypeE.
var (
	DeviceLocationTypeE_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "AERIAL",
		2:  "UNDERGROUND",
		3:  "INDOOR_COMMERCIAL",
		4:  "RESIDENTIAL",
		10: "OTHER",
	}
	DeviceLocationTypeE_value = map[string]int32{
		"UNKNOWN":           0,
		"AERIAL":            1,
		"UNDERGROUND":       2,
		"INDOOR_COMMERCIAL": 3,
		"RESIDENTIAL":       4,
		"OTHER":             10,
	}
)

func (x DeviceLocationTypeE) Enum() *DeviceLocationTypeE {
	p := new(DeviceLocationTypeE)
	*p = x
	return p
}

func (x DeviceLocationTypeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceLocationTypeE) Descriptor() protoreflect.EnumDescriptor {
	return file_common_device_common_proto_enumTypes[0].Descriptor()
}

func (DeviceLocationTypeE) Type() protoreflect.EnumType {
	return &file_common_device_common_proto_enumTypes[0]
}

func (x DeviceLocationTypeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DeviceLocationTypeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DeviceLocationTypeE(num)
	return nil
}

// Deprecated: Use DeviceLocationTypeE.Descriptor instead.
func (DeviceLocationTypeE) EnumDescriptor() ([]byte, []int) {
	return file_common_device_common_proto_rawDescGZIP(), []int{0}
}

type UsDeviceTypeE int32

const (
	UsDeviceTypeE_US_AMPLIFIER UsDeviceTypeE = 0
	UsDeviceTypeE_US_NODE      UsDeviceTypeE = 1
	UsDeviceTypeE_US_OTHER     UsDeviceTypeE = 2
)

// Enum value maps for UsDeviceTypeE.
var (
	UsDeviceTypeE_name = map[int32]string{
		0: "US_AMPLIFIER",
		1: "US_NODE",
		2: "US_OTHER",
	}
	UsDeviceTypeE_value = map[string]int32{
		"US_AMPLIFIER": 0,
		"US_NODE":      1,
		"US_OTHER":     2,
	}
)

func (x UsDeviceTypeE) Enum() *UsDeviceTypeE {
	p := new(UsDeviceTypeE)
	*p = x
	return p
}

func (x UsDeviceTypeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UsDeviceTypeE) Descriptor() protoreflect.EnumDescriptor {
	return file_common_device_common_proto_enumTypes[1].Descriptor()
}

func (UsDeviceTypeE) Type() protoreflect.EnumType {
	return &file_common_device_common_proto_enumTypes[1]
}

func (x UsDeviceTypeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *UsDeviceTypeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = UsDeviceTypeE(num)
	return nil
}

// Deprecated: Use UsDeviceTypeE.Descriptor instead.
func (UsDeviceTypeE) EnumDescriptor() ([]byte, []int) {
	return file_common_device_common_proto_rawDescGZIP(), []int{1}
}

type Identification struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ModelNumber       *string                `protobuf:"bytes,1,opt,name=model_number,json=modelNumber" json:"model_number,omitempty"`
	SerialNumber      *string                `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber" json:"serial_number,omitempty"`
	ProductId         *uint32                `protobuf:"varint,3,opt,name=product_id,json=productId" json:"product_id,omitempty"`
	HwVersion         *string                `protobuf:"bytes,4,opt,name=hw_version,json=hwVersion" json:"hw_version,omitempty"`
	ManufacturingDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=manufacturing_date,json=manufacturingDate" json:"manufacturing_date,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Identification) Reset() {
	*x = Identification{}
	mi := &file_common_device_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identification) ProtoMessage() {}

func (x *Identification) ProtoReflect() protoreflect.Message {
	mi := &file_common_device_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identification.ProtoReflect.Descriptor instead.
func (*Identification) Descriptor() ([]byte, []int) {
	return file_common_device_common_proto_rawDescGZIP(), []int{0}
}

func (x *Identification) GetModelNumber() string {
	if x != nil && x.ModelNumber != nil {
		return *x.ModelNumber
	}
	return ""
}

func (x *Identification) GetSerialNumber() string {
	if x != nil && x.SerialNumber != nil {
		return *x.SerialNumber
	}
	return ""
}

func (x *Identification) GetProductId() uint32 {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return 0
}

func (x *Identification) GetHwVersion() string {
	if x != nil && x.HwVersion != nil {
		return *x.HwVersion
	}
	return ""
}

func (x *Identification) GetManufacturingDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ManufacturingDate
	}
	return nil
}

type Vendor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Oui           []byte                 `protobuf:"bytes,2,opt,name=oui" json:"oui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vendor) Reset() {
	*x = Vendor{}
	mi := &file_common_device_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vendor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vendor) ProtoMessage() {}

func (x *Vendor) ProtoReflect() protoreflect.Message {
	mi := &file_common_device_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vendor.ProtoReflect.Descriptor instead.
func (*Vendor) Descriptor() ([]byte, []int) {
	return file_common_device_common_proto_rawDescGZIP(), []int{1}
}

func (x *Vendor) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Vendor) GetOui() []byte {
	if x != nil {
		return x.Oui
	}
	return nil
}

type UpstreamDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type          *UsDeviceTypeE         `protobuf:"varint,2,opt,name=type,enum=scte.common.UsDeviceTypeE" json:"type,omitempty"`
	UsDevicePort  *uint32                `protobuf:"varint,3,opt,name=us_device_port,json=usDevicePort" json:"us_device_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamDevice) Reset() {
	*x = UpstreamDevice{}
	mi := &file_common_device_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamDevice) ProtoMessage() {}

func (x *UpstreamDevice) ProtoReflect() protoreflect.Message {
	mi := &file_common_device_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamDevice.ProtoReflect.Descriptor instead.
func (*UpstreamDevice) Descriptor() ([]byte, []int) {
	return file_common_device_common_proto_rawDescGZIP(), []int{2}
}

func (x *UpstreamDevice) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *UpstreamDevice) GetType() UsDeviceTypeE {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return UsDeviceTypeE_US_AMPLIFIER
}

func (x *UpstreamDevice) GetUsDevicePort() uint32 {
	if x != nil && x.UsDevicePort != nil {
		return *x.UsDevicePort
	}
	return 0
}

type Location struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Description    *string                `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Latitude       *float64               `protobuf:"fixed64,2,opt,name=latitude" json:"latitude,omitempty"`
	Longitude      *float64               `protobuf:"fixed64,3,opt,name=longitude" json:"longitude,omitempty"`
	DeviceLocation *DeviceLocationTypeE   `protobuf:"varint,4,opt,name=device_location,json=deviceLocation,enum=scte.common.DeviceLocationTypeE" json:"device_location,omitempty"`
	UsDevice       *UpstreamDevice        `protobuf:"bytes,5,opt,name=us_device,json=usDevice" json:"us_device,omitempty"` //This should be configured along with location.  It will be used by HRDC for topology purposes.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_common_device_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_common_device_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_common_device_common_proto_rawDescGZIP(), []int{3}
}

func (x *Location) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Location) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *Location) GetDeviceLocation() DeviceLocationTypeE {
	if x != nil && x.DeviceLocation != nil {
		return *x.DeviceLocation
	}
	return DeviceLocationTypeE_UNKNOWN
}

func (x *Location) GetUsDevice() *UpstreamDevice {
	if x != nil {
		return x.UsDevice
	}
	return nil
}

var File_common_device_common_proto protoreflect.FileDescriptor

const file_common_device_common_proto_rawDesc = "" +
	"\n" +
	"\x1acommon/device_common.proto\x12\vscte.common\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe1\x01\n" +
	"\x0eIdentification\x12!\n" +
	"\fmodel_number\x18\x01 \x01(\tR\vmodelNumber\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\rR\tproductId\x12\x1d\n" +
	"\n" +
	"hw_version\x18\x04 \x01(\tR\thwVersion\x12I\n" +
	"\x12manufacturing_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x11manufacturingDate\".\n" +
	"\x06Vendor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03oui\x18\x02 \x01(\fR\x03oui\"y\n" +
	"\x0eUpstreamDevice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.scte.common.us_device_type_eR\x04type\x12$\n" +
	"\x0eus_device_port\x18\x03 \x01(\rR\fusDevicePort\"\xee\x01\n" +
	"\bLocation\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\x12L\n" +
	"\x0fdevice_location\x18\x04 \x01(\x0e2#.scte.common.device_location_type_eR\x0edeviceLocation\x128\n" +
	"\tus_device\x18\x05 \x01(\v2\x1b.scte.common.UpstreamDeviceR\busDevice*u\n" +
	"\x16device_location_type_e\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06AERIAL\x10\x01\x12\x0f\n" +
	"\vUNDERGROUND\x10\x02\x12\x15\n" +
	"\x11INDOOR_COMMERCIAL\x10\x03\x12\x0f\n" +
	"\vRESIDENTIAL\x10\x04\x12\t\n" +
	"\x05OTHER\x10\n" +
	"*?\n" +
	"\x10us_device_type_e\x12\x10\n" +
	"\fUS_AMPLIFIER\x10\x00\x12\v\n" +
	"\aUS_NODE\x10\x01\x12\f\n" +
	"\bUS_OTHER\x10\x02BD\n" +
	"\x0forg.scte.commonP\x01Z/github.com/enshure/scte-go/common_go;sctecommon"

var (
	file_common_device_common_proto_rawDescOnce sync.Once
	file_common_device_common_proto_rawDescData []byte
)

func file_common_device_common_proto_rawDescGZIP() []byte {
	file_common_device_common_proto_rawDescOnce.Do(func() {
		file_common_device_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_device_common_proto_rawDesc), len(file_common_device_common_proto_rawDesc)))
	})
	return file_common_device_common_proto_rawDescData
}

var file_common_device_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_device_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_device_common_proto_goTypes = []any{
	(DeviceLocationTypeE)(0),      // 0: scte.common.device_location_type_e
	(UsDeviceTypeE)(0),            // 1: scte.common.us_device_type_e
	(*Identification)(nil),        // 2: scte.common.Identification
	(*Vendor)(nil),                // 3: scte.common.Vendor
	(*UpstreamDevice)(nil),        // 4: scte.common.UpstreamDevice
	(*Location)(nil),              // 5: scte.common.Location
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_common_device_common_proto_depIdxs = []int32{
	6, // 0: scte.common.Identification.manufacturing_date:type_name -> google.protobuf.Timestamp
	1, // 1: scte.common.UpstreamDevice.type:type_name -> scte.common.us_device_type_e
	0, // 2: scte.common.Location.device_location:type_name -> scte.common.device_location_type_e
	4, // 3: scte.common.Location.us_device:type_name -> scte.common.UpstreamDevice
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_common_device_common_proto_init() }
func file_common_device_common_proto_init() {
	if File_common_device_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_device_common_proto_rawDesc), len(file_common_device_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_device_common_proto_goTypes,
		DependencyIndexes: file_common_device_common_proto_depIdxs,
		EnumInfos:         file_common_device_common_proto_enumTypes,
		MessageInfos:      file_common_device_common_proto_msgTypes,
	}.Build()
	File_common_device_common_proto = out.File
	file_common_device_common_proto_goTypes = nil
	file_common_device_common_proto_depIdxs = nil
}
