// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: common/event_common.proto

package sctecommon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventPriorityE int32

const (
	EventPriorityE_EVENT_PRIORITY_EMERGENCY EventPriorityE = 1
	EventPriorityE_EVENT_PRIORITY_ALERT     EventPriorityE = 2
	EventPriorityE_EVENT_PRIORITY_CRITICAL  EventPriorityE = 3
	EventPriorityE_EVENT_PRIORITY_ERROR     EventPriorityE = 4
	EventPriorityE_EVENT_PRIORITY_WARNING   EventPriorityE = 5
	EventPriorityE_EVENT_PRIORITY_NOTICE    EventPriorityE = 6
	EventPriorityE_EVENT_PRIORITY_INFO      EventPriorityE = 7
	EventPriorityE_EVENT_PRIORITY_DEBUG     EventPriorityE = 8
)

// Enum value maps for EventPriorityE.
var (
	EventPriorityE_name = map[int32]string{
		1: "EVENT_PRIORITY_EMERGENCY",
		2: "EVENT_PRIORITY_ALERT",
		3: "EVENT_PRIORITY_CRITICAL",
		4: "EVENT_PRIORITY_ERROR",
		5: "EVENT_PRIORITY_WARNING",
		6: "EVENT_PRIORITY_NOTICE",
		7: "EVENT_PRIORITY_INFO",
		8: "EVENT_PRIORITY_DEBUG",
	}
	EventPriorityE_value = map[string]int32{
		"EVENT_PRIORITY_EMERGENCY": 1,
		"EVENT_PRIORITY_ALERT":     2,
		"EVENT_PRIORITY_CRITICAL":  3,
		"EVENT_PRIORITY_ERROR":     4,
		"EVENT_PRIORITY_WARNING":   5,
		"EVENT_PRIORITY_NOTICE":    6,
		"EVENT_PRIORITY_INFO":      7,
		"EVENT_PRIORITY_DEBUG":     8,
	}
)

func (x EventPriorityE) Enum() *EventPriorityE {
	p := new(EventPriorityE)
	*p = x
	return p
}

func (x EventPriorityE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventPriorityE) Descriptor() protoreflect.EnumDescriptor {
	return file_common_event_common_proto_enumTypes[0].Descriptor()
}

func (EventPriorityE) Type() protoreflect.EnumType {
	return &file_common_event_common_proto_enumTypes[0]
}

func (x EventPriorityE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EventPriorityE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EventPriorityE(num)
	return nil
}

// Deprecated: Use EventPriorityE.Descriptor instead.
func (EventPriorityE) EnumDescriptor() ([]byte, []int) {
	return file_common_event_common_proto_rawDescGZIP(), []int{0}
}

type EventTransitionE int32

const (
	EventTransitionE_EVENT_TRANSITION_ASSERT            EventTransitionE = 1
	EventTransitionE_EVENT_TRANSITION_CLEAR             EventTransitionE = 2
	EventTransitionE_EVENT_TRANSITION_NOTIFICATION_ONLY EventTransitionE = 3
)

// Enum value maps for EventTransitionE.
var (
	EventTransitionE_name = map[int32]string{
		1: "EVENT_TRANSITION_ASSERT",
		2: "EVENT_TRANSITION_CLEAR",
		3: "EVENT_TRANSITION_NOTIFICATION_ONLY",
	}
	EventTransitionE_value = map[string]int32{
		"EVENT_TRANSITION_ASSERT":            1,
		"EVENT_TRANSITION_CLEAR":             2,
		"EVENT_TRANSITION_NOTIFICATION_ONLY": 3,
	}
)

func (x EventTransitionE) Enum() *EventTransitionE {
	p := new(EventTransitionE)
	*p = x
	return p
}

func (x EventTransitionE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventTransitionE) Descriptor() protoreflect.EnumDescriptor {
	return file_common_event_common_proto_enumTypes[1].Descriptor()
}

func (EventTransitionE) Type() protoreflect.EnumType {
	return &file_common_event_common_proto_enumTypes[1]
}

func (x EventTransitionE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EventTransitionE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EventTransitionE(num)
	return nil
}

// Deprecated: Use EventTransitionE.Descriptor instead.
func (EventTransitionE) EnumDescriptor() ([]byte, []int) {
	return file_common_event_common_proto_rawDescGZIP(), []int{1}
}

type EventDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       *uint32                `protobuf:"varint,1,opt,name=event_id,json=eventId" json:"event_id,omitempty"`             // The unique identifier for the event
	BitPosition   []uint32               `protobuf:"varint,2,rep,name=bit_position,json=bitPosition" json:"bit_position,omitempty"` // The bit positions in the active_event_bitmasks when the EventNotification is generated
	Description   *string                `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`                     // A description of the event
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventDefinition) Reset() {
	*x = EventDefinition{}
	mi := &file_common_event_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventDefinition) ProtoMessage() {}

func (x *EventDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_common_event_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventDefinition.ProtoReflect.Descriptor instead.
func (*EventDefinition) Descriptor() ([]byte, []int) {
	return file_common_event_common_proto_rawDescGZIP(), []int{0}
}

func (x *EventDefinition) GetEventId() uint32 {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return 0
}

func (x *EventDefinition) GetBitPosition() []uint32 {
	if x != nil {
		return x.BitPosition
	}
	return nil
}

func (x *EventDefinition) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type EventCapabilities struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LocalEventLogMaxSize *uint32                `protobuf:"varint,1,opt,name=local_event_log_max_size,json=localEventLogMaxSize" json:"local_event_log_max_size,omitempty"`
	EventDefinitions     []*EventDefinition     `protobuf:"bytes,2,rep,name=event_definitions,json=eventDefinitions" json:"event_definitions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EventCapabilities) Reset() {
	*x = EventCapabilities{}
	mi := &file_common_event_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventCapabilities) ProtoMessage() {}

func (x *EventCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_common_event_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventCapabilities.ProtoReflect.Descriptor instead.
func (*EventCapabilities) Descriptor() ([]byte, []int) {
	return file_common_event_common_proto_rawDescGZIP(), []int{1}
}

func (x *EventCapabilities) GetLocalEventLogMaxSize() uint32 {
	if x != nil && x.LocalEventLogMaxSize != nil {
		return *x.LocalEventLogMaxSize
	}
	return 0
}

func (x *EventCapabilities) GetEventDefinitions() []*EventDefinition {
	if x != nil {
		return x.EventDefinitions
	}
	return nil
}

type EventStatus struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ThrottleThresholdExceeded *bool                  `protobuf:"varint,1,opt,name=throttle_threshold_exceeded,json=throttleThresholdExceeded" json:"throttle_threshold_exceeded,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *EventStatus) Reset() {
	*x = EventStatus{}
	mi := &file_common_event_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStatus) ProtoMessage() {}

func (x *EventStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_event_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStatus.ProtoReflect.Descriptor instead.
func (*EventStatus) Descriptor() ([]byte, []int) {
	return file_common_event_common_proto_rawDescGZIP(), []int{2}
}

func (x *EventStatus) GetThrottleThresholdExceeded() bool {
	if x != nil && x.ThrottleThresholdExceeded != nil {
		return *x.ThrottleThresholdExceeded
	}
	return false
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       *uint32                `protobuf:"varint,1,opt,name=event_id,json=eventId" json:"event_id,omitempty"`
	FirstTime     *string                `protobuf:"bytes,2,opt,name=first_time,json=firstTime" json:"first_time,omitempty"`
	LastTime      *string                `protobuf:"bytes,3,opt,name=last_time,json=lastTime" json:"last_time,omitempty"`
	Count         *uint32                `protobuf:"varint,4,opt,name=count" json:"count,omitempty"`
	Level         *EventPriorityE        `protobuf:"varint,5,opt,name=level,enum=scte.common.EventPriorityE" json:"level,omitempty"`
	Text          *string                `protobuf:"bytes,6,opt,name=text" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_common_event_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_common_event_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_common_event_common_proto_rawDescGZIP(), []int{3}
}

func (x *Event) GetEventId() uint32 {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return 0
}

func (x *Event) GetFirstTime() string {
	if x != nil && x.FirstTime != nil {
		return *x.FirstTime
	}
	return ""
}

func (x *Event) GetLastTime() string {
	if x != nil && x.LastTime != nil {
		return *x.LastTime
	}
	return ""
}

func (x *Event) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *Event) GetLevel() EventPriorityE {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return EventPriorityE_EVENT_PRIORITY_EMERGENCY
}

func (x *Event) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

type EventLog struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Events        []*Event                `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
	Page          *ResponsePaginationInfo `protobuf:"bytes,2,opt,name=page" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLog) Reset() {
	*x = EventLog{}
	mi := &file_common_event_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLog) ProtoMessage() {}

func (x *EventLog) ProtoReflect() protoreflect.Message {
	mi := &file_common_event_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLog.ProtoReflect.Descriptor instead.
func (*EventLog) Descriptor() ([]byte, []int) {
	return file_common_event_common_proto_rawDescGZIP(), []int{4}
}

func (x *EventLog) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventLog) GetPage() *ResponsePaginationInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

type EventNotification struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Event        *Event                 `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
	EventVersion *uint32                `protobuf:"varint,2,opt,name=event_version,json=eventVersion" json:"event_version,omitempty"`
	Transition   *EventTransitionE      `protobuf:"varint,3,opt,name=transition,enum=scte.common.EventTransitionE" json:"transition,omitempty"`
	// the active events bitmask is a bitmask containing the active event bit positions set in the active_event_bitmasks array
	// if an active alert's bit position is beyond 32, then the subsequent array entries will be used.
	// this includes the current event bitmask changes
	ActiveEventsBitmask []uint32 `protobuf:"varint,4,rep,name=active_events_bitmask,json=activeEventsBitmask" json:"active_events_bitmask,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EventNotification) Reset() {
	*x = EventNotification{}
	mi := &file_common_event_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventNotification) ProtoMessage() {}

func (x *EventNotification) ProtoReflect() protoreflect.Message {
	mi := &file_common_event_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventNotification.ProtoReflect.Descriptor instead.
func (*EventNotification) Descriptor() ([]byte, []int) {
	return file_common_event_common_proto_rawDescGZIP(), []int{5}
}

func (x *EventNotification) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventNotification) GetEventVersion() uint32 {
	if x != nil && x.EventVersion != nil {
		return *x.EventVersion
	}
	return 0
}

func (x *EventNotification) GetTransition() EventTransitionE {
	if x != nil && x.Transition != nil {
		return *x.Transition
	}
	return EventTransitionE_EVENT_TRANSITION_ASSERT
}

func (x *EventNotification) GetActiveEventsBitmask() []uint32 {
	if x != nil {
		return x.ActiveEventsBitmask
	}
	return nil
}

type EventThrottleCfg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threshold     *uint32                `protobuf:"varint,1,opt,name=threshold" json:"threshold,omitempty"`
	Interval      *uint32                `protobuf:"varint,2,opt,name=interval" json:"interval,omitempty"`
	Write         *bool                  `protobuf:"varint,3,opt,name=write,def=0" json:"write,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for EventThrottleCfg fields.
const (
	Default_EventThrottleCfg_Write = bool(false)
)

func (x *EventThrottleCfg) Reset() {
	*x = EventThrottleCfg{}
	mi := &file_common_event_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventThrottleCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventThrottleCfg) ProtoMessage() {}

func (x *EventThrottleCfg) ProtoReflect() protoreflect.Message {
	mi := &file_common_event_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventThrottleCfg.ProtoReflect.Descriptor instead.
func (*EventThrottleCfg) Descriptor() ([]byte, []int) {
	return file_common_event_common_proto_rawDescGZIP(), []int{6}
}

func (x *EventThrottleCfg) GetThreshold() uint32 {
	if x != nil && x.Threshold != nil {
		return *x.Threshold
	}
	return 0
}

func (x *EventThrottleCfg) GetInterval() uint32 {
	if x != nil && x.Interval != nil {
		return *x.Interval
	}
	return 0
}

func (x *EventThrottleCfg) GetWrite() bool {
	if x != nil && x.Write != nil {
		return *x.Write
	}
	return Default_EventThrottleCfg_Write
}

type EventReportingCfg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Priority      *EventPriorityE        `protobuf:"varint,1,opt,name=priority,enum=scte.common.EventPriorityE" json:"priority,omitempty"`
	Reporting     *uint32                `protobuf:"varint,2,opt,name=reporting,def=0" json:"reporting,omitempty"`
	Write         *bool                  `protobuf:"varint,3,opt,name=write,def=0" json:"write,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for EventReportingCfg fields.
const (
	Default_EventReportingCfg_Reporting = uint32(0)
	Default_EventReportingCfg_Write     = bool(false)
)

func (x *EventReportingCfg) Reset() {
	*x = EventReportingCfg{}
	mi := &file_common_event_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventReportingCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventReportingCfg) ProtoMessage() {}

func (x *EventReportingCfg) ProtoReflect() protoreflect.Message {
	mi := &file_common_event_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventReportingCfg.ProtoReflect.Descriptor instead.
func (*EventReportingCfg) Descriptor() ([]byte, []int) {
	return file_common_event_common_proto_rawDescGZIP(), []int{7}
}

func (x *EventReportingCfg) GetPriority() EventPriorityE {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return EventPriorityE_EVENT_PRIORITY_EMERGENCY
}

func (x *EventReportingCfg) GetReporting() uint32 {
	if x != nil && x.Reporting != nil {
		return *x.Reporting
	}
	return Default_EventReportingCfg_Reporting
}

func (x *EventReportingCfg) GetWrite() bool {
	if x != nil && x.Write != nil {
		return *x.Write
	}
	return Default_EventReportingCfg_Write
}

var File_common_event_common_proto protoreflect.FileDescriptor

const file_common_event_common_proto_rawDesc = "" +
	"\n" +
	"\x19common/event_common.proto\x12\vscte.common\x1a\x17common/pagination.proto\"q\n" +
	"\x0fEventDefinition\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\rR\aeventId\x12!\n" +
	"\fbit_position\x18\x02 \x03(\rR\vbitPosition\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x96\x01\n" +
	"\x11EventCapabilities\x126\n" +
	"\x18local_event_log_max_size\x18\x01 \x01(\rR\x14localEventLogMaxSize\x12I\n" +
	"\x11event_definitions\x18\x02 \x03(\v2\x1c.scte.common.EventDefinitionR\x10eventDefinitions\"M\n" +
	"\vEventStatus\x12>\n" +
	"\x1bthrottle_threshold_exceeded\x18\x01 \x01(\bR\x19throttleThresholdExceeded\"\xbd\x01\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\rR\aeventId\x12\x1d\n" +
	"\n" +
	"first_time\x18\x02 \x01(\tR\tfirstTime\x12\x1b\n" +
	"\tlast_time\x18\x03 \x01(\tR\blastTime\x12\x14\n" +
	"\x05count\x18\x04 \x01(\rR\x05count\x123\n" +
	"\x05level\x18\x05 \x01(\x0e2\x1d.scte.common.event_priority_eR\x05level\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\"o\n" +
	"\bEventLog\x12*\n" +
	"\x06events\x18\x01 \x03(\v2\x12.scte.common.EventR\x06events\x127\n" +
	"\x04page\x18\x02 \x01(\v2#.scte.common.ResponsePaginationInfoR\x04page\"\xd7\x01\n" +
	"\x11EventNotification\x12(\n" +
	"\x05event\x18\x01 \x01(\v2\x12.scte.common.EventR\x05event\x12#\n" +
	"\revent_version\x18\x02 \x01(\rR\feventVersion\x12?\n" +
	"\n" +
	"transition\x18\x03 \x01(\x0e2\x1f.scte.common.event_transition_eR\n" +
	"transition\x122\n" +
	"\x15active_events_bitmask\x18\x04 \x03(\rR\x13activeEventsBitmask\"i\n" +
	"\x10EventThrottleCfg\x12\x1c\n" +
	"\tthreshold\x18\x01 \x01(\rR\tthreshold\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\rR\binterval\x12\x1b\n" +
	"\x05write\x18\x03 \x01(\b:\x05falseR\x05write\"\x8c\x01\n" +
	"\x11EventReportingCfg\x129\n" +
	"\bpriority\x18\x01 \x01(\x0e2\x1d.scte.common.event_priority_eR\bpriority\x12\x1f\n" +
	"\treporting\x18\x02 \x01(\r:\x010R\treporting\x12\x1b\n" +
	"\x05write\x18\x03 \x01(\b:\x05falseR\x05write*\xeb\x01\n" +
	"\x10event_priority_e\x12\x1c\n" +
	"\x18EVENT_PRIORITY_EMERGENCY\x10\x01\x12\x18\n" +
	"\x14EVENT_PRIORITY_ALERT\x10\x02\x12\x1b\n" +
	"\x17EVENT_PRIORITY_CRITICAL\x10\x03\x12\x18\n" +
	"\x14EVENT_PRIORITY_ERROR\x10\x04\x12\x1a\n" +
	"\x16EVENT_PRIORITY_WARNING\x10\x05\x12\x19\n" +
	"\x15EVENT_PRIORITY_NOTICE\x10\x06\x12\x17\n" +
	"\x13EVENT_PRIORITY_INFO\x10\a\x12\x18\n" +
	"\x14EVENT_PRIORITY_DEBUG\x10\b*u\n" +
	"\x12event_transition_e\x12\x1b\n" +
	"\x17EVENT_TRANSITION_ASSERT\x10\x01\x12\x1a\n" +
	"\x16EVENT_TRANSITION_CLEAR\x10\x02\x12&\n" +
	"\"EVENT_TRANSITION_NOTIFICATION_ONLY\x10\x03B1Z/github.com/enshure/scte-go/common_go;sctecommon"

var (
	file_common_event_common_proto_rawDescOnce sync.Once
	file_common_event_common_proto_rawDescData []byte
)

func file_common_event_common_proto_rawDescGZIP() []byte {
	file_common_event_common_proto_rawDescOnce.Do(func() {
		file_common_event_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_event_common_proto_rawDesc), len(file_common_event_common_proto_rawDesc)))
	})
	return file_common_event_common_proto_rawDescData
}

var file_common_event_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_event_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_common_event_common_proto_goTypes = []any{
	(EventPriorityE)(0),            // 0: scte.common.event_priority_e
	(EventTransitionE)(0),          // 1: scte.common.event_transition_e
	(*EventDefinition)(nil),        // 2: scte.common.EventDefinition
	(*EventCapabilities)(nil),      // 3: scte.common.EventCapabilities
	(*EventStatus)(nil),            // 4: scte.common.EventStatus
	(*Event)(nil),                  // 5: scte.common.Event
	(*EventLog)(nil),               // 6: scte.common.EventLog
	(*EventNotification)(nil),      // 7: scte.common.EventNotification
	(*EventThrottleCfg)(nil),       // 8: scte.common.EventThrottleCfg
	(*EventReportingCfg)(nil),      // 9: scte.common.EventReportingCfg
	(*ResponsePaginationInfo)(nil), // 10: scte.common.ResponsePaginationInfo
}
var file_common_event_common_proto_depIdxs = []int32{
	2,  // 0: scte.common.EventCapabilities.event_definitions:type_name -> scte.common.EventDefinition
	0,  // 1: scte.common.Event.level:type_name -> scte.common.event_priority_e
	5,  // 2: scte.common.EventLog.events:type_name -> scte.common.Event
	10, // 3: scte.common.EventLog.page:type_name -> scte.common.ResponsePaginationInfo
	5,  // 4: scte.common.EventNotification.event:type_name -> scte.common.Event
	1,  // 5: scte.common.EventNotification.transition:type_name -> scte.common.event_transition_e
	0,  // 6: scte.common.EventReportingCfg.priority:type_name -> scte.common.event_priority_e
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_common_event_common_proto_init() }
func file_common_event_common_proto_init() {
	if File_common_event_common_proto != nil {
		return
	}
	file_common_pagination_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_event_common_proto_rawDesc), len(file_common_event_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_event_common_proto_goTypes,
		DependencyIndexes: file_common_event_common_proto_depIdxs,
		EnumInfos:         file_common_event_common_proto_enumTypes,
		MessageInfos:      file_common_event_common_proto_msgTypes,
	}.Build()
	File_common_event_common_proto = out.File
	file_common_event_common_proto_goTypes = nil
	file_common_event_common_proto_depIdxs = nil
}
