// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: common/vendor_common.proto

package sctecommon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VendorSpecificEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`    // defined by the vendor, for example aoi_vendor_rf_capability_id_e
	Name  *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"` // Human-readable hint only; id is the contract, max length of 32 characters.
	// Types that are valid to be assigned to Value:
	//
	//	*VendorSpecificEntry_BoolValue
	//	*VendorSpecificEntry_UintValue
	//	*VendorSpecificEntry_StringValue
	//	*VendorSpecificEntry_BlobValue
	Value         isVendorSpecificEntry_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VendorSpecificEntry) Reset() {
	*x = VendorSpecificEntry{}
	mi := &file_common_vendor_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VendorSpecificEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VendorSpecificEntry) ProtoMessage() {}

func (x *VendorSpecificEntry) ProtoReflect() protoreflect.Message {
	mi := &file_common_vendor_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VendorSpecificEntry.ProtoReflect.Descriptor instead.
func (*VendorSpecificEntry) Descriptor() ([]byte, []int) {
	return file_common_vendor_common_proto_rawDescGZIP(), []int{0}
}

func (x *VendorSpecificEntry) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *VendorSpecificEntry) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *VendorSpecificEntry) GetValue() isVendorSpecificEntry_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *VendorSpecificEntry) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*VendorSpecificEntry_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *VendorSpecificEntry) GetUintValue() uint32 {
	if x != nil {
		if x, ok := x.Value.(*VendorSpecificEntry_UintValue); ok {
			return x.UintValue
		}
	}
	return 0
}

func (x *VendorSpecificEntry) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*VendorSpecificEntry_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *VendorSpecificEntry) GetBlobValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*VendorSpecificEntry_BlobValue); ok {
			return x.BlobValue
		}
	}
	return nil
}

type isVendorSpecificEntry_Value interface {
	isVendorSpecificEntry_Value()
}

type VendorSpecificEntry_BoolValue struct {
	BoolValue bool `protobuf:"varint,10,opt,name=bool_value,json=boolValue,oneof"`
}

type VendorSpecificEntry_UintValue struct {
	UintValue uint32 `protobuf:"varint,11,opt,name=uint_value,json=uintValue,oneof"`
}

type VendorSpecificEntry_StringValue struct {
	StringValue string `protobuf:"bytes,12,opt,name=string_value,json=stringValue,oneof"`
}

type VendorSpecificEntry_BlobValue struct {
	BlobValue []byte `protobuf:"bytes,13,opt,name=blob_value,json=blobValue,oneof"`
}

func (*VendorSpecificEntry_BoolValue) isVendorSpecificEntry_Value() {}

func (*VendorSpecificEntry_UintValue) isVendorSpecificEntry_Value() {}

func (*VendorSpecificEntry_StringValue) isVendorSpecificEntry_Value() {}

func (*VendorSpecificEntry_BlobValue) isVendorSpecificEntry_Value() {}

var File_common_vendor_common_proto protoreflect.FileDescriptor

const file_common_vendor_common_proto_rawDesc = "" +
	"\n" +
	"\x1acommon/vendor_common.proto\x12\vscte.common\"\xca\x01\n" +
	"\x13VendorSpecificEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\n" +
	"bool_value\x18\n" +
	" \x01(\bH\x00R\tboolValue\x12\x1f\n" +
	"\n" +
	"uint_value\x18\v \x01(\rH\x00R\tuintValue\x12#\n" +
	"\fstring_value\x18\f \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"blob_value\x18\r \x01(\fH\x00R\tblobValueB\a\n" +
	"\x05valueB1Z/github.com/enshure/scte-go/common_go;sctecommon"

var (
	file_common_vendor_common_proto_rawDescOnce sync.Once
	file_common_vendor_common_proto_rawDescData []byte
)

func file_common_vendor_common_proto_rawDescGZIP() []byte {
	file_common_vendor_common_proto_rawDescOnce.Do(func() {
		file_common_vendor_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_vendor_common_proto_rawDesc), len(file_common_vendor_common_proto_rawDesc)))
	})
	return file_common_vendor_common_proto_rawDescData
}

var file_common_vendor_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_vendor_common_proto_goTypes = []any{
	(*VendorSpecificEntry)(nil), // 0: scte.common.VendorSpecificEntry
}
var file_common_vendor_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_vendor_common_proto_init() }
func file_common_vendor_common_proto_init() {
	if File_common_vendor_common_proto != nil {
		return
	}
	file_common_vendor_common_proto_msgTypes[0].OneofWrappers = []any{
		(*VendorSpecificEntry_BoolValue)(nil),
		(*VendorSpecificEntry_UintValue)(nil),
		(*VendorSpecificEntry_StringValue)(nil),
		(*VendorSpecificEntry_BlobValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_vendor_common_proto_rawDesc), len(file_common_vendor_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_vendor_common_proto_goTypes,
		DependencyIndexes: file_common_vendor_common_proto_depIdxs,
		MessageInfos:      file_common_vendor_common_proto_msgTypes,
	}.Build()
	File_common_vendor_common_proto = out.File
	file_common_vendor_common_proto_goTypes = nil
	file_common_vendor_common_proto_depIdxs = nil
}
