// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: common/version_common.proto

package sctecommon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SwStateE int32

const (
	SwStateE_SW_STATE_UNKNOWN        SwStateE = 0
	SwStateE_SW_STATE_ACTIVE         SwStateE = 1
	SwStateE_SW_STATE_INACTIVE       SwStateE = 2
	SwStateE_SW_STATE_PENDING_REBOOT SwStateE = 3
)

// Enum value maps for SwStateE.
var (
	SwStateE_name = map[int32]string{
		0: "SW_STATE_UNKNOWN",
		1: "SW_STATE_ACTIVE",
		2: "SW_STATE_INACTIVE",
		3: "SW_STATE_PENDING_REBOOT",
	}
	SwStateE_value = map[string]int32{
		"SW_STATE_UNKNOWN":        0,
		"SW_STATE_ACTIVE":         1,
		"SW_STATE_INACTIVE":       2,
		"SW_STATE_PENDING_REBOOT": 3,
	}
)

func (x SwStateE) Enum() *SwStateE {
	p := new(SwStateE)
	*p = x
	return p
}

func (x SwStateE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SwStateE) Descriptor() protoreflect.EnumDescriptor {
	return file_common_version_common_proto_enumTypes[0].Descriptor()
}

func (SwStateE) Type() protoreflect.EnumType {
	return &file_common_version_common_proto_enumTypes[0]
}

func (x SwStateE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SwStateE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SwStateE(num)
	return nil
}

// Deprecated: Use SwStateE.Descriptor instead.
func (SwStateE) EnumDescriptor() ([]byte, []int) {
	return file_common_version_common_proto_rawDescGZIP(), []int{0}
}

type SwComponentTypeE int32

const (
	SwComponentTypeE_SW_COMPONENT_UNKNOWN         SwComponentTypeE = 0
	SwComponentTypeE_SW_COMPONENT_BOOTLOADER      SwComponentTypeE = 1
	SwComponentTypeE_SW_COMPONENT_FIRMWARE        SwComponentTypeE = 2
	SwComponentTypeE_SW_COMPONENT_APPLICATION     SwComponentTypeE = 3
	SwComponentTypeE_SW_COMPONENT_FPGA            SwComponentTypeE = 4
	SwComponentTypeE_SW_COMPONENT_CONFIG          SwComponentTypeE = 5
	SwComponentTypeE_SW_COMPONENT_VENDOR_SPECIFIC SwComponentTypeE = 1000
)

// Enum value maps for SwComponentTypeE.
var (
	SwComponentTypeE_name = map[int32]string{
		0:    "SW_COMPONENT_UNKNOWN",
		1:    "SW_COMPONENT_BOOTLOADER",
		2:    "SW_COMPONENT_FIRMWARE",
		3:    "SW_COMPONENT_APPLICATION",
		4:    "SW_COMPONENT_FPGA",
		5:    "SW_COMPONENT_CONFIG",
		1000: "SW_COMPONENT_VENDOR_SPECIFIC",
	}
	SwComponentTypeE_value = map[string]int32{
		"SW_COMPONENT_UNKNOWN":         0,
		"SW_COMPONENT_BOOTLOADER":      1,
		"SW_COMPONENT_FIRMWARE":        2,
		"SW_COMPONENT_APPLICATION":     3,
		"SW_COMPONENT_FPGA":            4,
		"SW_COMPONENT_CONFIG":          5,
		"SW_COMPONENT_VENDOR_SPECIFIC": 1000,
	}
)

func (x SwComponentTypeE) Enum() *SwComponentTypeE {
	p := new(SwComponentTypeE)
	*p = x
	return p
}

func (x SwComponentTypeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SwComponentTypeE) Descriptor() protoreflect.EnumDescriptor {
	return file_common_version_common_proto_enumTypes[1].Descriptor()
}

func (SwComponentTypeE) Type() protoreflect.EnumType {
	return &file_common_version_common_proto_enumTypes[1]
}

func (x SwComponentTypeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SwComponentTypeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SwComponentTypeE(num)
	return nil
}

// Deprecated: Use SwComponentTypeE.Descriptor instead.
func (SwComponentTypeE) EnumDescriptor() ([]byte, []int) {
	return file_common_version_common_proto_rawDescGZIP(), []int{1}
}

type SoftwareComponentVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *string                `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	State         *SwStateE              `protobuf:"varint,2,opt,name=state,enum=scte.common.SwStateE" json:"state,omitempty"`
	Type          *SwComponentTypeE      `protobuf:"varint,3,opt,name=type,enum=scte.common.SwComponentTypeE" json:"type,omitempty"`
	VendorType    *uint32                `protobuf:"varint,4,opt,name=vendor_type,json=vendorType" json:"vendor_type,omitempty"`
	Name          *string                `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	BankId        *uint32                `protobuf:"varint,6,opt,name=bank_id,json=bankId" json:"bank_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoftwareComponentVersion) Reset() {
	*x = SoftwareComponentVersion{}
	mi := &file_common_version_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftwareComponentVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftwareComponentVersion) ProtoMessage() {}

func (x *SoftwareComponentVersion) ProtoReflect() protoreflect.Message {
	mi := &file_common_version_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftwareComponentVersion.ProtoReflect.Descriptor instead.
func (*SoftwareComponentVersion) Descriptor() ([]byte, []int) {
	return file_common_version_common_proto_rawDescGZIP(), []int{0}
}

func (x *SoftwareComponentVersion) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *SoftwareComponentVersion) GetState() SwStateE {
	if x != nil && x.State != nil {
		return *x.State
	}
	return SwStateE_SW_STATE_UNKNOWN
}

func (x *SoftwareComponentVersion) GetType() SwComponentTypeE {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return SwComponentTypeE_SW_COMPONENT_UNKNOWN
}

func (x *SoftwareComponentVersion) GetVendorType() uint32 {
	if x != nil && x.VendorType != nil {
		return *x.VendorType
	}
	return 0
}

func (x *SoftwareComponentVersion) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SoftwareComponentVersion) GetBankId() uint32 {
	if x != nil && x.BankId != nil {
		return *x.BankId
	}
	return 0
}

type VersionSummary struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Components    []*SoftwareComponentVersion `protobuf:"bytes,1,rep,name=components" json:"components,omitempty"`
	Page          *ResponsePaginationInfo     `protobuf:"bytes,2,opt,name=page" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionSummary) Reset() {
	*x = VersionSummary{}
	mi := &file_common_version_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionSummary) ProtoMessage() {}

func (x *VersionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_common_version_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionSummary.ProtoReflect.Descriptor instead.
func (*VersionSummary) Descriptor() ([]byte, []int) {
	return file_common_version_common_proto_rawDescGZIP(), []int{1}
}

func (x *VersionSummary) GetComponents() []*SoftwareComponentVersion {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *VersionSummary) GetPage() *ResponsePaginationInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_common_version_common_proto protoreflect.FileDescriptor

const file_common_version_common_proto_rawDesc = "" +
	"\n" +
	"\x1bcommon/version_common.proto\x12\vscte.common\x1a\x17common/pagination.proto\"\xe7\x01\n" +
	"\x18SoftwareComponentVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12-\n" +
	"\x05state\x18\x02 \x01(\x0e2\x17.scte.common.sw_state_eR\x05state\x124\n" +
	"\x04type\x18\x03 \x01(\x0e2 .scte.common.sw_component_type_eR\x04type\x12\x1f\n" +
	"\vvendor_type\x18\x04 \x01(\rR\n" +
	"vendorType\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x17\n" +
	"\abank_id\x18\x06 \x01(\rR\x06bankId\"\x90\x01\n" +
	"\x0eVersionSummary\x12E\n" +
	"\n" +
	"components\x18\x01 \x03(\v2%.scte.common.SoftwareComponentVersionR\n" +
	"components\x127\n" +
	"\x04page\x18\x02 \x01(\v2#.scte.common.ResponsePaginationInfoR\x04page*k\n" +
	"\n" +
	"sw_state_e\x12\x14\n" +
	"\x10SW_STATE_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fSW_STATE_ACTIVE\x10\x01\x12\x15\n" +
	"\x11SW_STATE_INACTIVE\x10\x02\x12\x1b\n" +
	"\x17SW_STATE_PENDING_REBOOT\x10\x03*\xd8\x01\n" +
	"\x13sw_component_type_e\x12\x18\n" +
	"\x14SW_COMPONENT_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17SW_COMPONENT_BOOTLOADER\x10\x01\x12\x19\n" +
	"\x15SW_COMPONENT_FIRMWARE\x10\x02\x12\x1c\n" +
	"\x18SW_COMPONENT_APPLICATION\x10\x03\x12\x15\n" +
	"\x11SW_COMPONENT_FPGA\x10\x04\x12\x17\n" +
	"\x13SW_COMPONENT_CONFIG\x10\x05\x12!\n" +
	"\x1cSW_COMPONENT_VENDOR_SPECIFIC\x10\xe8\aB;Z9github.com/enshure/scte-go/common_go;sctecommon"

var (
	file_common_version_common_proto_rawDescOnce sync.Once
	file_common_version_common_proto_rawDescData []byte
)

func file_common_version_common_proto_rawDescGZIP() []byte {
	file_common_version_common_proto_rawDescOnce.Do(func() {
		file_common_version_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_version_common_proto_rawDesc), len(file_common_version_common_proto_rawDesc)))
	})
	return file_common_version_common_proto_rawDescData
}

var file_common_version_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_version_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_version_common_proto_goTypes = []any{
	(SwStateE)(0),                    // 0: scte.common.sw_state_e
	(SwComponentTypeE)(0),            // 1: scte.common.sw_component_type_e
	(*SoftwareComponentVersion)(nil), // 2: scte.common.SoftwareComponentVersion
	(*VersionSummary)(nil),           // 3: scte.common.VersionSummary
	(*ResponsePaginationInfo)(nil),   // 4: scte.common.ResponsePaginationInfo
}
var file_common_version_common_proto_depIdxs = []int32{
	0, // 0: scte.common.SoftwareComponentVersion.state:type_name -> scte.common.sw_state_e
	1, // 1: scte.common.SoftwareComponentVersion.type:type_name -> scte.common.sw_component_type_e
	2, // 2: scte.common.VersionSummary.components:type_name -> scte.common.SoftwareComponentVersion
	4, // 3: scte.common.VersionSummary.page:type_name -> scte.common.ResponsePaginationInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_common_version_common_proto_init() }
func file_common_version_common_proto_init() {
	if File_common_version_common_proto != nil {
		return
	}
	file_common_pagination_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_version_common_proto_rawDesc), len(file_common_version_common_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_version_common_proto_goTypes,
		DependencyIndexes: file_common_version_common_proto_depIdxs,
		EnumInfos:         file_common_version_common_proto_enumTypes,
		MessageInfos:      file_common_version_common_proto_msgTypes,
	}.Build()
	File_common_version_common_proto = out.File
	file_common_version_common_proto_goTypes = nil
	file_common_version_common_proto_depIdxs = nil
}
