// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: amps/common.proto

package scteamp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PathSelectorE int32

const (
	PathSelectorE_DOWNSTREAM PathSelectorE = 1
	PathSelectorE_UPSTREAM   PathSelectorE = 2
)

// Enum value maps for PathSelectorE.
var (
	PathSelectorE_name = map[int32]string{
		1: "DOWNSTREAM",
		2: "UPSTREAM",
	}
	PathSelectorE_value = map[string]int32{
		"DOWNSTREAM": 1,
		"UPSTREAM":   2,
	}
)

func (x PathSelectorE) Enum() *PathSelectorE {
	p := new(PathSelectorE)
	*p = x
	return p
}

func (x PathSelectorE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PathSelectorE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[0].Descriptor()
}

func (PathSelectorE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[0]
}

func (x PathSelectorE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PathSelectorE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PathSelectorE(num)
	return nil
}

// Deprecated: Use PathSelectorE.Descriptor instead.
func (PathSelectorE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{0}
}

type AutoAlignmentOpE int32

const (
	// Deprecated: Marked as deprecated in amps/common.proto.
	AutoAlignmentOpE_PRE_TUNE AutoAlignmentOpE = 1
	// Deprecated: Marked as deprecated in amps/common.proto.
	AutoAlignmentOpE_COARSE_TUNE AutoAlignmentOpE = 2
	// Deprecated: Marked as deprecated in amps/common.proto.
	AutoAlignmentOpE_FINE_TUNE AutoAlignmentOpE = 3
	AutoAlignmentOpE_FULL_TUNE AutoAlignmentOpE = 4
	AutoAlignmentOpE_SAVE      AutoAlignmentOpE = 5
	AutoAlignmentOpE_REVERT    AutoAlignmentOpE = 6
	AutoAlignmentOpE_CSM_CALC  AutoAlignmentOpE = 7
	AutoAlignmentOpE_RMSE_CALC AutoAlignmentOpE = 8
	// Deprecated: Marked as deprecated in amps/common.proto.
	AutoAlignmentOpE_RSME_CALC     AutoAlignmentOpE = 8
	AutoAlignmentOpE_SAVE_COMPLETE AutoAlignmentOpE = 9
)

// Enum value maps for AutoAlignmentOpE.
var (
	AutoAlignmentOpE_name = map[int32]string{
		1: "PRE_TUNE",
		2: "COARSE_TUNE",
		3: "FINE_TUNE",
		4: "FULL_TUNE",
		5: "SAVE",
		6: "REVERT",
		7: "CSM_CALC",
		8: "RMSE_CALC",
		// Duplicate value: 8: "RSME_CALC",
		9: "SAVE_COMPLETE",
	}
	AutoAlignmentOpE_value = map[string]int32{
		"PRE_TUNE":      1,
		"COARSE_TUNE":   2,
		"FINE_TUNE":     3,
		"FULL_TUNE":     4,
		"SAVE":          5,
		"REVERT":        6,
		"CSM_CALC":      7,
		"RMSE_CALC":     8,
		"RSME_CALC":     8,
		"SAVE_COMPLETE": 9,
	}
)

func (x AutoAlignmentOpE) Enum() *AutoAlignmentOpE {
	p := new(AutoAlignmentOpE)
	*p = x
	return p
}

func (x AutoAlignmentOpE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AutoAlignmentOpE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[1].Descriptor()
}

func (AutoAlignmentOpE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[1]
}

func (x AutoAlignmentOpE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AutoAlignmentOpE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AutoAlignmentOpE(num)
	return nil
}

// Deprecated: Use AutoAlignmentOpE.Descriptor instead.
func (AutoAlignmentOpE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{1}
}

type AutoAlignmentStatusE int32

const (
	AutoAlignmentStatusE_IDLE        AutoAlignmentStatusE = 1
	AutoAlignmentStatusE_IN_PROGRESS AutoAlignmentStatusE = 2
	AutoAlignmentStatusE_COMPLETE    AutoAlignmentStatusE = 3
	AutoAlignmentStatusE_ERROR       AutoAlignmentStatusE = 4
)

// Enum value maps for AutoAlignmentStatusE.
var (
	AutoAlignmentStatusE_name = map[int32]string{
		1: "IDLE",
		2: "IN_PROGRESS",
		3: "COMPLETE",
		4: "ERROR",
	}
	AutoAlignmentStatusE_value = map[string]int32{
		"IDLE":        1,
		"IN_PROGRESS": 2,
		"COMPLETE":    3,
		"ERROR":       4,
	}
)

func (x AutoAlignmentStatusE) Enum() *AutoAlignmentStatusE {
	p := new(AutoAlignmentStatusE)
	*p = x
	return p
}

func (x AutoAlignmentStatusE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AutoAlignmentStatusE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[2].Descriptor()
}

func (AutoAlignmentStatusE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[2]
}

func (x AutoAlignmentStatusE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AutoAlignmentStatusE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AutoAlignmentStatusE(num)
	return nil
}

// Deprecated: Use AutoAlignmentStatusE.Descriptor instead.
func (AutoAlignmentStatusE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{2}
}

type EnclosureStatusE int32

const (
	EnclosureStatusE_CLOSED EnclosureStatusE = 1
	EnclosureStatusE_OPEN   EnclosureStatusE = 2
)

// Enum value maps for EnclosureStatusE.
var (
	EnclosureStatusE_name = map[int32]string{
		1: "CLOSED",
		2: "OPEN",
	}
	EnclosureStatusE_value = map[string]int32{
		"CLOSED": 1,
		"OPEN":   2,
	}
)

func (x EnclosureStatusE) Enum() *EnclosureStatusE {
	p := new(EnclosureStatusE)
	*p = x
	return p
}

func (x EnclosureStatusE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnclosureStatusE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[3].Descriptor()
}

func (EnclosureStatusE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[3]
}

func (x EnclosureStatusE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EnclosureStatusE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EnclosureStatusE(num)
	return nil
}

// Deprecated: Use EnclosureStatusE.Descriptor instead.
func (EnclosureStatusE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{3}
}

type DsGainStageE int32

const (
	DsGainStageE_DS_INPUT_ATTN         DsGainStageE = 1
	DsGainStageE_DS_INTERSTAGE_ATTN    DsGainStageE = 2
	DsGainStageE_DS_OVERLOAD_PROT_ATTN DsGainStageE = 3
	DsGainStageE_DS_CUMULATIVE_ATTN    DsGainStageE = 4
)

// Enum value maps for DsGainStageE.
var (
	DsGainStageE_name = map[int32]string{
		1: "DS_INPUT_ATTN",
		2: "DS_INTERSTAGE_ATTN",
		3: "DS_OVERLOAD_PROT_ATTN",
		4: "DS_CUMULATIVE_ATTN",
	}
	DsGainStageE_value = map[string]int32{
		"DS_INPUT_ATTN":         1,
		"DS_INTERSTAGE_ATTN":    2,
		"DS_OVERLOAD_PROT_ATTN": 3,
		"DS_CUMULATIVE_ATTN":    4,
	}
)

func (x DsGainStageE) Enum() *DsGainStageE {
	p := new(DsGainStageE)
	*p = x
	return p
}

func (x DsGainStageE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DsGainStageE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[4].Descriptor()
}

func (DsGainStageE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[4]
}

func (x DsGainStageE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DsGainStageE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DsGainStageE(num)
	return nil
}

// Deprecated: Use DsGainStageE.Descriptor instead.
func (DsGainStageE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{4}
}

type DsEqStageE int32

const (
	DsEqStageE_DS_INPUT_EQ      DsEqStageE = 1
	DsEqStageE_DS_INTERSTAGE_EQ DsEqStageE = 2
	DsEqStageE_DS_OUTPUT_EQ     DsEqStageE = 3
	DsEqStageE_DS_CUMULATIVE_EQ DsEqStageE = 4
)

// Enum value maps for DsEqStageE.
var (
	DsEqStageE_name = map[int32]string{
		1: "DS_INPUT_EQ",
		2: "DS_INTERSTAGE_EQ",
		3: "DS_OUTPUT_EQ",
		4: "DS_CUMULATIVE_EQ",
	}
	DsEqStageE_value = map[string]int32{
		"DS_INPUT_EQ":      1,
		"DS_INTERSTAGE_EQ": 2,
		"DS_OUTPUT_EQ":     3,
		"DS_CUMULATIVE_EQ": 4,
	}
)

func (x DsEqStageE) Enum() *DsEqStageE {
	p := new(DsEqStageE)
	*p = x
	return p
}

func (x DsEqStageE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DsEqStageE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[5].Descriptor()
}

func (DsEqStageE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[5]
}

func (x DsEqStageE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DsEqStageE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DsEqStageE(num)
	return nil
}

// Deprecated: Use DsEqStageE.Descriptor instead.
func (DsEqStageE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{5}
}

type AgcConfigE int32

const (
	AgcConfigE_THERMAL AgcConfigE = 1
	AgcConfigE_MANUAL  AgcConfigE = 2
	AgcConfigE_ON      AgcConfigE = 3
)

// Enum value maps for AgcConfigE.
var (
	AgcConfigE_name = map[int32]string{
		1: "THERMAL",
		2: "MANUAL",
		3: "ON",
	}
	AgcConfigE_value = map[string]int32{
		"THERMAL": 1,
		"MANUAL":  2,
		"ON":      3,
	}
)

func (x AgcConfigE) Enum() *AgcConfigE {
	p := new(AgcConfigE)
	*p = x
	return p
}

func (x AgcConfigE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgcConfigE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[6].Descriptor()
}

func (AgcConfigE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[6]
}

func (x AgcConfigE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AgcConfigE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AgcConfigE(num)
	return nil
}

// Deprecated: Use AgcConfigE.Descriptor instead.
func (AgcConfigE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{6}
}

type UsGainStageE int32

const (
	UsGainStageE_US_ATTN1 UsGainStageE = 1
	UsGainStageE_US_ATTN2 UsGainStageE = 2
	UsGainStageE_US_CUMU  UsGainStageE = 3
)

// Enum value maps for UsGainStageE.
var (
	UsGainStageE_name = map[int32]string{
		1: "US_ATTN1",
		2: "US_ATTN2",
		3: "US_CUMU",
	}
	UsGainStageE_value = map[string]int32{
		"US_ATTN1": 1,
		"US_ATTN2": 2,
		"US_CUMU":  3,
	}
)

func (x UsGainStageE) Enum() *UsGainStageE {
	p := new(UsGainStageE)
	*p = x
	return p
}

func (x UsGainStageE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UsGainStageE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[7].Descriptor()
}

func (UsGainStageE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[7]
}

func (x UsGainStageE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *UsGainStageE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = UsGainStageE(num)
	return nil
}

// Deprecated: Use UsGainStageE.Descriptor instead.
func (UsGainStageE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{7}
}

type UsEqStageE int32

const (
	UsEqStageE_US_EQ1     UsEqStageE = 1
	UsEqStageE_US_CUMU_EQ UsEqStageE = 2
)

// Enum value maps for UsEqStageE.
var (
	UsEqStageE_name = map[int32]string{
		1: "US_EQ1",
		2: "US_CUMU_EQ",
	}
	UsEqStageE_value = map[string]int32{
		"US_EQ1":     1,
		"US_CUMU_EQ": 2,
	}
)

func (x UsEqStageE) Enum() *UsEqStageE {
	p := new(UsEqStageE)
	*p = x
	return p
}

func (x UsEqStageE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UsEqStageE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[8].Descriptor()
}

func (UsEqStageE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[8]
}

func (x UsEqStageE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *UsEqStageE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = UsEqStageE(num)
	return nil
}

// Deprecated: Use UsEqStageE.Descriptor instead.
func (UsEqStageE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{8}
}

type IngressSwitchConfigE int32

const (
	IngressSwitchConfigE_SW_0      IngressSwitchConfigE = 0
	IngressSwitchConfigE_SW_NEG_6  IngressSwitchConfigE = 1
	IngressSwitchConfigE_SW_NEG_50 IngressSwitchConfigE = 2
)

// Enum value maps for IngressSwitchConfigE.
var (
	IngressSwitchConfigE_name = map[int32]string{
		0: "SW_0",
		1: "SW_NEG_6",
		2: "SW_NEG_50",
	}
	IngressSwitchConfigE_value = map[string]int32{
		"SW_0":      0,
		"SW_NEG_6":  1,
		"SW_NEG_50": 2,
	}
)

func (x IngressSwitchConfigE) Enum() *IngressSwitchConfigE {
	p := new(IngressSwitchConfigE)
	*p = x
	return p
}

func (x IngressSwitchConfigE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IngressSwitchConfigE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[9].Descriptor()
}

func (IngressSwitchConfigE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[9]
}

func (x IngressSwitchConfigE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *IngressSwitchConfigE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = IngressSwitchConfigE(num)
	return nil
}

// Deprecated: Use IngressSwitchConfigE.Descriptor instead.
func (IngressSwitchConfigE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{9}
}

type TestPointIdE int32

const (
	TestPointIdE_INPUT_TP  TestPointIdE = 1
	TestPointIdE_OUTPUT_TP TestPointIdE = 2
	TestPointIdE_AUX1_TP   TestPointIdE = 3
	TestPointIdE_AUX2_TP   TestPointIdE = 4
)

// Enum value maps for TestPointIdE.
var (
	TestPointIdE_name = map[int32]string{
		1: "INPUT_TP",
		2: "OUTPUT_TP",
		3: "AUX1_TP",
		4: "AUX2_TP",
	}
	TestPointIdE_value = map[string]int32{
		"INPUT_TP":  1,
		"OUTPUT_TP": 2,
		"AUX1_TP":   3,
		"AUX2_TP":   4,
	}
)

func (x TestPointIdE) Enum() *TestPointIdE {
	p := new(TestPointIdE)
	*p = x
	return p
}

func (x TestPointIdE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestPointIdE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[10].Descriptor()
}

func (TestPointIdE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[10]
}

func (x TestPointIdE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TestPointIdE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TestPointIdE(num)
	return nil
}

// Deprecated: Use TestPointIdE.Descriptor instead.
func (TestPointIdE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{10}
}

type TestPointConfigE int32

const (
	TestPointConfigE_FWD TestPointConfigE = 1
	TestPointConfigE_REV TestPointConfigE = 2
)

// Enum value maps for TestPointConfigE.
var (
	TestPointConfigE_name = map[int32]string{
		1: "FWD",
		2: "REV",
	}
	TestPointConfigE_value = map[string]int32{
		"FWD": 1,
		"REV": 2,
	}
)

func (x TestPointConfigE) Enum() *TestPointConfigE {
	p := new(TestPointConfigE)
	*p = x
	return p
}

func (x TestPointConfigE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestPointConfigE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[11].Descriptor()
}

func (TestPointConfigE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[11]
}

func (x TestPointConfigE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TestPointConfigE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TestPointConfigE(num)
	return nil
}

// Deprecated: Use TestPointConfigE.Descriptor instead.
func (TestPointConfigE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{11}
}

type SpectrumScanDataE int32

const (
	SpectrumScanDataE_SCAN_AUTO_CACHED_DATA SpectrumScanDataE = 0
	SpectrumScanDataE_SCAN_MANUAL_DATA      SpectrumScanDataE = 1
)

// Enum value maps for SpectrumScanDataE.
var (
	SpectrumScanDataE_name = map[int32]string{
		0: "SCAN_AUTO_CACHED_DATA",
		1: "SCAN_MANUAL_DATA",
	}
	SpectrumScanDataE_value = map[string]int32{
		"SCAN_AUTO_CACHED_DATA": 0,
		"SCAN_MANUAL_DATA":      1,
	}
)

func (x SpectrumScanDataE) Enum() *SpectrumScanDataE {
	p := new(SpectrumScanDataE)
	*p = x
	return p
}

func (x SpectrumScanDataE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpectrumScanDataE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[12].Descriptor()
}

func (SpectrumScanDataE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[12]
}

func (x SpectrumScanDataE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SpectrumScanDataE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SpectrumScanDataE(num)
	return nil
}

// Deprecated: Use SpectrumScanDataE.Descriptor instead.
func (SpectrumScanDataE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{12}
}

type SpectrumScanStatusE int32

const (
	SpectrumScanStatusE_SCAN_STATUS_INVALID     SpectrumScanStatusE = 0
	SpectrumScanStatusE_SCAN_STATUS_IN_PROGRESS SpectrumScanStatusE = 1
	SpectrumScanStatusE_SCAN_STATUS_VALID       SpectrumScanStatusE = 2
)

// Enum value maps for SpectrumScanStatusE.
var (
	SpectrumScanStatusE_name = map[int32]string{
		0: "SCAN_STATUS_INVALID",
		1: "SCAN_STATUS_IN_PROGRESS",
		2: "SCAN_STATUS_VALID",
	}
	SpectrumScanStatusE_value = map[string]int32{
		"SCAN_STATUS_INVALID":     0,
		"SCAN_STATUS_IN_PROGRESS": 1,
		"SCAN_STATUS_VALID":       2,
	}
)

func (x SpectrumScanStatusE) Enum() *SpectrumScanStatusE {
	p := new(SpectrumScanStatusE)
	*p = x
	return p
}

func (x SpectrumScanStatusE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpectrumScanStatusE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[13].Descriptor()
}

func (SpectrumScanStatusE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[13]
}

func (x SpectrumScanStatusE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SpectrumScanStatusE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SpectrumScanStatusE(num)
	return nil
}

// Deprecated: Use SpectrumScanStatusE.Descriptor instead.
func (SpectrumScanStatusE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{13}
}

type BandwidthModeE int32

const (
	BandwidthModeE_BW_MODE_1P2GHZ BandwidthModeE = 0
	BandwidthModeE_BW_MODE_1P8GHZ BandwidthModeE = 1
)

// Enum value maps for BandwidthModeE.
var (
	BandwidthModeE_name = map[int32]string{
		0: "BW_MODE_1P2GHZ",
		1: "BW_MODE_1P8GHZ",
	}
	BandwidthModeE_value = map[string]int32{
		"BW_MODE_1P2GHZ": 0,
		"BW_MODE_1P8GHZ": 1,
	}
)

func (x BandwidthModeE) Enum() *BandwidthModeE {
	p := new(BandwidthModeE)
	*p = x
	return p
}

func (x BandwidthModeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BandwidthModeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[14].Descriptor()
}

func (BandwidthModeE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[14]
}

func (x BandwidthModeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *BandwidthModeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = BandwidthModeE(num)
	return nil
}

// Deprecated: Use BandwidthModeE.Descriptor instead.
func (BandwidthModeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{14}
}

type SplitE int32

const (
	SplitE_SPLIT_42_54   SplitE = 0
	SplitE_SPLIT_65_85   SplitE = 1
	SplitE_SPLIT_85_108  SplitE = 2
	SplitE_SPLIT_204_258 SplitE = 3
	SplitE_SPLIT_300_372 SplitE = 4
	SplitE_SPLIT_396_492 SplitE = 5
	SplitE_SPLIT_492_606 SplitE = 6
	SplitE_SPLIT_684_834 SplitE = 7
)

// Enum value maps for SplitE.
var (
	SplitE_name = map[int32]string{
		0: "SPLIT_42_54",
		1: "SPLIT_65_85",
		2: "SPLIT_85_108",
		3: "SPLIT_204_258",
		4: "SPLIT_300_372",
		5: "SPLIT_396_492",
		6: "SPLIT_492_606",
		7: "SPLIT_684_834",
	}
	SplitE_value = map[string]int32{
		"SPLIT_42_54":   0,
		"SPLIT_65_85":   1,
		"SPLIT_85_108":  2,
		"SPLIT_204_258": 3,
		"SPLIT_300_372": 4,
		"SPLIT_396_492": 5,
		"SPLIT_492_606": 6,
		"SPLIT_684_834": 7,
	}
)

func (x SplitE) Enum() *SplitE {
	p := new(SplitE)
	*p = x
	return p
}

func (x SplitE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SplitE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[15].Descriptor()
}

func (SplitE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[15]
}

func (x SplitE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SplitE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SplitE(num)
	return nil
}

// Deprecated: Use SplitE.Descriptor instead.
func (SplitE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{15}
}

type HpftModuleE int32

const (
	HpftModuleE_HPFT_MODULE_MISSING HpftModuleE = 0
	HpftModuleE_HPFT_MODULE_108     HpftModuleE = 1
	HpftModuleE_HPFT_MODULE_258     HpftModuleE = 2
	HpftModuleE_HPFT_MODULE_492     HpftModuleE = 3
	HpftModuleE_HPFT_MODULE_606     HpftModuleE = 4
	HpftModuleE_HPFT_MODULE_834     HpftModuleE = 5
)

// Enum value maps for HpftModuleE.
var (
	HpftModuleE_name = map[int32]string{
		0: "HPFT_MODULE_MISSING",
		1: "HPFT_MODULE_108",
		2: "HPFT_MODULE_258",
		3: "HPFT_MODULE_492",
		4: "HPFT_MODULE_606",
		5: "HPFT_MODULE_834",
	}
	HpftModuleE_value = map[string]int32{
		"HPFT_MODULE_MISSING": 0,
		"HPFT_MODULE_108":     1,
		"HPFT_MODULE_258":     2,
		"HPFT_MODULE_492":     3,
		"HPFT_MODULE_606":     4,
		"HPFT_MODULE_834":     5,
	}
)

func (x HpftModuleE) Enum() *HpftModuleE {
	p := new(HpftModuleE)
	*p = x
	return p
}

func (x HpftModuleE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HpftModuleE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[16].Descriptor()
}

func (HpftModuleE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[16]
}

func (x HpftModuleE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *HpftModuleE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = HpftModuleE(num)
	return nil
}

// Deprecated: Use HpftModuleE.Descriptor instead.
func (HpftModuleE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{16}
}

type LpftModuleE int32

const (
	LpftModuleE_LPFT_MODULE_MISSING LpftModuleE = 0
	LpftModuleE_LPFT_MODULE_42      LpftModuleE = 1
	LpftModuleE_LPFT_MODULE_65      LpftModuleE = 2
	LpftModuleE_LPFT_MODULE_85      LpftModuleE = 3
	LpftModuleE_LPFT_MODULE_204     LpftModuleE = 4
	LpftModuleE_LPFT_MODULE_300     LpftModuleE = 5
	LpftModuleE_LPFT_MODULE_396     LpftModuleE = 6
	LpftModuleE_LPFT_MODULE_492     LpftModuleE = 7
	LpftModuleE_LPFT_MODULE_588     LpftModuleE = 8
	LpftModuleE_LPFT_MODULE_684     LpftModuleE = 9
)

// Enum value maps for LpftModuleE.
var (
	LpftModuleE_name = map[int32]string{
		0: "LPFT_MODULE_MISSING",
		1: "LPFT_MODULE_42",
		2: "LPFT_MODULE_65",
		3: "LPFT_MODULE_85",
		4: "LPFT_MODULE_204",
		5: "LPFT_MODULE_300",
		6: "LPFT_MODULE_396",
		7: "LPFT_MODULE_492",
		8: "LPFT_MODULE_588",
		9: "LPFT_MODULE_684",
	}
	LpftModuleE_value = map[string]int32{
		"LPFT_MODULE_MISSING": 0,
		"LPFT_MODULE_42":      1,
		"LPFT_MODULE_65":      2,
		"LPFT_MODULE_85":      3,
		"LPFT_MODULE_204":     4,
		"LPFT_MODULE_300":     5,
		"LPFT_MODULE_396":     6,
		"LPFT_MODULE_492":     7,
		"LPFT_MODULE_588":     8,
		"LPFT_MODULE_684":     9,
	}
)

func (x LpftModuleE) Enum() *LpftModuleE {
	p := new(LpftModuleE)
	*p = x
	return p
}

func (x LpftModuleE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LpftModuleE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[17].Descriptor()
}

func (LpftModuleE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[17]
}

func (x LpftModuleE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *LpftModuleE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = LpftModuleE(num)
	return nil
}

// Deprecated: Use LpftModuleE.Descriptor instead.
func (LpftModuleE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{17}
}

type InvEqModuleE int32

const (
	InvEqModuleE_INV_EQ_MODULE_MISSING InvEqModuleE = 0
	InvEqModuleE_INV_EQ_MODULE_JUMPER  InvEqModuleE = 1
	InvEqModuleE_INV_EQ_MODULE_300FT   InvEqModuleE = 2
)

// Enum value maps for InvEqModuleE.
var (
	InvEqModuleE_name = map[int32]string{
		0: "INV_EQ_MODULE_MISSING",
		1: "INV_EQ_MODULE_JUMPER",
		2: "INV_EQ_MODULE_300FT",
	}
	InvEqModuleE_value = map[string]int32{
		"INV_EQ_MODULE_MISSING": 0,
		"INV_EQ_MODULE_JUMPER":  1,
		"INV_EQ_MODULE_300FT":   2,
	}
)

func (x InvEqModuleE) Enum() *InvEqModuleE {
	p := new(InvEqModuleE)
	*p = x
	return p
}

func (x InvEqModuleE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvEqModuleE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[18].Descriptor()
}

func (InvEqModuleE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[18]
}

func (x InvEqModuleE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *InvEqModuleE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = InvEqModuleE(num)
	return nil
}

// Deprecated: Use InvEqModuleE.Descriptor instead.
func (InvEqModuleE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{18}
}

type AnnexE int32

const (
	AnnexE_ANNEX_A AnnexE = 0
	AnnexE_ANNEX_B AnnexE = 1
)

// Enum value maps for AnnexE.
var (
	AnnexE_name = map[int32]string{
		0: "ANNEX_A",
		1: "ANNEX_B",
	}
	AnnexE_value = map[string]int32{
		"ANNEX_A": 0,
		"ANNEX_B": 1,
	}
)

func (x AnnexE) Enum() *AnnexE {
	p := new(AnnexE)
	*p = x
	return p
}

func (x AnnexE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnnexE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[19].Descriptor()
}

func (AnnexE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[19]
}

func (x AnnexE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AnnexE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AnnexE(num)
	return nil
}

// Deprecated: Use AnnexE.Descriptor instead.
func (AnnexE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{19}
}

type IngressPortSelectE int32

const (
	IngressPortSelectE_INGRESS_MAIN IngressPortSelectE = 0
	IngressPortSelectE_INGRESS_AUX1 IngressPortSelectE = 1
	IngressPortSelectE_INGRESS_AUX2 IngressPortSelectE = 2
)

// Enum value maps for IngressPortSelectE.
var (
	IngressPortSelectE_name = map[int32]string{
		0: "INGRESS_MAIN",
		1: "INGRESS_AUX1",
		2: "INGRESS_AUX2",
	}
	IngressPortSelectE_value = map[string]int32{
		"INGRESS_MAIN": 0,
		"INGRESS_AUX1": 1,
		"INGRESS_AUX2": 2,
	}
)

func (x IngressPortSelectE) Enum() *IngressPortSelectE {
	p := new(IngressPortSelectE)
	*p = x
	return p
}

func (x IngressPortSelectE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IngressPortSelectE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[20].Descriptor()
}

func (IngressPortSelectE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[20]
}

func (x IngressPortSelectE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *IngressPortSelectE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = IngressPortSelectE(num)
	return nil
}

// Deprecated: Use IngressPortSelectE.Descriptor instead.
func (IngressPortSelectE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{20}
}

type ErrorCodeE int32

const (
	ErrorCodeE_SUCCESS                                ErrorCodeE = 0
	ErrorCodeE_ERROR_FREQUENCY_OUT_OF_RANGE           ErrorCodeE = 1
	ErrorCodeE_ERROR_FREQUENCY_NOT_ALIGNED            ErrorCodeE = 2
	ErrorCodeE_ERROR_FREQUENCY_START_GREATER_THAN_END ErrorCodeE = 3
)

// Enum value maps for ErrorCodeE.
var (
	ErrorCodeE_name = map[int32]string{
		0: "SUCCESS",
		1: "ERROR_FREQUENCY_OUT_OF_RANGE",
		2: "ERROR_FREQUENCY_NOT_ALIGNED",
		3: "ERROR_FREQUENCY_START_GREATER_THAN_END",
	}
	ErrorCodeE_value = map[string]int32{
		"SUCCESS":                                0,
		"ERROR_FREQUENCY_OUT_OF_RANGE":           1,
		"ERROR_FREQUENCY_NOT_ALIGNED":            2,
		"ERROR_FREQUENCY_START_GREATER_THAN_END": 3,
	}
)

func (x ErrorCodeE) Enum() *ErrorCodeE {
	p := new(ErrorCodeE)
	*p = x
	return p
}

func (x ErrorCodeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCodeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[21].Descriptor()
}

func (ErrorCodeE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[21]
}

func (x ErrorCodeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ErrorCodeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ErrorCodeE(num)
	return nil
}

// Deprecated: Use ErrorCodeE.Descriptor instead.
func (ErrorCodeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{21}
}

type AmplifierTypeE int32

const (
	AmplifierTypeE_AMP_TYPE_OTHER        AmplifierTypeE = 1
	AmplifierTypeE_AMP_TYPE_UNKNOWN      AmplifierTypeE = 2
	AmplifierTypeE_AMP_TYPE_MULTIPORT    AmplifierTypeE = 3
	AmplifierTypeE_AMP_TYPE_LINEEXTENDER AmplifierTypeE = 4
	AmplifierTypeE_AMP_TYPE_BOOSTER      AmplifierTypeE = 5
	AmplifierTypeE_AMP_TYPE_COMPACT      AmplifierTypeE = 6
)

// Enum value maps for AmplifierTypeE.
var (
	AmplifierTypeE_name = map[int32]string{
		1: "AMP_TYPE_OTHER",
		2: "AMP_TYPE_UNKNOWN",
		3: "AMP_TYPE_MULTIPORT",
		4: "AMP_TYPE_LINEEXTENDER",
		5: "AMP_TYPE_BOOSTER",
		6: "AMP_TYPE_COMPACT",
	}
	AmplifierTypeE_value = map[string]int32{
		"AMP_TYPE_OTHER":        1,
		"AMP_TYPE_UNKNOWN":      2,
		"AMP_TYPE_MULTIPORT":    3,
		"AMP_TYPE_LINEEXTENDER": 4,
		"AMP_TYPE_BOOSTER":      5,
		"AMP_TYPE_COMPACT":      6,
	}
)

func (x AmplifierTypeE) Enum() *AmplifierTypeE {
	p := new(AmplifierTypeE)
	*p = x
	return p
}

func (x AmplifierTypeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AmplifierTypeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[22].Descriptor()
}

func (AmplifierTypeE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[22]
}

func (x AmplifierTypeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AmplifierTypeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AmplifierTypeE(num)
	return nil
}

// Deprecated: Use AmplifierTypeE.Descriptor instead.
func (AmplifierTypeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{22}
}

type PwrSupplyRedundancyModeE int32

const (
	PwrSupplyRedundancyModeE_PS_REDUNDANCY_MODE_OTHER             PwrSupplyRedundancyModeE = 1
	PwrSupplyRedundancyModeE_PS_REDUNDANCY_MODE_UNKNOWN           PwrSupplyRedundancyModeE = 2
	PwrSupplyRedundancyModeE_PS_REDUNDANCY_MODE_LOADSHARING       PwrSupplyRedundancyModeE = 3
	PwrSupplyRedundancyModeE_PS_REDUNDANCY_MODE_SWITCHEDREDUNDANT PwrSupplyRedundancyModeE = 4
)

// Enum value maps for PwrSupplyRedundancyModeE.
var (
	PwrSupplyRedundancyModeE_name = map[int32]string{
		1: "PS_REDUNDANCY_MODE_OTHER",
		2: "PS_REDUNDANCY_MODE_UNKNOWN",
		3: "PS_REDUNDANCY_MODE_LOADSHARING",
		4: "PS_REDUNDANCY_MODE_SWITCHEDREDUNDANT",
	}
	PwrSupplyRedundancyModeE_value = map[string]int32{
		"PS_REDUNDANCY_MODE_OTHER":             1,
		"PS_REDUNDANCY_MODE_UNKNOWN":           2,
		"PS_REDUNDANCY_MODE_LOADSHARING":       3,
		"PS_REDUNDANCY_MODE_SWITCHEDREDUNDANT": 4,
	}
)

func (x PwrSupplyRedundancyModeE) Enum() *PwrSupplyRedundancyModeE {
	p := new(PwrSupplyRedundancyModeE)
	*p = x
	return p
}

func (x PwrSupplyRedundancyModeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PwrSupplyRedundancyModeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[23].Descriptor()
}

func (PwrSupplyRedundancyModeE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[23]
}

func (x PwrSupplyRedundancyModeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PwrSupplyRedundancyModeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PwrSupplyRedundancyModeE(num)
	return nil
}

// Deprecated: Use PwrSupplyRedundancyModeE.Descriptor instead.
func (PwrSupplyRedundancyModeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{23}
}

type ResetTypeE int32

const (
	ResetTypeE_SOFT_RESET    ResetTypeE = 1
	ResetTypeE_HARD_RESET    ResetTypeE = 2
	ResetTypeE_NV_RESET      ResetTypeE = 4
	ResetTypeE_FACTORY_RESET ResetTypeE = 8
)

// Enum value maps for ResetTypeE.
var (
	ResetTypeE_name = map[int32]string{
		1: "SOFT_RESET",
		2: "HARD_RESET",
		4: "NV_RESET",
		8: "FACTORY_RESET",
	}
	ResetTypeE_value = map[string]int32{
		"SOFT_RESET":    1,
		"HARD_RESET":    2,
		"NV_RESET":      4,
		"FACTORY_RESET": 8,
	}
)

func (x ResetTypeE) Enum() *ResetTypeE {
	p := new(ResetTypeE)
	*p = x
	return p
}

func (x ResetTypeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResetTypeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[24].Descriptor()
}

func (ResetTypeE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[24]
}

func (x ResetTypeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ResetTypeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ResetTypeE(num)
	return nil
}

// Deprecated: Use ResetTypeE.Descriptor instead.
func (ResetTypeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{24}
}

type EvPriorityE int32

const (
	EvPriorityE_EV_EMERGENCY EvPriorityE = 1
	EvPriorityE_EV_ALERT     EvPriorityE = 2
	EvPriorityE_EV_CRITICAL  EvPriorityE = 3
	EvPriorityE_EV_ERROR     EvPriorityE = 4
	EvPriorityE_EV_WARNING   EvPriorityE = 5
	EvPriorityE_EV_NOTICE    EvPriorityE = 6
	EvPriorityE_EV_INFO      EvPriorityE = 7
	EvPriorityE_EV_DEBUG     EvPriorityE = 8
)

// Enum value maps for EvPriorityE.
var (
	EvPriorityE_name = map[int32]string{
		1: "EV_EMERGENCY",
		2: "EV_ALERT",
		3: "EV_CRITICAL",
		4: "EV_ERROR",
		5: "EV_WARNING",
		6: "EV_NOTICE",
		7: "EV_INFO",
		8: "EV_DEBUG",
	}
	EvPriorityE_value = map[string]int32{
		"EV_EMERGENCY": 1,
		"EV_ALERT":     2,
		"EV_CRITICAL":  3,
		"EV_ERROR":     4,
		"EV_WARNING":   5,
		"EV_NOTICE":    6,
		"EV_INFO":      7,
		"EV_DEBUG":     8,
	}
)

func (x EvPriorityE) Enum() *EvPriorityE {
	p := new(EvPriorityE)
	*p = x
	return p
}

func (x EvPriorityE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvPriorityE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[25].Descriptor()
}

func (EvPriorityE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[25]
}

func (x EvPriorityE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EvPriorityE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EvPriorityE(num)
	return nil
}

// Deprecated: Use EvPriorityE.Descriptor instead.
func (EvPriorityE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{25}
}

type AnalogOutRead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idx           *int32                 `protobuf:"varint,1,opt,name=idx" json:"idx,omitempty"`
	Value         *uint32                `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Result        *int32                 `protobuf:"zigzag32,3,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalogOutRead) Reset() {
	*x = AnalogOutRead{}
	mi := &file_amps_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalogOutRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalogOutRead) ProtoMessage() {}

func (x *AnalogOutRead) ProtoReflect() protoreflect.Message {
	mi := &file_amps_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalogOutRead.ProtoReflect.Descriptor instead.
func (*AnalogOutRead) Descriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{0}
}

func (x *AnalogOutRead) GetIdx() int32 {
	if x != nil && x.Idx != nil {
		return *x.Idx
	}
	return 0
}

func (x *AnalogOutRead) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *AnalogOutRead) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type AnalogOutWrite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idx           *int32                 `protobuf:"varint,1,opt,name=idx" json:"idx,omitempty"`
	Value         *uint32                `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Result        *int32                 `protobuf:"zigzag32,3,opt,name=result" json:"result,omitempty"`
	SaveToNvm     *bool                  `protobuf:"varint,4,opt,name=save_to_nvm,json=saveToNvm,def=1" json:"save_to_nvm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for AnalogOutWrite fields.
const (
	Default_AnalogOutWrite_SaveToNvm = bool(true)
)

func (x *AnalogOutWrite) Reset() {
	*x = AnalogOutWrite{}
	mi := &file_amps_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalogOutWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalogOutWrite) ProtoMessage() {}

func (x *AnalogOutWrite) ProtoReflect() protoreflect.Message {
	mi := &file_amps_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalogOutWrite.ProtoReflect.Descriptor instead.
func (*AnalogOutWrite) Descriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{1}
}

func (x *AnalogOutWrite) GetIdx() int32 {
	if x != nil && x.Idx != nil {
		return *x.Idx
	}
	return 0
}

func (x *AnalogOutWrite) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *AnalogOutWrite) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

func (x *AnalogOutWrite) GetSaveToNvm() bool {
	if x != nil && x.SaveToNvm != nil {
		return *x.SaveToNvm
	}
	return Default_AnalogOutWrite_SaveToNvm
}

type AnalogInRead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idx           *int32                 `protobuf:"varint,1,opt,name=idx" json:"idx,omitempty"`
	Value         *int32                 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Result        *int32                 `protobuf:"zigzag32,3,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalogInRead) Reset() {
	*x = AnalogInRead{}
	mi := &file_amps_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalogInRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalogInRead) ProtoMessage() {}

func (x *AnalogInRead) ProtoReflect() protoreflect.Message {
	mi := &file_amps_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalogInRead.ProtoReflect.Descriptor instead.
func (*AnalogInRead) Descriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{2}
}

func (x *AnalogInRead) GetIdx() int32 {
	if x != nil && x.Idx != nil {
		return *x.Idx
	}
	return 0
}

func (x *AnalogInRead) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *AnalogInRead) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type FragmentInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FragmentIndex  *uint32                `protobuf:"varint,1,opt,name=fragment_index,json=fragmentIndex" json:"fragment_index,omitempty"`
	TotalFragments *uint32                `protobuf:"varint,2,opt,name=total_fragments,json=totalFragments" json:"total_fragments,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FragmentInfo) Reset() {
	*x = FragmentInfo{}
	mi := &file_amps_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FragmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FragmentInfo) ProtoMessage() {}

func (x *FragmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_amps_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FragmentInfo.ProtoReflect.Descriptor instead.
func (*FragmentInfo) Descriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{3}
}

func (x *FragmentInfo) GetFragmentIndex() uint32 {
	if x != nil && x.FragmentIndex != nil {
		return *x.FragmentIndex
	}
	return 0
}

func (x *FragmentInfo) GetTotalFragments() uint32 {
	if x != nil && x.TotalFragments != nil {
		return *x.TotalFragments
	}
	return 0
}

var File_amps_common_proto protoreflect.FileDescriptor

const file_amps_common_proto_rawDesc = "" +
	"\n" +
	"\x11amps/common.proto\x12\bscte.amp\"O\n" +
	"\rAnalogOutRead\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\x05R\x03idx\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value\x12\x16\n" +
	"\x06result\x18\x03 \x01(\x11R\x06result\"v\n" +
	"\x0eAnalogOutWrite\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\x05R\x03idx\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value\x12\x16\n" +
	"\x06result\x18\x03 \x01(\x11R\x06result\x12$\n" +
	"\vsave_to_nvm\x18\x04 \x01(\b:\x04trueR\tsaveToNvm\"N\n" +
	"\fAnalogInRead\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\x05R\x03idx\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x12\x16\n" +
	"\x06result\x18\x03 \x01(\x11R\x06result\"^\n" +
	"\fFragmentInfo\x12%\n" +
	"\x0efragment_index\x18\x01 \x01(\rR\rfragmentIndex\x12'\n" +
	"\x0ftotal_fragments\x18\x02 \x01(\rR\x0etotalFragments*/\n" +
	"\x0fpath_selector_e\x12\x0e\n" +
	"\n" +
	"DOWNSTREAM\x10\x01\x12\f\n" +
	"\bUPSTREAM\x10\x02*\xbb\x01\n" +
	"\x13auto_alignment_op_e\x12\x10\n" +
	"\bPRE_TUNE\x10\x01\x1a\x02\b\x01\x12\x13\n" +
	"\vCOARSE_TUNE\x10\x02\x1a\x02\b\x01\x12\x11\n" +
	"\tFINE_TUNE\x10\x03\x1a\x02\b\x01\x12\r\n" +
	"\tFULL_TUNE\x10\x04\x12\b\n" +
	"\x04SAVE\x10\x05\x12\n" +
	"\n" +
	"\x06REVERT\x10\x06\x12\f\n" +
	"\bCSM_CALC\x10\a\x12\r\n" +
	"\tRMSE_CALC\x10\b\x12\x11\n" +
	"\tRSME_CALC\x10\b\x1a\x02\b\x01\x12\x11\n" +
	"\rSAVE_COMPLETE\x10\t\x1a\x02\x10\x01*M\n" +
	"\x17auto_alignment_status_e\x12\b\n" +
	"\x04IDLE\x10\x01\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x02\x12\f\n" +
	"\bCOMPLETE\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04**\n" +
	"\x12enclosure_status_e\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x01\x12\b\n" +
	"\x04OPEN\x10\x02*o\n" +
	"\x0fds_gain_stage_e\x12\x11\n" +
	"\rDS_INPUT_ATTN\x10\x01\x12\x16\n" +
	"\x12DS_INTERSTAGE_ATTN\x10\x02\x12\x19\n" +
	"\x15DS_OVERLOAD_PROT_ATTN\x10\x03\x12\x16\n" +
	"\x12DS_CUMULATIVE_ATTN\x10\x04*^\n" +
	"\rds_eq_stage_e\x12\x0f\n" +
	"\vDS_INPUT_EQ\x10\x01\x12\x14\n" +
	"\x10DS_INTERSTAGE_EQ\x10\x02\x12\x10\n" +
	"\fDS_OUTPUT_EQ\x10\x03\x12\x14\n" +
	"\x10DS_CUMULATIVE_EQ\x10\x04*/\n" +
	"\fagc_config_e\x12\v\n" +
	"\aTHERMAL\x10\x01\x12\n" +
	"\n" +
	"\x06MANUAL\x10\x02\x12\x06\n" +
	"\x02ON\x10\x03*:\n" +
	"\x0fus_gain_stage_e\x12\f\n" +
	"\bUS_ATTN1\x10\x01\x12\f\n" +
	"\bUS_ATTN2\x10\x02\x12\v\n" +
	"\aUS_CUMU\x10\x03*+\n" +
	"\rus_eq_stage_e\x12\n" +
	"\n" +
	"\x06US_EQ1\x10\x01\x12\x0e\n" +
	"\n" +
	"US_CUMU_EQ\x10\x02*@\n" +
	"\x17ingress_switch_config_e\x12\b\n" +
	"\x04SW_0\x10\x00\x12\f\n" +
	"\bSW_NEG_6\x10\x01\x12\r\n" +
	"\tSW_NEG_50\x10\x02*H\n" +
	"\x0ftest_point_id_e\x12\f\n" +
	"\bINPUT_TP\x10\x01\x12\r\n" +
	"\tOUTPUT_TP\x10\x02\x12\v\n" +
	"\aAUX1_TP\x10\x03\x12\v\n" +
	"\aAUX2_TP\x10\x04*'\n" +
	"\x13test_point_config_e\x12\a\n" +
	"\x03FWD\x10\x01\x12\a\n" +
	"\x03REV\x10\x02*G\n" +
	"\x14spectrum_scan_data_e\x12\x19\n" +
	"\x15SCAN_AUTO_CACHED_DATA\x10\x00\x12\x14\n" +
	"\x10SCAN_MANUAL_DATA\x10\x01*e\n" +
	"\x16spectrum_scan_status_e\x12\x17\n" +
	"\x13SCAN_STATUS_INVALID\x10\x00\x12\x1b\n" +
	"\x17SCAN_STATUS_IN_PROGRESS\x10\x01\x12\x15\n" +
	"\x11SCAN_STATUS_VALID\x10\x02*:\n" +
	"\x10bandwidth_mode_e\x12\x12\n" +
	"\x0eBW_MODE_1P2GHZ\x10\x00\x12\x12\n" +
	"\x0eBW_MODE_1P8GHZ\x10\x01*\x9c\x01\n" +
	"\asplit_e\x12\x0f\n" +
	"\vSPLIT_42_54\x10\x00\x12\x0f\n" +
	"\vSPLIT_65_85\x10\x01\x12\x10\n" +
	"\fSPLIT_85_108\x10\x02\x12\x11\n" +
	"\rSPLIT_204_258\x10\x03\x12\x11\n" +
	"\rSPLIT_300_372\x10\x04\x12\x11\n" +
	"\rSPLIT_396_492\x10\x05\x12\x11\n" +
	"\rSPLIT_492_606\x10\x06\x12\x11\n" +
	"\rSPLIT_684_834\x10\a*\x91\x01\n" +
	"\rhpft_module_e\x12\x17\n" +
	"\x13HPFT_MODULE_MISSING\x10\x00\x12\x13\n" +
	"\x0fHPFT_MODULE_108\x10\x01\x12\x13\n" +
	"\x0fHPFT_MODULE_258\x10\x02\x12\x13\n" +
	"\x0fHPFT_MODULE_492\x10\x03\x12\x13\n" +
	"\x0fHPFT_MODULE_606\x10\x04\x12\x13\n" +
	"\x0fHPFT_MODULE_834\x10\x05*\xe2\x01\n" +
	"\rlpft_module_e\x12\x17\n" +
	"\x13LPFT_MODULE_MISSING\x10\x00\x12\x12\n" +
	"\x0eLPFT_MODULE_42\x10\x01\x12\x12\n" +
	"\x0eLPFT_MODULE_65\x10\x02\x12\x12\n" +
	"\x0eLPFT_MODULE_85\x10\x03\x12\x13\n" +
	"\x0fLPFT_MODULE_204\x10\x04\x12\x13\n" +
	"\x0fLPFT_MODULE_300\x10\x05\x12\x13\n" +
	"\x0fLPFT_MODULE_396\x10\x06\x12\x13\n" +
	"\x0fLPFT_MODULE_492\x10\a\x12\x13\n" +
	"\x0fLPFT_MODULE_588\x10\b\x12\x13\n" +
	"\x0fLPFT_MODULE_684\x10\t*_\n" +
	"\x0finv_eq_module_e\x12\x19\n" +
	"\x15INV_EQ_MODULE_MISSING\x10\x00\x12\x18\n" +
	"\x14INV_EQ_MODULE_JUMPER\x10\x01\x12\x17\n" +
	"\x13INV_EQ_MODULE_300FT\x10\x02*#\n" +
	"\aannex_e\x12\v\n" +
	"\aANNEX_A\x10\x00\x12\v\n" +
	"\aANNEX_B\x10\x01*M\n" +
	"\x15ingress_port_select_e\x12\x10\n" +
	"\fINGRESS_MAIN\x10\x00\x12\x10\n" +
	"\fINGRESS_AUX1\x10\x01\x12\x10\n" +
	"\fINGRESS_AUX2\x10\x02*\x8a\x01\n" +
	"\ferror_code_e\x12\v\n" +
	"\aSUCCESS\x10\x00\x12 \n" +
	"\x1cERROR_FREQUENCY_OUT_OF_RANGE\x10\x01\x12\x1f\n" +
	"\x1bERROR_FREQUENCY_NOT_ALIGNED\x10\x02\x12*\n" +
	"&ERROR_FREQUENCY_START_GREATER_THAN_END\x10\x03*\x9b\x01\n" +
	"\x10amplifier_type_e\x12\x12\n" +
	"\x0eAMP_TYPE_OTHER\x10\x01\x12\x14\n" +
	"\x10AMP_TYPE_UNKNOWN\x10\x02\x12\x16\n" +
	"\x12AMP_TYPE_MULTIPORT\x10\x03\x12\x19\n" +
	"\x15AMP_TYPE_LINEEXTENDER\x10\x04\x12\x14\n" +
	"\x10AMP_TYPE_BOOSTER\x10\x05\x12\x14\n" +
	"\x10AMP_TYPE_COMPACT\x10\x06*\xaa\x01\n" +
	"\x1cpwr_supply_redundancy_mode_e\x12\x1c\n" +
	"\x18PS_REDUNDANCY_MODE_OTHER\x10\x01\x12\x1e\n" +
	"\x1aPS_REDUNDANCY_MODE_UNKNOWN\x10\x02\x12\"\n" +
	"\x1ePS_REDUNDANCY_MODE_LOADSHARING\x10\x03\x12(\n" +
	"$PS_REDUNDANCY_MODE_SWITCHEDREDUNDANT\x10\x04*O\n" +
	"\freset_type_e\x12\x0e\n" +
	"\n" +
	"SOFT_RESET\x10\x01\x12\x0e\n" +
	"\n" +
	"HARD_RESET\x10\x02\x12\f\n" +
	"\bNV_RESET\x10\x04\x12\x11\n" +
	"\rFACTORY_RESET\x10\b*\x88\x01\n" +
	"\rev_priority_e\x12\x10\n" +
	"\fEV_EMERGENCY\x10\x01\x12\f\n" +
	"\bEV_ALERT\x10\x02\x12\x0f\n" +
	"\vEV_CRITICAL\x10\x03\x12\f\n" +
	"\bEV_ERROR\x10\x04\x12\x0e\n" +
	"\n" +
	"EV_WARNING\x10\x05\x12\r\n" +
	"\tEV_NOTICE\x10\x06\x12\v\n" +
	"\aEV_INFO\x10\a\x12\f\n" +
	"\bEV_DEBUG\x10\bB,Z*github.com/enshure/scte-go/amps_go;scteamp"

var (
	file_amps_common_proto_rawDescOnce sync.Once
	file_amps_common_proto_rawDescData []byte
)

func file_amps_common_proto_rawDescGZIP() []byte {
	file_amps_common_proto_rawDescOnce.Do(func() {
		file_amps_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amps_common_proto_rawDesc), len(file_amps_common_proto_rawDesc)))
	})
	return file_amps_common_proto_rawDescData
}

var file_amps_common_proto_enumTypes = make([]protoimpl.EnumInfo, 26)
var file_amps_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_amps_common_proto_goTypes = []any{
	(PathSelectorE)(0),            // 0: scte.amp.path_selector_e
	(AutoAlignmentOpE)(0),         // 1: scte.amp.auto_alignment_op_e
	(AutoAlignmentStatusE)(0),     // 2: scte.amp.auto_alignment_status_e
	(EnclosureStatusE)(0),         // 3: scte.amp.enclosure_status_e
	(DsGainStageE)(0),             // 4: scte.amp.ds_gain_stage_e
	(DsEqStageE)(0),               // 5: scte.amp.ds_eq_stage_e
	(AgcConfigE)(0),               // 6: scte.amp.agc_config_e
	(UsGainStageE)(0),             // 7: scte.amp.us_gain_stage_e
	(UsEqStageE)(0),               // 8: scte.amp.us_eq_stage_e
	(IngressSwitchConfigE)(0),     // 9: scte.amp.ingress_switch_config_e
	(TestPointIdE)(0),             // 10: scte.amp.test_point_id_e
	(TestPointConfigE)(0),         // 11: scte.amp.test_point_config_e
	(SpectrumScanDataE)(0),        // 12: scte.amp.spectrum_scan_data_e
	(SpectrumScanStatusE)(0),      // 13: scte.amp.spectrum_scan_status_e
	(BandwidthModeE)(0),           // 14: scte.amp.bandwidth_mode_e
	(SplitE)(0),                   // 15: scte.amp.split_e
	(HpftModuleE)(0),              // 16: scte.amp.hpft_module_e
	(LpftModuleE)(0),              // 17: scte.amp.lpft_module_e
	(InvEqModuleE)(0),             // 18: scte.amp.inv_eq_module_e
	(AnnexE)(0),                   // 19: scte.amp.annex_e
	(IngressPortSelectE)(0),       // 20: scte.amp.ingress_port_select_e
	(ErrorCodeE)(0),               // 21: scte.amp.error_code_e
	(AmplifierTypeE)(0),           // 22: scte.amp.amplifier_type_e
	(PwrSupplyRedundancyModeE)(0), // 23: scte.amp.pwr_supply_redundancy_mode_e
	(ResetTypeE)(0),               // 24: scte.amp.reset_type_e
	(EvPriorityE)(0),              // 25: scte.amp.ev_priority_e
	(*AnalogOutRead)(nil),         // 26: scte.amp.AnalogOutRead
	(*AnalogOutWrite)(nil),        // 27: scte.amp.AnalogOutWrite
	(*AnalogInRead)(nil),          // 28: scte.amp.AnalogInRead
	(*FragmentInfo)(nil),          // 29: scte.amp.FragmentInfo
}
var file_amps_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_amps_common_proto_init() }
func file_amps_common_proto_init() {
	if File_amps_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amps_common_proto_rawDesc), len(file_amps_common_proto_rawDesc)),
			NumEnums:      26,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_amps_common_proto_goTypes,
		DependencyIndexes: file_amps_common_proto_depIdxs,
		EnumInfos:         file_amps_common_proto_enumTypes,
		MessageInfos:      file_amps_common_proto_msgTypes,
	}.Build()
	File_amps_common_proto = out.File
	file_amps_common_proto_goTypes = nil
	file_amps_common_proto_depIdxs = nil
}
