// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: amps/common.proto

package scteamp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PathSelectorE int32

const (
	PathSelectorE_PATH_SELECTOR_UNKNOWN PathSelectorE = 0
	PathSelectorE_DOWNSTREAM            PathSelectorE = 1
	PathSelectorE_UPSTREAM              PathSelectorE = 2
)

// Enum value maps for PathSelectorE.
var (
	PathSelectorE_name = map[int32]string{
		0: "PATH_SELECTOR_UNKNOWN",
		1: "DOWNSTREAM",
		2: "UPSTREAM",
	}
	PathSelectorE_value = map[string]int32{
		"PATH_SELECTOR_UNKNOWN": 0,
		"DOWNSTREAM":            1,
		"UPSTREAM":              2,
	}
)

func (x PathSelectorE) Enum() *PathSelectorE {
	p := new(PathSelectorE)
	*p = x
	return p
}

func (x PathSelectorE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PathSelectorE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[0].Descriptor()
}

func (PathSelectorE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[0]
}

func (x PathSelectorE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PathSelectorE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PathSelectorE(num)
	return nil
}

// Deprecated: Use PathSelectorE.Descriptor instead.
func (PathSelectorE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{0}
}

type RfPortIndexE int32

const (
	RfPortIndexE_RF_PORT_INDEX_1 RfPortIndexE = 1   //Input DS RF port
	RfPortIndexE_RF_PORT_INDEX_2 RfPortIndexE = 2   //Main DS output
	RfPortIndexE_RF_PORT_INDEX_3 RfPortIndexE = 3   //Aux1 DS output
	RfPortIndexE_RF_PORT_INDEX_4 RfPortIndexE = 4   //Aux2 DS output
	RfPortIndexE_RF_PORT_ALL     RfPortIndexE = 255 //Extend SCTE-283 info model to include support for all ports.
)

// Enum value maps for RfPortIndexE.
var (
	RfPortIndexE_name = map[int32]string{
		1:   "RF_PORT_INDEX_1",
		2:   "RF_PORT_INDEX_2",
		3:   "RF_PORT_INDEX_3",
		4:   "RF_PORT_INDEX_4",
		255: "RF_PORT_ALL",
	}
	RfPortIndexE_value = map[string]int32{
		"RF_PORT_INDEX_1": 1,
		"RF_PORT_INDEX_2": 2,
		"RF_PORT_INDEX_3": 3,
		"RF_PORT_INDEX_4": 4,
		"RF_PORT_ALL":     255,
	}
)

func (x RfPortIndexE) Enum() *RfPortIndexE {
	p := new(RfPortIndexE)
	*p = x
	return p
}

func (x RfPortIndexE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RfPortIndexE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[1].Descriptor()
}

func (RfPortIndexE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[1]
}

func (x RfPortIndexE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RfPortIndexE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RfPortIndexE(num)
	return nil
}

// Deprecated: Use RfPortIndexE.Descriptor instead.
func (RfPortIndexE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{1}
}

type AlignmentOpE int32

const (
	AlignmentOpE_UNSPECIFIED   AlignmentOpE = 0
	AlignmentOpE_PRE_TUNE      AlignmentOpE = 1
	AlignmentOpE_COARSE_TUNE   AlignmentOpE = 2
	AlignmentOpE_FINE_TUNE     AlignmentOpE = 3
	AlignmentOpE_FULL_TUNE     AlignmentOpE = 4
	AlignmentOpE_SAVE          AlignmentOpE = 5
	AlignmentOpE_REVERT        AlignmentOpE = 6
	AlignmentOpE_CSM_CALC      AlignmentOpE = 7
	AlignmentOpE_RMSE_CALC     AlignmentOpE = 8
	AlignmentOpE_SAVE_COMPLETE AlignmentOpE = 9
)

// Enum value maps for AlignmentOpE.
var (
	AlignmentOpE_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "PRE_TUNE",
		2: "COARSE_TUNE",
		3: "FINE_TUNE",
		4: "FULL_TUNE",
		5: "SAVE",
		6: "REVERT",
		7: "CSM_CALC",
		8: "RMSE_CALC",
		9: "SAVE_COMPLETE",
	}
	AlignmentOpE_value = map[string]int32{
		"UNSPECIFIED":   0,
		"PRE_TUNE":      1,
		"COARSE_TUNE":   2,
		"FINE_TUNE":     3,
		"FULL_TUNE":     4,
		"SAVE":          5,
		"REVERT":        6,
		"CSM_CALC":      7,
		"RMSE_CALC":     8,
		"SAVE_COMPLETE": 9,
	}
)

func (x AlignmentOpE) Enum() *AlignmentOpE {
	p := new(AlignmentOpE)
	*p = x
	return p
}

func (x AlignmentOpE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlignmentOpE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[2].Descriptor()
}

func (AlignmentOpE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[2]
}

func (x AlignmentOpE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AlignmentOpE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AlignmentOpE(num)
	return nil
}

// Deprecated: Use AlignmentOpE.Descriptor instead.
func (AlignmentOpE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{2}
}

type AlignmentStatusE int32

const (
	AlignmentStatusE_IDLE        AlignmentStatusE = 1
	AlignmentStatusE_IN_PROGRESS AlignmentStatusE = 2
	AlignmentStatusE_COMPLETE    AlignmentStatusE = 3
	AlignmentStatusE_ERROR       AlignmentStatusE = 4
)

// Enum value maps for AlignmentStatusE.
var (
	AlignmentStatusE_name = map[int32]string{
		1: "IDLE",
		2: "IN_PROGRESS",
		3: "COMPLETE",
		4: "ERROR",
	}
	AlignmentStatusE_value = map[string]int32{
		"IDLE":        1,
		"IN_PROGRESS": 2,
		"COMPLETE":    3,
		"ERROR":       4,
	}
)

func (x AlignmentStatusE) Enum() *AlignmentStatusE {
	p := new(AlignmentStatusE)
	*p = x
	return p
}

func (x AlignmentStatusE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlignmentStatusE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[3].Descriptor()
}

func (AlignmentStatusE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[3]
}

func (x AlignmentStatusE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AlignmentStatusE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AlignmentStatusE(num)
	return nil
}

// Deprecated: Use AlignmentStatusE.Descriptor instead.
func (AlignmentStatusE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{3}
}

type RfSpectrumCaptureTypeE int32

const (
	RfSpectrumCaptureTypeE_PORT1_UPSTREAM      RfSpectrumCaptureTypeE = 1
	RfSpectrumCaptureTypeE_PORT1_DOWNSTREAM    RfSpectrumCaptureTypeE = 2
	RfSpectrumCaptureTypeE_PORT2_UPSTREAM      RfSpectrumCaptureTypeE = 4
	RfSpectrumCaptureTypeE_PORT2_DOWNSTREAM    RfSpectrumCaptureTypeE = 8
	RfSpectrumCaptureTypeE_PORT3_UPSTREAM      RfSpectrumCaptureTypeE = 16
	RfSpectrumCaptureTypeE_PORT3_DOWNSTREAM    RfSpectrumCaptureTypeE = 32
	RfSpectrumCaptureTypeE_PORT4_UPSTREAM      RfSpectrumCaptureTypeE = 64
	RfSpectrumCaptureTypeE_PORT4_DOWNSTREAM    RfSpectrumCaptureTypeE = 128
	RfSpectrumCaptureTypeE_PORT_UPSTREAM_ALL   RfSpectrumCaptureTypeE = 256 //Extend SCTE-283 info model to include support for all upstream ports.
	RfSpectrumCaptureTypeE_PORT_DOWNSTREAM_ALL RfSpectrumCaptureTypeE = 512 //Extend SCTE-283 info model to include support for all upstream ports.
)

// Enum value maps for RfSpectrumCaptureTypeE.
var (
	RfSpectrumCaptureTypeE_name = map[int32]string{
		1:   "PORT1_UPSTREAM",
		2:   "PORT1_DOWNSTREAM",
		4:   "PORT2_UPSTREAM",
		8:   "PORT2_DOWNSTREAM",
		16:  "PORT3_UPSTREAM",
		32:  "PORT3_DOWNSTREAM",
		64:  "PORT4_UPSTREAM",
		128: "PORT4_DOWNSTREAM",
		256: "PORT_UPSTREAM_ALL",
		512: "PORT_DOWNSTREAM_ALL",
	}
	RfSpectrumCaptureTypeE_value = map[string]int32{
		"PORT1_UPSTREAM":      1,
		"PORT1_DOWNSTREAM":    2,
		"PORT2_UPSTREAM":      4,
		"PORT2_DOWNSTREAM":    8,
		"PORT3_UPSTREAM":      16,
		"PORT3_DOWNSTREAM":    32,
		"PORT4_UPSTREAM":      64,
		"PORT4_DOWNSTREAM":    128,
		"PORT_UPSTREAM_ALL":   256,
		"PORT_DOWNSTREAM_ALL": 512,
	}
)

func (x RfSpectrumCaptureTypeE) Enum() *RfSpectrumCaptureTypeE {
	p := new(RfSpectrumCaptureTypeE)
	*p = x
	return p
}

func (x RfSpectrumCaptureTypeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RfSpectrumCaptureTypeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[4].Descriptor()
}

func (RfSpectrumCaptureTypeE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[4]
}

func (x RfSpectrumCaptureTypeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RfSpectrumCaptureTypeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RfSpectrumCaptureTypeE(num)
	return nil
}

// Deprecated: Use RfSpectrumCaptureTypeE.Descriptor instead.
func (RfSpectrumCaptureTypeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{4}
}

type AlignmentTypeE int32

const (
	AlignmentTypeE_ALIGNMENT_TYPE_DS_AUTO   AlignmentTypeE = 1
	AlignmentTypeE_ALIGNMENT_TYPE_US_AUTO   AlignmentTypeE = 2
	AlignmentTypeE_ALIGNMENT_TYPE_DS_MANUAL AlignmentTypeE = 4
	AlignmentTypeE_ALIGNMENT_TYPE_US_MANUAL AlignmentTypeE = 8
)

// Enum value maps for AlignmentTypeE.
var (
	AlignmentTypeE_name = map[int32]string{
		1: "ALIGNMENT_TYPE_DS_AUTO",
		2: "ALIGNMENT_TYPE_US_AUTO",
		4: "ALIGNMENT_TYPE_DS_MANUAL",
		8: "ALIGNMENT_TYPE_US_MANUAL",
	}
	AlignmentTypeE_value = map[string]int32{
		"ALIGNMENT_TYPE_DS_AUTO":   1,
		"ALIGNMENT_TYPE_US_AUTO":   2,
		"ALIGNMENT_TYPE_DS_MANUAL": 4,
		"ALIGNMENT_TYPE_US_MANUAL": 8,
	}
)

func (x AlignmentTypeE) Enum() *AlignmentTypeE {
	p := new(AlignmentTypeE)
	*p = x
	return p
}

func (x AlignmentTypeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlignmentTypeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[5].Descriptor()
}

func (AlignmentTypeE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[5]
}

func (x AlignmentTypeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AlignmentTypeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AlignmentTypeE(num)
	return nil
}

// Deprecated: Use AlignmentTypeE.Descriptor instead.
func (AlignmentTypeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{5}
}

type RfLevelControlTypeE int32

const (
	RfLevelControlTypeE_RF_LEVEL_CONTROL_OTHER                        RfLevelControlTypeE = 0
	RfLevelControlTypeE_RF_LEVEL_CONTROL_UNKNOWN                      RfLevelControlTypeE = 1
	RfLevelControlTypeE_RF_LEVEL_CONTROL_QUASI_AGC                    RfLevelControlTypeE = 2
	RfLevelControlTypeE_RF_LEVEL_CONTROL_THERMAL_LEVEL_CONTROL        RfLevelControlTypeE = 3
	RfLevelControlTypeE_RF_LEVEL_CONTROL_THERMAL_LEVEL_CONTROL_SELECT RfLevelControlTypeE = 4
)

// Enum value maps for RfLevelControlTypeE.
var (
	RfLevelControlTypeE_name = map[int32]string{
		0: "RF_LEVEL_CONTROL_OTHER",
		1: "RF_LEVEL_CONTROL_UNKNOWN",
		2: "RF_LEVEL_CONTROL_QUASI_AGC",
		3: "RF_LEVEL_CONTROL_THERMAL_LEVEL_CONTROL",
		4: "RF_LEVEL_CONTROL_THERMAL_LEVEL_CONTROL_SELECT",
	}
	RfLevelControlTypeE_value = map[string]int32{
		"RF_LEVEL_CONTROL_OTHER":                        0,
		"RF_LEVEL_CONTROL_UNKNOWN":                      1,
		"RF_LEVEL_CONTROL_QUASI_AGC":                    2,
		"RF_LEVEL_CONTROL_THERMAL_LEVEL_CONTROL":        3,
		"RF_LEVEL_CONTROL_THERMAL_LEVEL_CONTROL_SELECT": 4,
	}
)

func (x RfLevelControlTypeE) Enum() *RfLevelControlTypeE {
	p := new(RfLevelControlTypeE)
	*p = x
	return p
}

func (x RfLevelControlTypeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RfLevelControlTypeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[6].Descriptor()
}

func (RfLevelControlTypeE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[6]
}

func (x RfLevelControlTypeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RfLevelControlTypeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RfLevelControlTypeE(num)
	return nil
}

// Deprecated: Use RfLevelControlTypeE.Descriptor instead.
func (RfLevelControlTypeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{6}
}

type StageTypeE int32

const (
	StageTypeE_STAGE_TYPE_OTHER      StageTypeE = 0
	StageTypeE_STAGE_TYPE_UNKNOWN    StageTypeE = 1
	StageTypeE_STAGE_TYPE_ATTENUATOR StageTypeE = 2
	StageTypeE_STAGE_TYPE_EQUALIZER  StageTypeE = 3
)

// Enum value maps for StageTypeE.
var (
	StageTypeE_name = map[int32]string{
		0: "STAGE_TYPE_OTHER",
		1: "STAGE_TYPE_UNKNOWN",
		2: "STAGE_TYPE_ATTENUATOR",
		3: "STAGE_TYPE_EQUALIZER",
	}
	StageTypeE_value = map[string]int32{
		"STAGE_TYPE_OTHER":      0,
		"STAGE_TYPE_UNKNOWN":    1,
		"STAGE_TYPE_ATTENUATOR": 2,
		"STAGE_TYPE_EQUALIZER":  3,
	}
)

func (x StageTypeE) Enum() *StageTypeE {
	p := new(StageTypeE)
	*p = x
	return p
}

func (x StageTypeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StageTypeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[7].Descriptor()
}

func (StageTypeE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[7]
}

func (x StageTypeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StageTypeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StageTypeE(num)
	return nil
}

// Deprecated: Use StageTypeE.Descriptor instead.
func (StageTypeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{7}
}

// *
// SCTE-283 has type constraints of 1-8 for number of stages
// Extend it to include cumulative stage index for vendors that can only configure cumulative attn/eq
type StageIndexE int32

const (
	StageIndexE_STAGE_INDEX1           StageIndexE = 1
	StageIndexE_STAGE_INDEX2           StageIndexE = 2
	StageIndexE_STAGE_INDEX3           StageIndexE = 3
	StageIndexE_STAGE_INDEX4           StageIndexE = 4
	StageIndexE_STAGE_INDEX5           StageIndexE = 5
	StageIndexE_STAGE_INDEX6           StageIndexE = 6
	StageIndexE_STAGE_INDEX7           StageIndexE = 7
	StageIndexE_STAGE_INDEX8           StageIndexE = 8
	StageIndexE_STAGE_INDEX_CUMULATIVE StageIndexE = 9
)

// Enum value maps for StageIndexE.
var (
	StageIndexE_name = map[int32]string{
		1: "STAGE_INDEX1",
		2: "STAGE_INDEX2",
		3: "STAGE_INDEX3",
		4: "STAGE_INDEX4",
		5: "STAGE_INDEX5",
		6: "STAGE_INDEX6",
		7: "STAGE_INDEX7",
		8: "STAGE_INDEX8",
		9: "STAGE_INDEX_CUMULATIVE",
	}
	StageIndexE_value = map[string]int32{
		"STAGE_INDEX1":           1,
		"STAGE_INDEX2":           2,
		"STAGE_INDEX3":           3,
		"STAGE_INDEX4":           4,
		"STAGE_INDEX5":           5,
		"STAGE_INDEX6":           6,
		"STAGE_INDEX7":           7,
		"STAGE_INDEX8":           8,
		"STAGE_INDEX_CUMULATIVE": 9,
	}
)

func (x StageIndexE) Enum() *StageIndexE {
	p := new(StageIndexE)
	*p = x
	return p
}

func (x StageIndexE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StageIndexE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[8].Descriptor()
}

func (StageIndexE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[8]
}

func (x StageIndexE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StageIndexE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StageIndexE(num)
	return nil
}

// Deprecated: Use StageIndexE.Descriptor instead.
func (StageIndexE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{8}
}

type StageLocationE int32

const (
	StageLocationE_STAGE_LOCATION_OTHER       StageLocationE = 0
	StageLocationE_STAGE_LOCATION_UNKNOWN     StageLocationE = 1
	StageLocationE_STAGE_LOCATION_INPUT       StageLocationE = 2
	StageLocationE_STAGE_LOCATION_INTER_STAGE StageLocationE = 3
	StageLocationE_STAGE_LOCATION_OUTPUT      StageLocationE = 4
	StageLocationE_STAGE_LOCATION_CUMULATIVE  StageLocationE = 5
)

// Enum value maps for StageLocationE.
var (
	StageLocationE_name = map[int32]string{
		0: "STAGE_LOCATION_OTHER",
		1: "STAGE_LOCATION_UNKNOWN",
		2: "STAGE_LOCATION_INPUT",
		3: "STAGE_LOCATION_INTER_STAGE",
		4: "STAGE_LOCATION_OUTPUT",
		5: "STAGE_LOCATION_CUMULATIVE",
	}
	StageLocationE_value = map[string]int32{
		"STAGE_LOCATION_OTHER":       0,
		"STAGE_LOCATION_UNKNOWN":     1,
		"STAGE_LOCATION_INPUT":       2,
		"STAGE_LOCATION_INTER_STAGE": 3,
		"STAGE_LOCATION_OUTPUT":      4,
		"STAGE_LOCATION_CUMULATIVE":  5,
	}
)

func (x StageLocationE) Enum() *StageLocationE {
	p := new(StageLocationE)
	*p = x
	return p
}

func (x StageLocationE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StageLocationE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[9].Descriptor()
}

func (StageLocationE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[9]
}

func (x StageLocationE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StageLocationE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StageLocationE(num)
	return nil
}

// Deprecated: Use StageLocationE.Descriptor instead.
func (StageLocationE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{9}
}

type EnclosureStatusE int32

const (
	EnclosureStatusE_CLOSED EnclosureStatusE = 1
	EnclosureStatusE_OPEN   EnclosureStatusE = 2
)

// Enum value maps for EnclosureStatusE.
var (
	EnclosureStatusE_name = map[int32]string{
		1: "CLOSED",
		2: "OPEN",
	}
	EnclosureStatusE_value = map[string]int32{
		"CLOSED": 1,
		"OPEN":   2,
	}
)

func (x EnclosureStatusE) Enum() *EnclosureStatusE {
	p := new(EnclosureStatusE)
	*p = x
	return p
}

func (x EnclosureStatusE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnclosureStatusE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[10].Descriptor()
}

func (EnclosureStatusE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[10]
}

func (x EnclosureStatusE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EnclosureStatusE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EnclosureStatusE(num)
	return nil
}

// Deprecated: Use EnclosureStatusE.Descriptor instead.
func (EnclosureStatusE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{10}
}

type AgcConfigE int32

const (
	AgcConfigE_THERMAL AgcConfigE = 1
	AgcConfigE_MANUAL  AgcConfigE = 2
	AgcConfigE_ON      AgcConfigE = 3
)

// Enum value maps for AgcConfigE.
var (
	AgcConfigE_name = map[int32]string{
		1: "THERMAL",
		2: "MANUAL",
		3: "ON",
	}
	AgcConfigE_value = map[string]int32{
		"THERMAL": 1,
		"MANUAL":  2,
		"ON":      3,
	}
)

func (x AgcConfigE) Enum() *AgcConfigE {
	p := new(AgcConfigE)
	*p = x
	return p
}

func (x AgcConfigE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgcConfigE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[11].Descriptor()
}

func (AgcConfigE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[11]
}

func (x AgcConfigE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AgcConfigE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AgcConfigE(num)
	return nil
}

// Deprecated: Use AgcConfigE.Descriptor instead.
func (AgcConfigE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{11}
}

type UsGainStageE int32

const (
	UsGainStageE_US_ATTN1 UsGainStageE = 1
	UsGainStageE_US_ATTN2 UsGainStageE = 2
	UsGainStageE_US_CUMU  UsGainStageE = 3
)

// Enum value maps for UsGainStageE.
var (
	UsGainStageE_name = map[int32]string{
		1: "US_ATTN1",
		2: "US_ATTN2",
		3: "US_CUMU",
	}
	UsGainStageE_value = map[string]int32{
		"US_ATTN1": 1,
		"US_ATTN2": 2,
		"US_CUMU":  3,
	}
)

func (x UsGainStageE) Enum() *UsGainStageE {
	p := new(UsGainStageE)
	*p = x
	return p
}

func (x UsGainStageE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UsGainStageE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[12].Descriptor()
}

func (UsGainStageE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[12]
}

func (x UsGainStageE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *UsGainStageE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = UsGainStageE(num)
	return nil
}

// Deprecated: Use UsGainStageE.Descriptor instead.
func (UsGainStageE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{12}
}

type UsEqStageE int32

const (
	UsEqStageE_US_EQ1     UsEqStageE = 1
	UsEqStageE_US_CUMU_EQ UsEqStageE = 2
)

// Enum value maps for UsEqStageE.
var (
	UsEqStageE_name = map[int32]string{
		1: "US_EQ1",
		2: "US_CUMU_EQ",
	}
	UsEqStageE_value = map[string]int32{
		"US_EQ1":     1,
		"US_CUMU_EQ": 2,
	}
)

func (x UsEqStageE) Enum() *UsEqStageE {
	p := new(UsEqStageE)
	*p = x
	return p
}

func (x UsEqStageE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UsEqStageE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[13].Descriptor()
}

func (UsEqStageE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[13]
}

func (x UsEqStageE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *UsEqStageE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = UsEqStageE(num)
	return nil
}

// Deprecated: Use UsEqStageE.Descriptor instead.
func (UsEqStageE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{13}
}

type IngressSwitchConfigE int32

const (
	IngressSwitchConfigE_SW_0      IngressSwitchConfigE = 0
	IngressSwitchConfigE_SW_NEG_6  IngressSwitchConfigE = 1
	IngressSwitchConfigE_SW_NEG_50 IngressSwitchConfigE = 2
)

// Enum value maps for IngressSwitchConfigE.
var (
	IngressSwitchConfigE_name = map[int32]string{
		0: "SW_0",
		1: "SW_NEG_6",
		2: "SW_NEG_50",
	}
	IngressSwitchConfigE_value = map[string]int32{
		"SW_0":      0,
		"SW_NEG_6":  1,
		"SW_NEG_50": 2,
	}
)

func (x IngressSwitchConfigE) Enum() *IngressSwitchConfigE {
	p := new(IngressSwitchConfigE)
	*p = x
	return p
}

func (x IngressSwitchConfigE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IngressSwitchConfigE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[14].Descriptor()
}

func (IngressSwitchConfigE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[14]
}

func (x IngressSwitchConfigE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *IngressSwitchConfigE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = IngressSwitchConfigE(num)
	return nil
}

// Deprecated: Use IngressSwitchConfigE.Descriptor instead.
func (IngressSwitchConfigE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{14}
}

type TestPointIdE int32

const (
	TestPointIdE_INPUT_TP  TestPointIdE = 1
	TestPointIdE_OUTPUT_TP TestPointIdE = 2
	TestPointIdE_AUX1_TP   TestPointIdE = 3
	TestPointIdE_AUX2_TP   TestPointIdE = 4
)

// Enum value maps for TestPointIdE.
var (
	TestPointIdE_name = map[int32]string{
		1: "INPUT_TP",
		2: "OUTPUT_TP",
		3: "AUX1_TP",
		4: "AUX2_TP",
	}
	TestPointIdE_value = map[string]int32{
		"INPUT_TP":  1,
		"OUTPUT_TP": 2,
		"AUX1_TP":   3,
		"AUX2_TP":   4,
	}
)

func (x TestPointIdE) Enum() *TestPointIdE {
	p := new(TestPointIdE)
	*p = x
	return p
}

func (x TestPointIdE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestPointIdE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[15].Descriptor()
}

func (TestPointIdE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[15]
}

func (x TestPointIdE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TestPointIdE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TestPointIdE(num)
	return nil
}

// Deprecated: Use TestPointIdE.Descriptor instead.
func (TestPointIdE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{15}
}

type TestPointConfigE int32

const (
	TestPointConfigE_FWD TestPointConfigE = 1
	TestPointConfigE_REV TestPointConfigE = 2
)

// Enum value maps for TestPointConfigE.
var (
	TestPointConfigE_name = map[int32]string{
		1: "FWD",
		2: "REV",
	}
	TestPointConfigE_value = map[string]int32{
		"FWD": 1,
		"REV": 2,
	}
)

func (x TestPointConfigE) Enum() *TestPointConfigE {
	p := new(TestPointConfigE)
	*p = x
	return p
}

func (x TestPointConfigE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestPointConfigE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[16].Descriptor()
}

func (TestPointConfigE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[16]
}

func (x TestPointConfigE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TestPointConfigE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TestPointConfigE(num)
	return nil
}

// Deprecated: Use TestPointConfigE.Descriptor instead.
func (TestPointConfigE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{16}
}

type SpectrumScanDataE int32

const (
	SpectrumScanDataE_SCAN_AUTO_CACHED_DATA SpectrumScanDataE = 0
	SpectrumScanDataE_SCAN_MANUAL_DATA      SpectrumScanDataE = 1
)

// Enum value maps for SpectrumScanDataE.
var (
	SpectrumScanDataE_name = map[int32]string{
		0: "SCAN_AUTO_CACHED_DATA",
		1: "SCAN_MANUAL_DATA",
	}
	SpectrumScanDataE_value = map[string]int32{
		"SCAN_AUTO_CACHED_DATA": 0,
		"SCAN_MANUAL_DATA":      1,
	}
)

func (x SpectrumScanDataE) Enum() *SpectrumScanDataE {
	p := new(SpectrumScanDataE)
	*p = x
	return p
}

func (x SpectrumScanDataE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpectrumScanDataE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[17].Descriptor()
}

func (SpectrumScanDataE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[17]
}

func (x SpectrumScanDataE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SpectrumScanDataE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SpectrumScanDataE(num)
	return nil
}

// Deprecated: Use SpectrumScanDataE.Descriptor instead.
func (SpectrumScanDataE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{17}
}

type SpectrumScanStatusE int32

const (
	SpectrumScanStatusE_SCAN_STATUS_INVALID     SpectrumScanStatusE = 0
	SpectrumScanStatusE_SCAN_STATUS_IN_PROGRESS SpectrumScanStatusE = 1
	SpectrumScanStatusE_SCAN_STATUS_VALID       SpectrumScanStatusE = 2
)

// Enum value maps for SpectrumScanStatusE.
var (
	SpectrumScanStatusE_name = map[int32]string{
		0: "SCAN_STATUS_INVALID",
		1: "SCAN_STATUS_IN_PROGRESS",
		2: "SCAN_STATUS_VALID",
	}
	SpectrumScanStatusE_value = map[string]int32{
		"SCAN_STATUS_INVALID":     0,
		"SCAN_STATUS_IN_PROGRESS": 1,
		"SCAN_STATUS_VALID":       2,
	}
)

func (x SpectrumScanStatusE) Enum() *SpectrumScanStatusE {
	p := new(SpectrumScanStatusE)
	*p = x
	return p
}

func (x SpectrumScanStatusE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpectrumScanStatusE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[18].Descriptor()
}

func (SpectrumScanStatusE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[18]
}

func (x SpectrumScanStatusE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SpectrumScanStatusE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SpectrumScanStatusE(num)
	return nil
}

// Deprecated: Use SpectrumScanStatusE.Descriptor instead.
func (SpectrumScanStatusE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{18}
}

type BandwidthModeE int32

const (
	BandwidthModeE_BW_MODE_UNKNOWN BandwidthModeE = 0
	BandwidthModeE_BW_MODE_1P2GHZ  BandwidthModeE = 1
	BandwidthModeE_BW_MODE_1P8GHZ  BandwidthModeE = 2
)

// Enum value maps for BandwidthModeE.
var (
	BandwidthModeE_name = map[int32]string{
		0: "BW_MODE_UNKNOWN",
		1: "BW_MODE_1P2GHZ",
		2: "BW_MODE_1P8GHZ",
	}
	BandwidthModeE_value = map[string]int32{
		"BW_MODE_UNKNOWN": 0,
		"BW_MODE_1P2GHZ":  1,
		"BW_MODE_1P8GHZ":  2,
	}
)

func (x BandwidthModeE) Enum() *BandwidthModeE {
	p := new(BandwidthModeE)
	*p = x
	return p
}

func (x BandwidthModeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BandwidthModeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[19].Descriptor()
}

func (BandwidthModeE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[19]
}

func (x BandwidthModeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *BandwidthModeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = BandwidthModeE(num)
	return nil
}

// Deprecated: Use BandwidthModeE.Descriptor instead.
func (BandwidthModeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{19}
}

type AnnexTypeE int32

const (
	AnnexTypeE_ANNEX_UNKNOWN AnnexTypeE = 0
	AnnexTypeE_ANNEX_A_TYPE  AnnexTypeE = 1
	AnnexTypeE_ANNEX_B_TYPE  AnnexTypeE = 2
	AnnexTypeE_ANNEX_C_TYPE  AnnexTypeE = 4
)

// Enum value maps for AnnexTypeE.
var (
	AnnexTypeE_name = map[int32]string{
		0: "ANNEX_UNKNOWN",
		1: "ANNEX_A_TYPE",
		2: "ANNEX_B_TYPE",
		4: "ANNEX_C_TYPE",
	}
	AnnexTypeE_value = map[string]int32{
		"ANNEX_UNKNOWN": 0,
		"ANNEX_A_TYPE":  1,
		"ANNEX_B_TYPE":  2,
		"ANNEX_C_TYPE":  4,
	}
)

func (x AnnexTypeE) Enum() *AnnexTypeE {
	p := new(AnnexTypeE)
	*p = x
	return p
}

func (x AnnexTypeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnnexTypeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[20].Descriptor()
}

func (AnnexTypeE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[20]
}

func (x AnnexTypeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AnnexTypeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AnnexTypeE(num)
	return nil
}

// Deprecated: Use AnnexTypeE.Descriptor instead.
func (AnnexTypeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{20}
}

type SplitTypeE int32

const (
	SplitTypeE_SPLIT_UNKNOWN SplitTypeE = 0
	SplitTypeE_SPLIT_42_54   SplitTypeE = 1
	SplitTypeE_SPLIT_65_85   SplitTypeE = 2
	SplitTypeE_SPLIT_85_108  SplitTypeE = 4
	SplitTypeE_SPLIT_204_258 SplitTypeE = 8
	SplitTypeE_SPLIT_300_372 SplitTypeE = 16
	SplitTypeE_SPLIT_396_492 SplitTypeE = 32
	SplitTypeE_SPLIT_492_606 SplitTypeE = 64
	SplitTypeE_SPLIT_684_834 SplitTypeE = 128
)

// Enum value maps for SplitTypeE.
var (
	SplitTypeE_name = map[int32]string{
		0:   "SPLIT_UNKNOWN",
		1:   "SPLIT_42_54",
		2:   "SPLIT_65_85",
		4:   "SPLIT_85_108",
		8:   "SPLIT_204_258",
		16:  "SPLIT_300_372",
		32:  "SPLIT_396_492",
		64:  "SPLIT_492_606",
		128: "SPLIT_684_834",
	}
	SplitTypeE_value = map[string]int32{
		"SPLIT_UNKNOWN": 0,
		"SPLIT_42_54":   1,
		"SPLIT_65_85":   2,
		"SPLIT_85_108":  4,
		"SPLIT_204_258": 8,
		"SPLIT_300_372": 16,
		"SPLIT_396_492": 32,
		"SPLIT_492_606": 64,
		"SPLIT_684_834": 128,
	}
)

func (x SplitTypeE) Enum() *SplitTypeE {
	p := new(SplitTypeE)
	*p = x
	return p
}

func (x SplitTypeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SplitTypeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[21].Descriptor()
}

func (SplitTypeE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[21]
}

func (x SplitTypeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SplitTypeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SplitTypeE(num)
	return nil
}

// Deprecated: Use SplitTypeE.Descriptor instead.
func (SplitTypeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{21}
}

type HpftModuleE int32

const (
	HpftModuleE_HPFT_MODULE_MISSING HpftModuleE = 0
	HpftModuleE_HPFT_MODULE_108     HpftModuleE = 1
	HpftModuleE_HPFT_MODULE_258     HpftModuleE = 2
	HpftModuleE_HPFT_MODULE_492     HpftModuleE = 3
	HpftModuleE_HPFT_MODULE_606     HpftModuleE = 4
	HpftModuleE_HPFT_MODULE_834     HpftModuleE = 5
)

// Enum value maps for HpftModuleE.
var (
	HpftModuleE_name = map[int32]string{
		0: "HPFT_MODULE_MISSING",
		1: "HPFT_MODULE_108",
		2: "HPFT_MODULE_258",
		3: "HPFT_MODULE_492",
		4: "HPFT_MODULE_606",
		5: "HPFT_MODULE_834",
	}
	HpftModuleE_value = map[string]int32{
		"HPFT_MODULE_MISSING": 0,
		"HPFT_MODULE_108":     1,
		"HPFT_MODULE_258":     2,
		"HPFT_MODULE_492":     3,
		"HPFT_MODULE_606":     4,
		"HPFT_MODULE_834":     5,
	}
)

func (x HpftModuleE) Enum() *HpftModuleE {
	p := new(HpftModuleE)
	*p = x
	return p
}

func (x HpftModuleE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HpftModuleE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[22].Descriptor()
}

func (HpftModuleE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[22]
}

func (x HpftModuleE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *HpftModuleE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = HpftModuleE(num)
	return nil
}

// Deprecated: Use HpftModuleE.Descriptor instead.
func (HpftModuleE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{22}
}

type LpftModuleE int32

const (
	LpftModuleE_LPFT_MODULE_MISSING LpftModuleE = 0
	LpftModuleE_LPFT_MODULE_42      LpftModuleE = 1
	LpftModuleE_LPFT_MODULE_65      LpftModuleE = 2
	LpftModuleE_LPFT_MODULE_85      LpftModuleE = 3
	LpftModuleE_LPFT_MODULE_204     LpftModuleE = 4
	LpftModuleE_LPFT_MODULE_300     LpftModuleE = 5
	LpftModuleE_LPFT_MODULE_396     LpftModuleE = 6
	LpftModuleE_LPFT_MODULE_492     LpftModuleE = 7
	LpftModuleE_LPFT_MODULE_588     LpftModuleE = 8
	LpftModuleE_LPFT_MODULE_684     LpftModuleE = 9
)

// Enum value maps for LpftModuleE.
var (
	LpftModuleE_name = map[int32]string{
		0: "LPFT_MODULE_MISSING",
		1: "LPFT_MODULE_42",
		2: "LPFT_MODULE_65",
		3: "LPFT_MODULE_85",
		4: "LPFT_MODULE_204",
		5: "LPFT_MODULE_300",
		6: "LPFT_MODULE_396",
		7: "LPFT_MODULE_492",
		8: "LPFT_MODULE_588",
		9: "LPFT_MODULE_684",
	}
	LpftModuleE_value = map[string]int32{
		"LPFT_MODULE_MISSING": 0,
		"LPFT_MODULE_42":      1,
		"LPFT_MODULE_65":      2,
		"LPFT_MODULE_85":      3,
		"LPFT_MODULE_204":     4,
		"LPFT_MODULE_300":     5,
		"LPFT_MODULE_396":     6,
		"LPFT_MODULE_492":     7,
		"LPFT_MODULE_588":     8,
		"LPFT_MODULE_684":     9,
	}
)

func (x LpftModuleE) Enum() *LpftModuleE {
	p := new(LpftModuleE)
	*p = x
	return p
}

func (x LpftModuleE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LpftModuleE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[23].Descriptor()
}

func (LpftModuleE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[23]
}

func (x LpftModuleE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *LpftModuleE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = LpftModuleE(num)
	return nil
}

// Deprecated: Use LpftModuleE.Descriptor instead.
func (LpftModuleE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{23}
}

type InvEqModuleE int32

const (
	InvEqModuleE_INV_EQ_MODULE_MISSING InvEqModuleE = 0
	InvEqModuleE_INV_EQ_MODULE_JUMPER  InvEqModuleE = 1
	InvEqModuleE_INV_EQ_MODULE_300FT   InvEqModuleE = 2
)

// Enum value maps for InvEqModuleE.
var (
	InvEqModuleE_name = map[int32]string{
		0: "INV_EQ_MODULE_MISSING",
		1: "INV_EQ_MODULE_JUMPER",
		2: "INV_EQ_MODULE_300FT",
	}
	InvEqModuleE_value = map[string]int32{
		"INV_EQ_MODULE_MISSING": 0,
		"INV_EQ_MODULE_JUMPER":  1,
		"INV_EQ_MODULE_300FT":   2,
	}
)

func (x InvEqModuleE) Enum() *InvEqModuleE {
	p := new(InvEqModuleE)
	*p = x
	return p
}

func (x InvEqModuleE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvEqModuleE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[24].Descriptor()
}

func (InvEqModuleE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[24]
}

func (x InvEqModuleE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *InvEqModuleE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = InvEqModuleE(num)
	return nil
}

// Deprecated: Use InvEqModuleE.Descriptor instead.
func (InvEqModuleE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{24}
}

type AnnexE int32

const (
	AnnexE_ANNEX_A AnnexE = 0
	AnnexE_ANNEX_B AnnexE = 1
)

// Enum value maps for AnnexE.
var (
	AnnexE_name = map[int32]string{
		0: "ANNEX_A",
		1: "ANNEX_B",
	}
	AnnexE_value = map[string]int32{
		"ANNEX_A": 0,
		"ANNEX_B": 1,
	}
)

func (x AnnexE) Enum() *AnnexE {
	p := new(AnnexE)
	*p = x
	return p
}

func (x AnnexE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnnexE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[25].Descriptor()
}

func (AnnexE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[25]
}

func (x AnnexE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AnnexE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AnnexE(num)
	return nil
}

// Deprecated: Use AnnexE.Descriptor instead.
func (AnnexE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{25}
}

type IngressPortSelectE int32

const (
	IngressPortSelectE_INGRESS_MAIN IngressPortSelectE = 0
	IngressPortSelectE_INGRESS_AUX1 IngressPortSelectE = 1
	IngressPortSelectE_INGRESS_AUX2 IngressPortSelectE = 2
)

// Enum value maps for IngressPortSelectE.
var (
	IngressPortSelectE_name = map[int32]string{
		0: "INGRESS_MAIN",
		1: "INGRESS_AUX1",
		2: "INGRESS_AUX2",
	}
	IngressPortSelectE_value = map[string]int32{
		"INGRESS_MAIN": 0,
		"INGRESS_AUX1": 1,
		"INGRESS_AUX2": 2,
	}
)

func (x IngressPortSelectE) Enum() *IngressPortSelectE {
	p := new(IngressPortSelectE)
	*p = x
	return p
}

func (x IngressPortSelectE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IngressPortSelectE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[26].Descriptor()
}

func (IngressPortSelectE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[26]
}

func (x IngressPortSelectE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *IngressPortSelectE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = IngressPortSelectE(num)
	return nil
}

// Deprecated: Use IngressPortSelectE.Descriptor instead.
func (IngressPortSelectE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{26}
}

type ErrorCodeE int32

const (
	ErrorCodeE_SUCCESS                                ErrorCodeE = 0
	ErrorCodeE_ERROR_FREQUENCY_OUT_OF_RANGE           ErrorCodeE = 1
	ErrorCodeE_ERROR_FREQUENCY_NOT_ALIGNED            ErrorCodeE = 2
	ErrorCodeE_ERROR_FREQUENCY_START_GREATER_THAN_END ErrorCodeE = 3
)

// Enum value maps for ErrorCodeE.
var (
	ErrorCodeE_name = map[int32]string{
		0: "SUCCESS",
		1: "ERROR_FREQUENCY_OUT_OF_RANGE",
		2: "ERROR_FREQUENCY_NOT_ALIGNED",
		3: "ERROR_FREQUENCY_START_GREATER_THAN_END",
	}
	ErrorCodeE_value = map[string]int32{
		"SUCCESS":                                0,
		"ERROR_FREQUENCY_OUT_OF_RANGE":           1,
		"ERROR_FREQUENCY_NOT_ALIGNED":            2,
		"ERROR_FREQUENCY_START_GREATER_THAN_END": 3,
	}
)

func (x ErrorCodeE) Enum() *ErrorCodeE {
	p := new(ErrorCodeE)
	*p = x
	return p
}

func (x ErrorCodeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCodeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[27].Descriptor()
}

func (ErrorCodeE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[27]
}

func (x ErrorCodeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ErrorCodeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ErrorCodeE(num)
	return nil
}

// Deprecated: Use ErrorCodeE.Descriptor instead.
func (ErrorCodeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{27}
}

type AmplifierTypeE int32

const (
	AmplifierTypeE_AMP_TYPE_OTHER        AmplifierTypeE = 1
	AmplifierTypeE_AMP_TYPE_UNKNOWN      AmplifierTypeE = 2
	AmplifierTypeE_AMP_TYPE_MULTIPORT    AmplifierTypeE = 3
	AmplifierTypeE_AMP_TYPE_LINEEXTENDER AmplifierTypeE = 4
	AmplifierTypeE_AMP_TYPE_BOOSTER      AmplifierTypeE = 5
	AmplifierTypeE_AMP_TYPE_COMPACT      AmplifierTypeE = 6
)

// Enum value maps for AmplifierTypeE.
var (
	AmplifierTypeE_name = map[int32]string{
		1: "AMP_TYPE_OTHER",
		2: "AMP_TYPE_UNKNOWN",
		3: "AMP_TYPE_MULTIPORT",
		4: "AMP_TYPE_LINEEXTENDER",
		5: "AMP_TYPE_BOOSTER",
		6: "AMP_TYPE_COMPACT",
	}
	AmplifierTypeE_value = map[string]int32{
		"AMP_TYPE_OTHER":        1,
		"AMP_TYPE_UNKNOWN":      2,
		"AMP_TYPE_MULTIPORT":    3,
		"AMP_TYPE_LINEEXTENDER": 4,
		"AMP_TYPE_BOOSTER":      5,
		"AMP_TYPE_COMPACT":      6,
	}
)

func (x AmplifierTypeE) Enum() *AmplifierTypeE {
	p := new(AmplifierTypeE)
	*p = x
	return p
}

func (x AmplifierTypeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AmplifierTypeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[28].Descriptor()
}

func (AmplifierTypeE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[28]
}

func (x AmplifierTypeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AmplifierTypeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AmplifierTypeE(num)
	return nil
}

// Deprecated: Use AmplifierTypeE.Descriptor instead.
func (AmplifierTypeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{28}
}

type PwrSupplyRedundancyModeE int32

const (
	PwrSupplyRedundancyModeE_PS_REDUNDANCY_MODE_NONE              PwrSupplyRedundancyModeE = 0
	PwrSupplyRedundancyModeE_PS_REDUNDANCY_MODE_OTHER             PwrSupplyRedundancyModeE = 1
	PwrSupplyRedundancyModeE_PS_REDUNDANCY_MODE_UNKNOWN           PwrSupplyRedundancyModeE = 2
	PwrSupplyRedundancyModeE_PS_REDUNDANCY_MODE_LOADSHARING       PwrSupplyRedundancyModeE = 3
	PwrSupplyRedundancyModeE_PS_REDUNDANCY_MODE_SWITCHEDREDUNDANT PwrSupplyRedundancyModeE = 4
)

// Enum value maps for PwrSupplyRedundancyModeE.
var (
	PwrSupplyRedundancyModeE_name = map[int32]string{
		0: "PS_REDUNDANCY_MODE_NONE",
		1: "PS_REDUNDANCY_MODE_OTHER",
		2: "PS_REDUNDANCY_MODE_UNKNOWN",
		3: "PS_REDUNDANCY_MODE_LOADSHARING",
		4: "PS_REDUNDANCY_MODE_SWITCHEDREDUNDANT",
	}
	PwrSupplyRedundancyModeE_value = map[string]int32{
		"PS_REDUNDANCY_MODE_NONE":              0,
		"PS_REDUNDANCY_MODE_OTHER":             1,
		"PS_REDUNDANCY_MODE_UNKNOWN":           2,
		"PS_REDUNDANCY_MODE_LOADSHARING":       3,
		"PS_REDUNDANCY_MODE_SWITCHEDREDUNDANT": 4,
	}
)

func (x PwrSupplyRedundancyModeE) Enum() *PwrSupplyRedundancyModeE {
	p := new(PwrSupplyRedundancyModeE)
	*p = x
	return p
}

func (x PwrSupplyRedundancyModeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PwrSupplyRedundancyModeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[29].Descriptor()
}

func (PwrSupplyRedundancyModeE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[29]
}

func (x PwrSupplyRedundancyModeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PwrSupplyRedundancyModeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PwrSupplyRedundancyModeE(num)
	return nil
}

// Deprecated: Use PwrSupplyRedundancyModeE.Descriptor instead.
func (PwrSupplyRedundancyModeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{29}
}

type EvPriorityE int32

const (
	EvPriorityE_EV_EMERGENCY EvPriorityE = 1
	EvPriorityE_EV_ALERT     EvPriorityE = 2
	EvPriorityE_EV_CRITICAL  EvPriorityE = 3
	EvPriorityE_EV_ERROR     EvPriorityE = 4
	EvPriorityE_EV_WARNING   EvPriorityE = 5
	EvPriorityE_EV_NOTICE    EvPriorityE = 6
	EvPriorityE_EV_INFO      EvPriorityE = 7
	EvPriorityE_EV_DEBUG     EvPriorityE = 8
)

// Enum value maps for EvPriorityE.
var (
	EvPriorityE_name = map[int32]string{
		1: "EV_EMERGENCY",
		2: "EV_ALERT",
		3: "EV_CRITICAL",
		4: "EV_ERROR",
		5: "EV_WARNING",
		6: "EV_NOTICE",
		7: "EV_INFO",
		8: "EV_DEBUG",
	}
	EvPriorityE_value = map[string]int32{
		"EV_EMERGENCY": 1,
		"EV_ALERT":     2,
		"EV_CRITICAL":  3,
		"EV_ERROR":     4,
		"EV_WARNING":   5,
		"EV_NOTICE":    6,
		"EV_INFO":      7,
		"EV_DEBUG":     8,
	}
)

func (x EvPriorityE) Enum() *EvPriorityE {
	p := new(EvPriorityE)
	*p = x
	return p
}

func (x EvPriorityE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvPriorityE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_common_proto_enumTypes[30].Descriptor()
}

func (EvPriorityE) Type() protoreflect.EnumType {
	return &file_amps_common_proto_enumTypes[30]
}

func (x EvPriorityE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EvPriorityE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EvPriorityE(num)
	return nil
}

// Deprecated: Use EvPriorityE.Descriptor instead.
func (EvPriorityE) EnumDescriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{30}
}

type AnalogOutRead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idx           *int32                 `protobuf:"varint,1,opt,name=idx" json:"idx,omitempty"`
	Value         *uint32                `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Result        *int32                 `protobuf:"zigzag32,3,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalogOutRead) Reset() {
	*x = AnalogOutRead{}
	mi := &file_amps_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalogOutRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalogOutRead) ProtoMessage() {}

func (x *AnalogOutRead) ProtoReflect() protoreflect.Message {
	mi := &file_amps_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalogOutRead.ProtoReflect.Descriptor instead.
func (*AnalogOutRead) Descriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{0}
}

func (x *AnalogOutRead) GetIdx() int32 {
	if x != nil && x.Idx != nil {
		return *x.Idx
	}
	return 0
}

func (x *AnalogOutRead) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *AnalogOutRead) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type AnalogOutWrite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idx           *int32                 `protobuf:"varint,1,opt,name=idx" json:"idx,omitempty"`
	Value         *uint32                `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Result        *int32                 `protobuf:"zigzag32,3,opt,name=result" json:"result,omitempty"`
	SaveToNvm     *bool                  `protobuf:"varint,4,opt,name=save_to_nvm,json=saveToNvm,def=1" json:"save_to_nvm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

// Default values for AnalogOutWrite fields.
const (
	Default_AnalogOutWrite_SaveToNvm = bool(true)
)

func (x *AnalogOutWrite) Reset() {
	*x = AnalogOutWrite{}
	mi := &file_amps_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalogOutWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalogOutWrite) ProtoMessage() {}

func (x *AnalogOutWrite) ProtoReflect() protoreflect.Message {
	mi := &file_amps_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalogOutWrite.ProtoReflect.Descriptor instead.
func (*AnalogOutWrite) Descriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{1}
}

func (x *AnalogOutWrite) GetIdx() int32 {
	if x != nil && x.Idx != nil {
		return *x.Idx
	}
	return 0
}

func (x *AnalogOutWrite) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *AnalogOutWrite) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

func (x *AnalogOutWrite) GetSaveToNvm() bool {
	if x != nil && x.SaveToNvm != nil {
		return *x.SaveToNvm
	}
	return Default_AnalogOutWrite_SaveToNvm
}

type AnalogInRead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idx           *int32                 `protobuf:"varint,1,opt,name=idx" json:"idx,omitempty"`
	Value         *int32                 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Result        *int32                 `protobuf:"zigzag32,3,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalogInRead) Reset() {
	*x = AnalogInRead{}
	mi := &file_amps_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalogInRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalogInRead) ProtoMessage() {}

func (x *AnalogInRead) ProtoReflect() protoreflect.Message {
	mi := &file_amps_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalogInRead.ProtoReflect.Descriptor instead.
func (*AnalogInRead) Descriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{2}
}

func (x *AnalogInRead) GetIdx() int32 {
	if x != nil && x.Idx != nil {
		return *x.Idx
	}
	return 0
}

func (x *AnalogInRead) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *AnalogInRead) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type FragmentInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FragmentIndex  *uint32                `protobuf:"varint,1,opt,name=fragment_index,json=fragmentIndex" json:"fragment_index,omitempty"`
	TotalFragments *uint32                `protobuf:"varint,2,opt,name=total_fragments,json=totalFragments" json:"total_fragments,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FragmentInfo) Reset() {
	*x = FragmentInfo{}
	mi := &file_amps_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FragmentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FragmentInfo) ProtoMessage() {}

func (x *FragmentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_amps_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FragmentInfo.ProtoReflect.Descriptor instead.
func (*FragmentInfo) Descriptor() ([]byte, []int) {
	return file_amps_common_proto_rawDescGZIP(), []int{3}
}

func (x *FragmentInfo) GetFragmentIndex() uint32 {
	if x != nil && x.FragmentIndex != nil {
		return *x.FragmentIndex
	}
	return 0
}

func (x *FragmentInfo) GetTotalFragments() uint32 {
	if x != nil && x.TotalFragments != nil {
		return *x.TotalFragments
	}
	return 0
}

var File_amps_common_proto protoreflect.FileDescriptor

const file_amps_common_proto_rawDesc = "" +
	"\n" +
	"\x11amps/common.proto\x12\bscte.amp\"O\n" +
	"\rAnalogOutRead\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\x05R\x03idx\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value\x12\x16\n" +
	"\x06result\x18\x03 \x01(\x11R\x06result\"v\n" +
	"\x0eAnalogOutWrite\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\x05R\x03idx\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value\x12\x16\n" +
	"\x06result\x18\x03 \x01(\x11R\x06result\x12$\n" +
	"\vsave_to_nvm\x18\x04 \x01(\b:\x04trueR\tsaveToNvm\"N\n" +
	"\fAnalogInRead\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\x05R\x03idx\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x12\x16\n" +
	"\x06result\x18\x03 \x01(\x11R\x06result\"^\n" +
	"\fFragmentInfo\x12%\n" +
	"\x0efragment_index\x18\x01 \x01(\rR\rfragmentIndex\x12'\n" +
	"\x0ftotal_fragments\x18\x02 \x01(\rR\x0etotalFragments*J\n" +
	"\x0fpath_selector_e\x12\x19\n" +
	"\x15PATH_SELECTOR_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"DOWNSTREAM\x10\x01\x12\f\n" +
	"\bUPSTREAM\x10\x02*w\n" +
	"\x0frf_port_index_e\x12\x13\n" +
	"\x0fRF_PORT_INDEX_1\x10\x01\x12\x13\n" +
	"\x0fRF_PORT_INDEX_2\x10\x02\x12\x13\n" +
	"\x0fRF_PORT_INDEX_3\x10\x03\x12\x13\n" +
	"\x0fRF_PORT_INDEX_4\x10\x04\x12\x10\n" +
	"\vRF_PORT_ALL\x10\xff\x01*\xa4\x01\n" +
	"\x0ealignment_op_e\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\f\n" +
	"\bPRE_TUNE\x10\x01\x12\x0f\n" +
	"\vCOARSE_TUNE\x10\x02\x12\r\n" +
	"\tFINE_TUNE\x10\x03\x12\r\n" +
	"\tFULL_TUNE\x10\x04\x12\b\n" +
	"\x04SAVE\x10\x05\x12\n" +
	"\n" +
	"\x06REVERT\x10\x06\x12\f\n" +
	"\bCSM_CALC\x10\a\x12\r\n" +
	"\tRMSE_CALC\x10\b\x12\x11\n" +
	"\rSAVE_COMPLETE\x10\t*H\n" +
	"\x12alignment_status_e\x12\b\n" +
	"\x04IDLE\x10\x01\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x02\x12\f\n" +
	"\bCOMPLETE\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04*\xf7\x01\n" +
	"\x1arf_spectrum_capture_type_e\x12\x12\n" +
	"\x0ePORT1_UPSTREAM\x10\x01\x12\x14\n" +
	"\x10PORT1_DOWNSTREAM\x10\x02\x12\x12\n" +
	"\x0ePORT2_UPSTREAM\x10\x04\x12\x14\n" +
	"\x10PORT2_DOWNSTREAM\x10\b\x12\x12\n" +
	"\x0ePORT3_UPSTREAM\x10\x10\x12\x14\n" +
	"\x10PORT3_DOWNSTREAM\x10 \x12\x12\n" +
	"\x0ePORT4_UPSTREAM\x10@\x12\x15\n" +
	"\x10PORT4_DOWNSTREAM\x10\x80\x01\x12\x16\n" +
	"\x11PORT_UPSTREAM_ALL\x10\x80\x02\x12\x18\n" +
	"\x13PORT_DOWNSTREAM_ALL\x10\x80\x04*\x86\x01\n" +
	"\x10alignment_type_e\x12\x1a\n" +
	"\x16ALIGNMENT_TYPE_DS_AUTO\x10\x01\x12\x1a\n" +
	"\x16ALIGNMENT_TYPE_US_AUTO\x10\x02\x12\x1c\n" +
	"\x18ALIGNMENT_TYPE_DS_MANUAL\x10\x04\x12\x1c\n" +
	"\x18ALIGNMENT_TYPE_US_MANUAL\x10\b*\xd2\x01\n" +
	"\x17rf_level_control_type_e\x12\x1a\n" +
	"\x16RF_LEVEL_CONTROL_OTHER\x10\x00\x12\x1c\n" +
	"\x18RF_LEVEL_CONTROL_UNKNOWN\x10\x01\x12\x1e\n" +
	"\x1aRF_LEVEL_CONTROL_QUASI_AGC\x10\x02\x12*\n" +
	"&RF_LEVEL_CONTROL_THERMAL_LEVEL_CONTROL\x10\x03\x121\n" +
	"-RF_LEVEL_CONTROL_THERMAL_LEVEL_CONTROL_SELECT\x10\x04*q\n" +
	"\fstage_type_e\x12\x14\n" +
	"\x10STAGE_TYPE_OTHER\x10\x00\x12\x16\n" +
	"\x12STAGE_TYPE_UNKNOWN\x10\x01\x12\x19\n" +
	"\x15STAGE_TYPE_ATTENUATOR\x10\x02\x12\x18\n" +
	"\x14STAGE_TYPE_EQUALIZER\x10\x03*\xbb\x01\n" +
	"\rstage_index_e\x12\x10\n" +
	"\fSTAGE_INDEX1\x10\x01\x12\x10\n" +
	"\fSTAGE_INDEX2\x10\x02\x12\x10\n" +
	"\fSTAGE_INDEX3\x10\x03\x12\x10\n" +
	"\fSTAGE_INDEX4\x10\x04\x12\x10\n" +
	"\fSTAGE_INDEX5\x10\x05\x12\x10\n" +
	"\fSTAGE_INDEX6\x10\x06\x12\x10\n" +
	"\fSTAGE_INDEX7\x10\a\x12\x10\n" +
	"\fSTAGE_INDEX8\x10\b\x12\x1a\n" +
	"\x16STAGE_INDEX_CUMULATIVE\x10\t*\xbc\x01\n" +
	"\x10stage_location_e\x12\x18\n" +
	"\x14STAGE_LOCATION_OTHER\x10\x00\x12\x1a\n" +
	"\x16STAGE_LOCATION_UNKNOWN\x10\x01\x12\x18\n" +
	"\x14STAGE_LOCATION_INPUT\x10\x02\x12\x1e\n" +
	"\x1aSTAGE_LOCATION_INTER_STAGE\x10\x03\x12\x19\n" +
	"\x15STAGE_LOCATION_OUTPUT\x10\x04\x12\x1d\n" +
	"\x19STAGE_LOCATION_CUMULATIVE\x10\x05**\n" +
	"\x12enclosure_status_e\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x01\x12\b\n" +
	"\x04OPEN\x10\x02*/\n" +
	"\fagc_config_e\x12\v\n" +
	"\aTHERMAL\x10\x01\x12\n" +
	"\n" +
	"\x06MANUAL\x10\x02\x12\x06\n" +
	"\x02ON\x10\x03*:\n" +
	"\x0fus_gain_stage_e\x12\f\n" +
	"\bUS_ATTN1\x10\x01\x12\f\n" +
	"\bUS_ATTN2\x10\x02\x12\v\n" +
	"\aUS_CUMU\x10\x03*+\n" +
	"\rus_eq_stage_e\x12\n" +
	"\n" +
	"\x06US_EQ1\x10\x01\x12\x0e\n" +
	"\n" +
	"US_CUMU_EQ\x10\x02*@\n" +
	"\x17ingress_switch_config_e\x12\b\n" +
	"\x04SW_0\x10\x00\x12\f\n" +
	"\bSW_NEG_6\x10\x01\x12\r\n" +
	"\tSW_NEG_50\x10\x02*H\n" +
	"\x0ftest_point_id_e\x12\f\n" +
	"\bINPUT_TP\x10\x01\x12\r\n" +
	"\tOUTPUT_TP\x10\x02\x12\v\n" +
	"\aAUX1_TP\x10\x03\x12\v\n" +
	"\aAUX2_TP\x10\x04*'\n" +
	"\x13test_point_config_e\x12\a\n" +
	"\x03FWD\x10\x01\x12\a\n" +
	"\x03REV\x10\x02*G\n" +
	"\x14spectrum_scan_data_e\x12\x19\n" +
	"\x15SCAN_AUTO_CACHED_DATA\x10\x00\x12\x14\n" +
	"\x10SCAN_MANUAL_DATA\x10\x01*e\n" +
	"\x16spectrum_scan_status_e\x12\x17\n" +
	"\x13SCAN_STATUS_INVALID\x10\x00\x12\x1b\n" +
	"\x17SCAN_STATUS_IN_PROGRESS\x10\x01\x12\x15\n" +
	"\x11SCAN_STATUS_VALID\x10\x02*O\n" +
	"\x10bandwidth_mode_e\x12\x13\n" +
	"\x0fBW_MODE_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eBW_MODE_1P2GHZ\x10\x01\x12\x12\n" +
	"\x0eBW_MODE_1P8GHZ\x10\x02*W\n" +
	"\fannex_type_e\x12\x11\n" +
	"\rANNEX_UNKNOWN\x10\x00\x12\x10\n" +
	"\fANNEX_A_TYPE\x10\x01\x12\x10\n" +
	"\fANNEX_B_TYPE\x10\x02\x12\x10\n" +
	"\fANNEX_C_TYPE\x10\x04*\xb5\x01\n" +
	"\fsplit_type_e\x12\x11\n" +
	"\rSPLIT_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vSPLIT_42_54\x10\x01\x12\x0f\n" +
	"\vSPLIT_65_85\x10\x02\x12\x10\n" +
	"\fSPLIT_85_108\x10\x04\x12\x11\n" +
	"\rSPLIT_204_258\x10\b\x12\x11\n" +
	"\rSPLIT_300_372\x10\x10\x12\x11\n" +
	"\rSPLIT_396_492\x10 \x12\x11\n" +
	"\rSPLIT_492_606\x10@\x12\x12\n" +
	"\rSPLIT_684_834\x10\x80\x01*\x91\x01\n" +
	"\rhpft_module_e\x12\x17\n" +
	"\x13HPFT_MODULE_MISSING\x10\x00\x12\x13\n" +
	"\x0fHPFT_MODULE_108\x10\x01\x12\x13\n" +
	"\x0fHPFT_MODULE_258\x10\x02\x12\x13\n" +
	"\x0fHPFT_MODULE_492\x10\x03\x12\x13\n" +
	"\x0fHPFT_MODULE_606\x10\x04\x12\x13\n" +
	"\x0fHPFT_MODULE_834\x10\x05*\xe2\x01\n" +
	"\rlpft_module_e\x12\x17\n" +
	"\x13LPFT_MODULE_MISSING\x10\x00\x12\x12\n" +
	"\x0eLPFT_MODULE_42\x10\x01\x12\x12\n" +
	"\x0eLPFT_MODULE_65\x10\x02\x12\x12\n" +
	"\x0eLPFT_MODULE_85\x10\x03\x12\x13\n" +
	"\x0fLPFT_MODULE_204\x10\x04\x12\x13\n" +
	"\x0fLPFT_MODULE_300\x10\x05\x12\x13\n" +
	"\x0fLPFT_MODULE_396\x10\x06\x12\x13\n" +
	"\x0fLPFT_MODULE_492\x10\a\x12\x13\n" +
	"\x0fLPFT_MODULE_588\x10\b\x12\x13\n" +
	"\x0fLPFT_MODULE_684\x10\t*_\n" +
	"\x0finv_eq_module_e\x12\x19\n" +
	"\x15INV_EQ_MODULE_MISSING\x10\x00\x12\x18\n" +
	"\x14INV_EQ_MODULE_JUMPER\x10\x01\x12\x17\n" +
	"\x13INV_EQ_MODULE_300FT\x10\x02*#\n" +
	"\aannex_e\x12\v\n" +
	"\aANNEX_A\x10\x00\x12\v\n" +
	"\aANNEX_B\x10\x01*M\n" +
	"\x15ingress_port_select_e\x12\x10\n" +
	"\fINGRESS_MAIN\x10\x00\x12\x10\n" +
	"\fINGRESS_AUX1\x10\x01\x12\x10\n" +
	"\fINGRESS_AUX2\x10\x02*\x8a\x01\n" +
	"\ferror_code_e\x12\v\n" +
	"\aSUCCESS\x10\x00\x12 \n" +
	"\x1cERROR_FREQUENCY_OUT_OF_RANGE\x10\x01\x12\x1f\n" +
	"\x1bERROR_FREQUENCY_NOT_ALIGNED\x10\x02\x12*\n" +
	"&ERROR_FREQUENCY_START_GREATER_THAN_END\x10\x03*\x9b\x01\n" +
	"\x10amplifier_type_e\x12\x12\n" +
	"\x0eAMP_TYPE_OTHER\x10\x01\x12\x14\n" +
	"\x10AMP_TYPE_UNKNOWN\x10\x02\x12\x16\n" +
	"\x12AMP_TYPE_MULTIPORT\x10\x03\x12\x19\n" +
	"\x15AMP_TYPE_LINEEXTENDER\x10\x04\x12\x14\n" +
	"\x10AMP_TYPE_BOOSTER\x10\x05\x12\x14\n" +
	"\x10AMP_TYPE_COMPACT\x10\x06*\xc7\x01\n" +
	"\x1cpwr_supply_redundancy_mode_e\x12\x1b\n" +
	"\x17PS_REDUNDANCY_MODE_NONE\x10\x00\x12\x1c\n" +
	"\x18PS_REDUNDANCY_MODE_OTHER\x10\x01\x12\x1e\n" +
	"\x1aPS_REDUNDANCY_MODE_UNKNOWN\x10\x02\x12\"\n" +
	"\x1ePS_REDUNDANCY_MODE_LOADSHARING\x10\x03\x12(\n" +
	"$PS_REDUNDANCY_MODE_SWITCHEDREDUNDANT\x10\x04*\x88\x01\n" +
	"\rev_priority_e\x12\x10\n" +
	"\fEV_EMERGENCY\x10\x01\x12\f\n" +
	"\bEV_ALERT\x10\x02\x12\x0f\n" +
	"\vEV_CRITICAL\x10\x03\x12\f\n" +
	"\bEV_ERROR\x10\x04\x12\x0e\n" +
	"\n" +
	"EV_WARNING\x10\x05\x12\r\n" +
	"\tEV_NOTICE\x10\x06\x12\v\n" +
	"\aEV_INFO\x10\a\x12\f\n" +
	"\bEV_DEBUG\x10\bB=\n" +
	"\rorg.scte.ampsP\x01Z*github.com/enshure/scte-go/amps_go;scteamp"

var (
	file_amps_common_proto_rawDescOnce sync.Once
	file_amps_common_proto_rawDescData []byte
)

func file_amps_common_proto_rawDescGZIP() []byte {
	file_amps_common_proto_rawDescOnce.Do(func() {
		file_amps_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amps_common_proto_rawDesc), len(file_amps_common_proto_rawDesc)))
	})
	return file_amps_common_proto_rawDescData
}

var file_amps_common_proto_enumTypes = make([]protoimpl.EnumInfo, 31)
var file_amps_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_amps_common_proto_goTypes = []any{
	(PathSelectorE)(0),            // 0: scte.amp.path_selector_e
	(RfPortIndexE)(0),             // 1: scte.amp.rf_port_index_e
	(AlignmentOpE)(0),             // 2: scte.amp.alignment_op_e
	(AlignmentStatusE)(0),         // 3: scte.amp.alignment_status_e
	(RfSpectrumCaptureTypeE)(0),   // 4: scte.amp.rf_spectrum_capture_type_e
	(AlignmentTypeE)(0),           // 5: scte.amp.alignment_type_e
	(RfLevelControlTypeE)(0),      // 6: scte.amp.rf_level_control_type_e
	(StageTypeE)(0),               // 7: scte.amp.stage_type_e
	(StageIndexE)(0),              // 8: scte.amp.stage_index_e
	(StageLocationE)(0),           // 9: scte.amp.stage_location_e
	(EnclosureStatusE)(0),         // 10: scte.amp.enclosure_status_e
	(AgcConfigE)(0),               // 11: scte.amp.agc_config_e
	(UsGainStageE)(0),             // 12: scte.amp.us_gain_stage_e
	(UsEqStageE)(0),               // 13: scte.amp.us_eq_stage_e
	(IngressSwitchConfigE)(0),     // 14: scte.amp.ingress_switch_config_e
	(TestPointIdE)(0),             // 15: scte.amp.test_point_id_e
	(TestPointConfigE)(0),         // 16: scte.amp.test_point_config_e
	(SpectrumScanDataE)(0),        // 17: scte.amp.spectrum_scan_data_e
	(SpectrumScanStatusE)(0),      // 18: scte.amp.spectrum_scan_status_e
	(BandwidthModeE)(0),           // 19: scte.amp.bandwidth_mode_e
	(AnnexTypeE)(0),               // 20: scte.amp.annex_type_e
	(SplitTypeE)(0),               // 21: scte.amp.split_type_e
	(HpftModuleE)(0),              // 22: scte.amp.hpft_module_e
	(LpftModuleE)(0),              // 23: scte.amp.lpft_module_e
	(InvEqModuleE)(0),             // 24: scte.amp.inv_eq_module_e
	(AnnexE)(0),                   // 25: scte.amp.annex_e
	(IngressPortSelectE)(0),       // 26: scte.amp.ingress_port_select_e
	(ErrorCodeE)(0),               // 27: scte.amp.error_code_e
	(AmplifierTypeE)(0),           // 28: scte.amp.amplifier_type_e
	(PwrSupplyRedundancyModeE)(0), // 29: scte.amp.pwr_supply_redundancy_mode_e
	(EvPriorityE)(0),              // 30: scte.amp.ev_priority_e
	(*AnalogOutRead)(nil),         // 31: scte.amp.AnalogOutRead
	(*AnalogOutWrite)(nil),        // 32: scte.amp.AnalogOutWrite
	(*AnalogInRead)(nil),          // 33: scte.amp.AnalogInRead
	(*FragmentInfo)(nil),          // 34: scte.amp.FragmentInfo
}
var file_amps_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_amps_common_proto_init() }
func file_amps_common_proto_init() {
	if File_amps_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amps_common_proto_rawDesc), len(file_amps_common_proto_rawDesc)),
			NumEnums:      31,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_amps_common_proto_goTypes,
		DependencyIndexes: file_amps_common_proto_depIdxs,
		EnumInfos:         file_amps_common_proto_enumTypes,
		MessageInfos:      file_amps_common_proto_msgTypes,
	}.Build()
	File_amps_common_proto = out.File
	file_amps_common_proto_goTypes = nil
	file_amps_common_proto_depIdxs = nil
}
