// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: amps/debug.proto

package scteamp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutputSelectE int32

const (
	OutputSelectE_OUTSEL_SW1          OutputSelectE = 0
	OutputSelectE_OUTSEL_SW2          OutputSelectE = 1
	OutputSelectE_OUTSEL_MIXER_MODE   OutputSelectE = 2
	OutputSelectE_OUTSEL_MIXER_ENABLE OutputSelectE = 3
	OutputSelectE_OUTSEL_MIXER_ENX    OutputSelectE = 4
	OutputSelectE_OUTSEL_MIXER_RSTB   OutputSelectE = 5
	OutputSelectE_OUTSEL_INPUT_TP     OutputSelectE = 6
	OutputSelectE_OUTSEL_OUTPUT_TP    OutputSelectE = 7
	OutputSelectE_OUTSEL_CURRENT_CTRL OutputSelectE = 8
)

// Enum value maps for OutputSelectE.
var (
	OutputSelectE_name = map[int32]string{
		0: "OUTSEL_SW1",
		1: "OUTSEL_SW2",
		2: "OUTSEL_MIXER_MODE",
		3: "OUTSEL_MIXER_ENABLE",
		4: "OUTSEL_MIXER_ENX",
		5: "OUTSEL_MIXER_RSTB",
		6: "OUTSEL_INPUT_TP",
		7: "OUTSEL_OUTPUT_TP",
		8: "OUTSEL_CURRENT_CTRL",
	}
	OutputSelectE_value = map[string]int32{
		"OUTSEL_SW1":          0,
		"OUTSEL_SW2":          1,
		"OUTSEL_MIXER_MODE":   2,
		"OUTSEL_MIXER_ENABLE": 3,
		"OUTSEL_MIXER_ENX":    4,
		"OUTSEL_MIXER_RSTB":   5,
		"OUTSEL_INPUT_TP":     6,
		"OUTSEL_OUTPUT_TP":    7,
		"OUTSEL_CURRENT_CTRL": 8,
	}
)

func (x OutputSelectE) Enum() *OutputSelectE {
	p := new(OutputSelectE)
	*p = x
	return p
}

func (x OutputSelectE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputSelectE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_debug_proto_enumTypes[0].Descriptor()
}

func (OutputSelectE) Type() protoreflect.EnumType {
	return &file_amps_debug_proto_enumTypes[0]
}

func (x OutputSelectE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *OutputSelectE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = OutputSelectE(num)
	return nil
}

// Deprecated: Use OutputSelectE.Descriptor instead.
func (OutputSelectE) EnumDescriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{0}
}

type SetOutputLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputSelect  *OutputSelectE         `protobuf:"varint,1,opt,name=output_select,json=outputSelect,enum=scte.amp.OutputSelectE" json:"output_select,omitempty"`
	Level         *bool                  `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOutputLevel) Reset() {
	*x = SetOutputLevel{}
	mi := &file_amps_debug_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOutputLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOutputLevel) ProtoMessage() {}

func (x *SetOutputLevel) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOutputLevel.ProtoReflect.Descriptor instead.
func (*SetOutputLevel) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{0}
}

func (x *SetOutputLevel) GetOutputSelect() OutputSelectE {
	if x != nil && x.OutputSelect != nil {
		return *x.OutputSelect
	}
	return OutputSelectE_OUTSEL_SW1
}

func (x *SetOutputLevel) GetLevel() bool {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return false
}

type GetRfMixerRegRead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idx           *int32                 `protobuf:"varint,1,opt,name=idx" json:"idx,omitempty"`
	Result        *int32                 `protobuf:"zigzag32,2,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRfMixerRegRead) Reset() {
	*x = GetRfMixerRegRead{}
	mi := &file_amps_debug_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRfMixerRegRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRfMixerRegRead) ProtoMessage() {}

func (x *GetRfMixerRegRead) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRfMixerRegRead.ProtoReflect.Descriptor instead.
func (*GetRfMixerRegRead) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{1}
}

func (x *GetRfMixerRegRead) GetIdx() int32 {
	if x != nil && x.Idx != nil {
		return *x.Idx
	}
	return 0
}

func (x *GetRfMixerRegRead) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type SendRfMixerSingleWrite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          *uint32                `protobuf:"varint,1,opt,name=addr" json:"addr,omitempty"`
	Value         *uint32                `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Result        *int32                 `protobuf:"zigzag32,3,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRfMixerSingleWrite) Reset() {
	*x = SendRfMixerSingleWrite{}
	mi := &file_amps_debug_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRfMixerSingleWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRfMixerSingleWrite) ProtoMessage() {}

func (x *SendRfMixerSingleWrite) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRfMixerSingleWrite.ProtoReflect.Descriptor instead.
func (*SendRfMixerSingleWrite) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{2}
}

func (x *SendRfMixerSingleWrite) GetAddr() uint32 {
	if x != nil && x.Addr != nil {
		return *x.Addr
	}
	return 0
}

func (x *SendRfMixerSingleWrite) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *SendRfMixerSingleWrite) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type SendRfMixerPnSetWrite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          *uint32                `protobuf:"varint,1,opt,name=path" json:"path,omitempty"`
	Data          []uint32               `protobuf:"varint,2,rep,name=data" json:"data,omitempty"`
	Result        *int32                 `protobuf:"zigzag32,3,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRfMixerPnSetWrite) Reset() {
	*x = SendRfMixerPnSetWrite{}
	mi := &file_amps_debug_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRfMixerPnSetWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRfMixerPnSetWrite) ProtoMessage() {}

func (x *SendRfMixerPnSetWrite) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRfMixerPnSetWrite.ProtoReflect.Descriptor instead.
func (*SendRfMixerPnSetWrite) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{3}
}

func (x *SendRfMixerPnSetWrite) GetPath() uint32 {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return 0
}

func (x *SendRfMixerPnSetWrite) GetData() []uint32 {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SendRfMixerPnSetWrite) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type GetUpTimeCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *int32                 `protobuf:"zigzag32,1,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpTimeCount) Reset() {
	*x = GetUpTimeCount{}
	mi := &file_amps_debug_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpTimeCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpTimeCount) ProtoMessage() {}

func (x *GetUpTimeCount) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpTimeCount.ProtoReflect.Descriptor instead.
func (*GetUpTimeCount) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{4}
}

func (x *GetUpTimeCount) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type RfsScanModeDisable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disable       *bool                  `protobuf:"varint,1,opt,name=disable" json:"disable,omitempty"`
	Result        *int32                 `protobuf:"zigzag32,2,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RfsScanModeDisable) Reset() {
	*x = RfsScanModeDisable{}
	mi := &file_amps_debug_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RfsScanModeDisable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RfsScanModeDisable) ProtoMessage() {}

func (x *RfsScanModeDisable) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RfsScanModeDisable.ProtoReflect.Descriptor instead.
func (*RfsScanModeDisable) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{5}
}

func (x *RfsScanModeDisable) GetDisable() bool {
	if x != nil && x.Disable != nil {
		return *x.Disable
	}
	return false
}

func (x *RfsScanModeDisable) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type RfsCoeffBlockRW struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableNumber   *uint32                `protobuf:"varint,1,opt,name=tableNumber" json:"tableNumber,omitempty"`
	BlockNumber   *uint32                `protobuf:"varint,2,opt,name=blockNumber" json:"blockNumber,omitempty"`
	CoeffTable    []int32                `protobuf:"zigzag32,3,rep,name=coeffTable" json:"coeffTable,omitempty"`
	Result        *int32                 `protobuf:"zigzag32,4,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RfsCoeffBlockRW) Reset() {
	*x = RfsCoeffBlockRW{}
	mi := &file_amps_debug_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RfsCoeffBlockRW) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RfsCoeffBlockRW) ProtoMessage() {}

func (x *RfsCoeffBlockRW) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RfsCoeffBlockRW.ProtoReflect.Descriptor instead.
func (*RfsCoeffBlockRW) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{6}
}

func (x *RfsCoeffBlockRW) GetTableNumber() uint32 {
	if x != nil && x.TableNumber != nil {
		return *x.TableNumber
	}
	return 0
}

func (x *RfsCoeffBlockRW) GetBlockNumber() uint32 {
	if x != nil && x.BlockNumber != nil {
		return *x.BlockNumber
	}
	return 0
}

func (x *RfsCoeffBlockRW) GetCoeffTable() []int32 {
	if x != nil {
		return x.CoeffTable
	}
	return nil
}

func (x *RfsCoeffBlockRW) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type RfsCoeffSaveToFlashWrite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *int32                 `protobuf:"zigzag32,1,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RfsCoeffSaveToFlashWrite) Reset() {
	*x = RfsCoeffSaveToFlashWrite{}
	mi := &file_amps_debug_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RfsCoeffSaveToFlashWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RfsCoeffSaveToFlashWrite) ProtoMessage() {}

func (x *RfsCoeffSaveToFlashWrite) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RfsCoeffSaveToFlashWrite.ProtoReflect.Descriptor instead.
func (*RfsCoeffSaveToFlashWrite) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{7}
}

func (x *RfsCoeffSaveToFlashWrite) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type RfsMeasureChannelPower struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frequency     *uint32                `protobuf:"varint,1,opt,name=frequency" json:"frequency,omitempty"`
	Power         *int32                 `protobuf:"zigzag32,2,opt,name=power" json:"power,omitempty"`
	Result        *int32                 `protobuf:"zigzag32,3,opt,name=result" json:"result,omitempty"`
	Delay         *uint32                `protobuf:"varint,4,opt,name=delay" json:"delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RfsMeasureChannelPower) Reset() {
	*x = RfsMeasureChannelPower{}
	mi := &file_amps_debug_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RfsMeasureChannelPower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RfsMeasureChannelPower) ProtoMessage() {}

func (x *RfsMeasureChannelPower) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RfsMeasureChannelPower.ProtoReflect.Descriptor instead.
func (*RfsMeasureChannelPower) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{8}
}

func (x *RfsMeasureChannelPower) GetFrequency() uint32 {
	if x != nil && x.Frequency != nil {
		return *x.Frequency
	}
	return 0
}

func (x *RfsMeasureChannelPower) GetPower() int32 {
	if x != nil && x.Power != nil {
		return *x.Power
	}
	return 0
}

func (x *RfsMeasureChannelPower) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

func (x *RfsMeasureChannelPower) GetDelay() uint32 {
	if x != nil && x.Delay != nil {
		return *x.Delay
	}
	return 0
}

type DownstreamAutoAlignRMSE struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RmseValues    []int32                `protobuf:"zigzag32,1,rep,name=rmse_values,json=rmseValues" json:"rmse_values,omitempty"`
	Result        *int32                 `protobuf:"zigzag32,2,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownstreamAutoAlignRMSE) Reset() {
	*x = DownstreamAutoAlignRMSE{}
	mi := &file_amps_debug_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownstreamAutoAlignRMSE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownstreamAutoAlignRMSE) ProtoMessage() {}

func (x *DownstreamAutoAlignRMSE) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownstreamAutoAlignRMSE.ProtoReflect.Descriptor instead.
func (*DownstreamAutoAlignRMSE) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{9}
}

func (x *DownstreamAutoAlignRMSE) GetRmseValues() []int32 {
	if x != nil {
		return x.RmseValues
	}
	return nil
}

func (x *DownstreamAutoAlignRMSE) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type UpstreamAutoAlignCSM struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CsmCableLen         *float32               `protobuf:"fixed32,1,opt,name=csm_cable_len,json=csmCableLen" json:"csm_cable_len,omitempty"`
	CsmGamma            *float32               `protobuf:"fixed32,2,opt,name=csm_gamma,json=csmGamma" json:"csm_gamma,omitempty"`
	CsmPhi              *float32               `protobuf:"fixed32,3,opt,name=csm_phi,json=csmPhi" json:"csm_phi,omitempty"`
	Result              *int32                 `protobuf:"zigzag32,4,opt,name=result" json:"result,omitempty"`
	TotalCompositePower *float32               `protobuf:"fixed32,5,opt,name=total_composite_power,json=totalCompositePower" json:"total_composite_power,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpstreamAutoAlignCSM) Reset() {
	*x = UpstreamAutoAlignCSM{}
	mi := &file_amps_debug_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamAutoAlignCSM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamAutoAlignCSM) ProtoMessage() {}

func (x *UpstreamAutoAlignCSM) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamAutoAlignCSM.ProtoReflect.Descriptor instead.
func (*UpstreamAutoAlignCSM) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{10}
}

func (x *UpstreamAutoAlignCSM) GetCsmCableLen() float32 {
	if x != nil && x.CsmCableLen != nil {
		return *x.CsmCableLen
	}
	return 0
}

func (x *UpstreamAutoAlignCSM) GetCsmGamma() float32 {
	if x != nil && x.CsmGamma != nil {
		return *x.CsmGamma
	}
	return 0
}

func (x *UpstreamAutoAlignCSM) GetCsmPhi() float32 {
	if x != nil && x.CsmPhi != nil {
		return *x.CsmPhi
	}
	return 0
}

func (x *UpstreamAutoAlignCSM) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

func (x *UpstreamAutoAlignCSM) GetTotalCompositePower() float32 {
	if x != nil && x.TotalCompositePower != nil {
		return *x.TotalCompositePower
	}
	return 0
}

type RfDetectorRead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frequency     *uint32                `protobuf:"varint,1,opt,name=frequency" json:"frequency,omitempty"`
	DetOutMv      *uint32                `protobuf:"varint,2,opt,name=det_out_mv,json=detOutMv" json:"det_out_mv,omitempty"`
	CalcPower     *int32                 `protobuf:"zigzag32,3,opt,name=calc_power,json=calcPower" json:"calc_power,omitempty"`
	Result        *int32                 `protobuf:"zigzag32,4,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RfDetectorRead) Reset() {
	*x = RfDetectorRead{}
	mi := &file_amps_debug_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RfDetectorRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RfDetectorRead) ProtoMessage() {}

func (x *RfDetectorRead) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RfDetectorRead.ProtoReflect.Descriptor instead.
func (*RfDetectorRead) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{11}
}

func (x *RfDetectorRead) GetFrequency() uint32 {
	if x != nil && x.Frequency != nil {
		return *x.Frequency
	}
	return 0
}

func (x *RfDetectorRead) GetDetOutMv() uint32 {
	if x != nil && x.DetOutMv != nil {
		return *x.DetOutMv
	}
	return 0
}

func (x *RfDetectorRead) GetCalcPower() int32 {
	if x != nil && x.CalcPower != nil {
		return *x.CalcPower
	}
	return 0
}

func (x *RfDetectorRead) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type AlscControl struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AutoModeEnable   *bool                  `protobuf:"varint,1,opt,name=auto_mode_enable,json=autoModeEnable" json:"auto_mode_enable,omitempty"`
	AutoModeInterval *uint32                `protobuf:"varint,2,opt,name=auto_mode_interval,json=autoModeInterval" json:"auto_mode_interval,omitempty"`
	// Types that are valid to be assigned to ManualOp:
	//
	//	*AlscControl_ManualTriggerFull
	//	*AlscControl_ManualTriggerDsOnly
	//	*AlscControl_ManualTriggerUsOnly
	//	*AlscControl_RmseCalculateTrigger
	ManualOp      isAlscControl_ManualOp `protobuf_oneof:"manual_op"`
	Result        *int32                 `protobuf:"zigzag32,7,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlscControl) Reset() {
	*x = AlscControl{}
	mi := &file_amps_debug_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlscControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlscControl) ProtoMessage() {}

func (x *AlscControl) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlscControl.ProtoReflect.Descriptor instead.
func (*AlscControl) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{12}
}

func (x *AlscControl) GetAutoModeEnable() bool {
	if x != nil && x.AutoModeEnable != nil {
		return *x.AutoModeEnable
	}
	return false
}

func (x *AlscControl) GetAutoModeInterval() uint32 {
	if x != nil && x.AutoModeInterval != nil {
		return *x.AutoModeInterval
	}
	return 0
}

func (x *AlscControl) GetManualOp() isAlscControl_ManualOp {
	if x != nil {
		return x.ManualOp
	}
	return nil
}

func (x *AlscControl) GetManualTriggerFull() bool {
	if x != nil {
		if x, ok := x.ManualOp.(*AlscControl_ManualTriggerFull); ok {
			return x.ManualTriggerFull
		}
	}
	return false
}

func (x *AlscControl) GetManualTriggerDsOnly() bool {
	if x != nil {
		if x, ok := x.ManualOp.(*AlscControl_ManualTriggerDsOnly); ok {
			return x.ManualTriggerDsOnly
		}
	}
	return false
}

func (x *AlscControl) GetManualTriggerUsOnly() bool {
	if x != nil {
		if x, ok := x.ManualOp.(*AlscControl_ManualTriggerUsOnly); ok {
			return x.ManualTriggerUsOnly
		}
	}
	return false
}

func (x *AlscControl) GetRmseCalculateTrigger() bool {
	if x != nil {
		if x, ok := x.ManualOp.(*AlscControl_RmseCalculateTrigger); ok {
			return x.RmseCalculateTrigger
		}
	}
	return false
}

func (x *AlscControl) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type isAlscControl_ManualOp interface {
	isAlscControl_ManualOp()
}

type AlscControl_ManualTriggerFull struct {
	ManualTriggerFull bool `protobuf:"varint,3,opt,name=manual_trigger_full,json=manualTriggerFull,oneof"`
}

type AlscControl_ManualTriggerDsOnly struct {
	ManualTriggerDsOnly bool `protobuf:"varint,4,opt,name=manual_trigger_ds_only,json=manualTriggerDsOnly,oneof"`
}

type AlscControl_ManualTriggerUsOnly struct {
	ManualTriggerUsOnly bool `protobuf:"varint,5,opt,name=manual_trigger_us_only,json=manualTriggerUsOnly,oneof"`
}

type AlscControl_RmseCalculateTrigger struct {
	RmseCalculateTrigger bool `protobuf:"varint,6,opt,name=rmse_calculate_trigger,json=rmseCalculateTrigger,oneof"`
}

func (*AlscControl_ManualTriggerFull) isAlscControl_ManualOp() {}

func (*AlscControl_ManualTriggerDsOnly) isAlscControl_ManualOp() {}

func (*AlscControl_ManualTriggerUsOnly) isAlscControl_ManualOp() {}

func (*AlscControl_RmseCalculateTrigger) isAlscControl_ManualOp() {}

type AlscStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AutoModeEnabled  *bool                  `protobuf:"varint,1,opt,name=auto_mode_enabled,json=autoModeEnabled" json:"auto_mode_enabled,omitempty"`
	AutoModeInterval *uint32                `protobuf:"varint,2,opt,name=auto_mode_interval,json=autoModeInterval" json:"auto_mode_interval,omitempty"`
	DsGainAdjust     *int32                 `protobuf:"zigzag32,4,opt,name=ds_gain_adjust,json=dsGainAdjust" json:"ds_gain_adjust,omitempty"`
	DsSlopeAdjust    *int32                 `protobuf:"zigzag32,5,opt,name=ds_slope_adjust,json=dsSlopeAdjust" json:"ds_slope_adjust,omitempty"`
	UsGainAdjust     *int32                 `protobuf:"zigzag32,6,opt,name=us_gain_adjust,json=usGainAdjust" json:"us_gain_adjust,omitempty"`
	UsSlopeAdjust    *int32                 `protobuf:"zigzag32,7,opt,name=us_slope_adjust,json=usSlopeAdjust" json:"us_slope_adjust,omitempty"`
	Result           *int32                 `protobuf:"zigzag32,8,opt,name=result" json:"result,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AlscStatus) Reset() {
	*x = AlscStatus{}
	mi := &file_amps_debug_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlscStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlscStatus) ProtoMessage() {}

func (x *AlscStatus) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlscStatus.ProtoReflect.Descriptor instead.
func (*AlscStatus) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{13}
}

func (x *AlscStatus) GetAutoModeEnabled() bool {
	if x != nil && x.AutoModeEnabled != nil {
		return *x.AutoModeEnabled
	}
	return false
}

func (x *AlscStatus) GetAutoModeInterval() uint32 {
	if x != nil && x.AutoModeInterval != nil {
		return *x.AutoModeInterval
	}
	return 0
}

func (x *AlscStatus) GetDsGainAdjust() int32 {
	if x != nil && x.DsGainAdjust != nil {
		return *x.DsGainAdjust
	}
	return 0
}

func (x *AlscStatus) GetDsSlopeAdjust() int32 {
	if x != nil && x.DsSlopeAdjust != nil {
		return *x.DsSlopeAdjust
	}
	return 0
}

func (x *AlscStatus) GetUsGainAdjust() int32 {
	if x != nil && x.UsGainAdjust != nil {
		return *x.UsGainAdjust
	}
	return 0
}

func (x *AlscStatus) GetUsSlopeAdjust() int32 {
	if x != nil && x.UsSlopeAdjust != nil {
		return *x.UsSlopeAdjust
	}
	return 0
}

func (x *AlscStatus) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type AlscStatistics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CalcRmse         *float32               `protobuf:"fixed32,1,opt,name=calc_rmse,json=calcRmse" json:"calc_rmse,omitempty"`
	PilotMeasuredPwr []int32                `protobuf:"zigzag32,2,rep,name=pilot_measured_pwr,json=pilotMeasuredPwr" json:"pilot_measured_pwr,omitempty"`
	Result           *int32                 `protobuf:"zigzag32,9,opt,name=result" json:"result,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AlscStatistics) Reset() {
	*x = AlscStatistics{}
	mi := &file_amps_debug_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlscStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlscStatistics) ProtoMessage() {}

func (x *AlscStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlscStatistics.ProtoReflect.Descriptor instead.
func (*AlscStatistics) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{14}
}

func (x *AlscStatistics) GetCalcRmse() float32 {
	if x != nil && x.CalcRmse != nil {
		return *x.CalcRmse
	}
	return 0
}

func (x *AlscStatistics) GetPilotMeasuredPwr() []int32 {
	if x != nil {
		return x.PilotMeasuredPwr
	}
	return nil
}

func (x *AlscStatistics) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type Db2MvTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idx           *uint32                `protobuf:"varint,1,opt,name=idx" json:"idx,omitempty"`
	DbValStart    *uint32                `protobuf:"varint,2,opt,name=db_val_start,json=dbValStart" json:"db_val_start,omitempty"`
	DbValEnd      *uint32                `protobuf:"varint,3,opt,name=db_val_end,json=dbValEnd" json:"db_val_end,omitempty"`
	DbStep        *uint32                `protobuf:"varint,4,opt,name=db_step,json=dbStep" json:"db_step,omitempty"`
	Temp          *uint32                `protobuf:"varint,5,opt,name=temp" json:"temp,omitempty"`
	MvValues      []int32                `protobuf:"zigzag32,6,rep,name=mv_values,json=mvValues" json:"mv_values,omitempty"`
	DbValues      []int32                `protobuf:"zigzag32,7,rep,name=db_values,json=dbValues" json:"db_values,omitempty"`
	Result        *int32                 `protobuf:"zigzag32,8,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Db2MvTable) Reset() {
	*x = Db2MvTable{}
	mi := &file_amps_debug_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Db2MvTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Db2MvTable) ProtoMessage() {}

func (x *Db2MvTable) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Db2MvTable.ProtoReflect.Descriptor instead.
func (*Db2MvTable) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{15}
}

func (x *Db2MvTable) GetIdx() uint32 {
	if x != nil && x.Idx != nil {
		return *x.Idx
	}
	return 0
}

func (x *Db2MvTable) GetDbValStart() uint32 {
	if x != nil && x.DbValStart != nil {
		return *x.DbValStart
	}
	return 0
}

func (x *Db2MvTable) GetDbValEnd() uint32 {
	if x != nil && x.DbValEnd != nil {
		return *x.DbValEnd
	}
	return 0
}

func (x *Db2MvTable) GetDbStep() uint32 {
	if x != nil && x.DbStep != nil {
		return *x.DbStep
	}
	return 0
}

func (x *Db2MvTable) GetTemp() uint32 {
	if x != nil && x.Temp != nil {
		return *x.Temp
	}
	return 0
}

func (x *Db2MvTable) GetMvValues() []int32 {
	if x != nil {
		return x.MvValues
	}
	return nil
}

func (x *Db2MvTable) GetDbValues() []int32 {
	if x != nil {
		return x.DbValues
	}
	return nil
}

func (x *Db2MvTable) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

type HGD_SetUpstreamAttn2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttenuationDB *float32               `protobuf:"fixed32,1,opt,name=attenuation_dB,json=attenuationDB" json:"attenuation_dB,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGD_SetUpstreamAttn2) Reset() {
	*x = HGD_SetUpstreamAttn2{}
	mi := &file_amps_debug_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGD_SetUpstreamAttn2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGD_SetUpstreamAttn2) ProtoMessage() {}

func (x *HGD_SetUpstreamAttn2) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGD_SetUpstreamAttn2.ProtoReflect.Descriptor instead.
func (*HGD_SetUpstreamAttn2) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{16}
}

func (x *HGD_SetUpstreamAttn2) GetAttenuationDB() float32 {
	if x != nil && x.AttenuationDB != nil {
		return *x.AttenuationDB
	}
	return 0
}

type HGD_GetUpstreamAttn2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttenuationDB *float32               `protobuf:"fixed32,1,opt,name=attenuation_dB,json=attenuationDB" json:"attenuation_dB,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGD_GetUpstreamAttn2) Reset() {
	*x = HGD_GetUpstreamAttn2{}
	mi := &file_amps_debug_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGD_GetUpstreamAttn2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGD_GetUpstreamAttn2) ProtoMessage() {}

func (x *HGD_GetUpstreamAttn2) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGD_GetUpstreamAttn2.ProtoReflect.Descriptor instead.
func (*HGD_GetUpstreamAttn2) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{17}
}

func (x *HGD_GetUpstreamAttn2) GetAttenuationDB() float32 {
	if x != nil && x.AttenuationDB != nil {
		return *x.AttenuationDB
	}
	return 0
}

type HGD_SetBandwidthMode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *BandwidthModeE        `protobuf:"varint,1,opt,name=value,enum=scte.amp.BandwidthModeE" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGD_SetBandwidthMode) Reset() {
	*x = HGD_SetBandwidthMode{}
	mi := &file_amps_debug_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGD_SetBandwidthMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGD_SetBandwidthMode) ProtoMessage() {}

func (x *HGD_SetBandwidthMode) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGD_SetBandwidthMode.ProtoReflect.Descriptor instead.
func (*HGD_SetBandwidthMode) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{18}
}

func (x *HGD_SetBandwidthMode) GetValue() BandwidthModeE {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return BandwidthModeE_BW_MODE_UNKNOWN
}

type HGD_GetBandwidthMode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *BandwidthModeE        `protobuf:"varint,1,opt,name=value,enum=scte.amp.BandwidthModeE" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGD_GetBandwidthMode) Reset() {
	*x = HGD_GetBandwidthMode{}
	mi := &file_amps_debug_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGD_GetBandwidthMode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGD_GetBandwidthMode) ProtoMessage() {}

func (x *HGD_GetBandwidthMode) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGD_GetBandwidthMode.ProtoReflect.Descriptor instead.
func (*HGD_GetBandwidthMode) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{19}
}

func (x *HGD_GetBandwidthMode) GetValue() BandwidthModeE {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return BandwidthModeE_BW_MODE_UNKNOWN
}

type HGD_SetMainWink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *uint32                `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGD_SetMainWink) Reset() {
	*x = HGD_SetMainWink{}
	mi := &file_amps_debug_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGD_SetMainWink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGD_SetMainWink) ProtoMessage() {}

func (x *HGD_SetMainWink) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGD_SetMainWink.ProtoReflect.Descriptor instead.
func (*HGD_SetMainWink) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{20}
}

func (x *HGD_SetMainWink) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type HGD_SetAuxWink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *uint32                `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Index         *uint32                `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGD_SetAuxWink) Reset() {
	*x = HGD_SetAuxWink{}
	mi := &file_amps_debug_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGD_SetAuxWink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGD_SetAuxWink) ProtoMessage() {}

func (x *HGD_SetAuxWink) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGD_SetAuxWink.ProtoReflect.Descriptor instead.
func (*HGD_SetAuxWink) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{21}
}

func (x *HGD_SetAuxWink) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *HGD_SetAuxWink) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

type Pilot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Frequency     *uint32                `protobuf:"varint,1,opt,name=frequency" json:"frequency,omitempty"`
	Level         *uint32                `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	Reference     *uint32                `protobuf:"varint,3,opt,name=reference" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pilot) Reset() {
	*x = Pilot{}
	mi := &file_amps_debug_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pilot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pilot) ProtoMessage() {}

func (x *Pilot) ProtoReflect() protoreflect.Message {
	mi := &file_amps_debug_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pilot.ProtoReflect.Descriptor instead.
func (*Pilot) Descriptor() ([]byte, []int) {
	return file_amps_debug_proto_rawDescGZIP(), []int{22}
}

func (x *Pilot) GetFrequency() uint32 {
	if x != nil && x.Frequency != nil {
		return *x.Frequency
	}
	return 0
}

func (x *Pilot) GetLevel() uint32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *Pilot) GetReference() uint32 {
	if x != nil && x.Reference != nil {
		return *x.Reference
	}
	return 0
}

var File_amps_debug_proto protoreflect.FileDescriptor

const file_amps_debug_proto_rawDesc = "" +
	"\n" +
	"\x10amps/debug.proto\x12\bscte.amp\x1a\x11amps/common.proto\"f\n" +
	"\x0eSetOutputLevel\x12>\n" +
	"\routput_select\x18\x01 \x01(\x0e2\x19.scte.amp.output_select_eR\foutputSelect\x12\x14\n" +
	"\x05level\x18\x02 \x01(\bR\x05level\"=\n" +
	"\x11GetRfMixerRegRead\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\x05R\x03idx\x12\x16\n" +
	"\x06result\x18\x02 \x01(\x11R\x06result\"Z\n" +
	"\x16SendRfMixerSingleWrite\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\rR\x04addr\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value\x12\x16\n" +
	"\x06result\x18\x03 \x01(\x11R\x06result\"W\n" +
	"\x15SendRfMixerPnSetWrite\x12\x12\n" +
	"\x04path\x18\x01 \x01(\rR\x04path\x12\x12\n" +
	"\x04data\x18\x02 \x03(\rR\x04data\x12\x16\n" +
	"\x06result\x18\x03 \x01(\x11R\x06result\"(\n" +
	"\x0eGetUpTimeCount\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x11R\x06result\"F\n" +
	"\x12RfsScanModeDisable\x12\x18\n" +
	"\adisable\x18\x01 \x01(\bR\adisable\x12\x16\n" +
	"\x06result\x18\x02 \x01(\x11R\x06result\"\x8d\x01\n" +
	"\x0fRfsCoeffBlockRW\x12 \n" +
	"\vtableNumber\x18\x01 \x01(\rR\vtableNumber\x12 \n" +
	"\vblockNumber\x18\x02 \x01(\rR\vblockNumber\x12\x1e\n" +
	"\n" +
	"coeffTable\x18\x03 \x03(\x11R\n" +
	"coeffTable\x12\x16\n" +
	"\x06result\x18\x04 \x01(\x11R\x06result\"2\n" +
	"\x18RfsCoeffSaveToFlashWrite\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x11R\x06result\"z\n" +
	"\x16RfsMeasureChannelPower\x12\x1c\n" +
	"\tfrequency\x18\x01 \x01(\rR\tfrequency\x12\x14\n" +
	"\x05power\x18\x02 \x01(\x11R\x05power\x12\x16\n" +
	"\x06result\x18\x03 \x01(\x11R\x06result\x12\x14\n" +
	"\x05delay\x18\x04 \x01(\rR\x05delay\"R\n" +
	"\x17DownstreamAutoAlignRMSE\x12\x1f\n" +
	"\vrmse_values\x18\x01 \x03(\x11R\n" +
	"rmseValues\x12\x16\n" +
	"\x06result\x18\x02 \x01(\x11R\x06result\"\xbc\x01\n" +
	"\x14UpstreamAutoAlignCSM\x12\"\n" +
	"\rcsm_cable_len\x18\x01 \x01(\x02R\vcsmCableLen\x12\x1b\n" +
	"\tcsm_gamma\x18\x02 \x01(\x02R\bcsmGamma\x12\x17\n" +
	"\acsm_phi\x18\x03 \x01(\x02R\x06csmPhi\x12\x16\n" +
	"\x06result\x18\x04 \x01(\x11R\x06result\x122\n" +
	"\x15total_composite_power\x18\x05 \x01(\x02R\x13totalCompositePower\"\x83\x01\n" +
	"\x0eRfDetectorRead\x12\x1c\n" +
	"\tfrequency\x18\x01 \x01(\rR\tfrequency\x12\x1c\n" +
	"\n" +
	"det_out_mv\x18\x02 \x01(\rR\bdetOutMv\x12\x1d\n" +
	"\n" +
	"calc_power\x18\x03 \x01(\x11R\tcalcPower\x12\x16\n" +
	"\x06result\x18\x04 \x01(\x11R\x06result\"\xe2\x02\n" +
	"\vAlscControl\x12(\n" +
	"\x10auto_mode_enable\x18\x01 \x01(\bR\x0eautoModeEnable\x12,\n" +
	"\x12auto_mode_interval\x18\x02 \x01(\rR\x10autoModeInterval\x120\n" +
	"\x13manual_trigger_full\x18\x03 \x01(\bH\x00R\x11manualTriggerFull\x125\n" +
	"\x16manual_trigger_ds_only\x18\x04 \x01(\bH\x00R\x13manualTriggerDsOnly\x125\n" +
	"\x16manual_trigger_us_only\x18\x05 \x01(\bH\x00R\x13manualTriggerUsOnly\x126\n" +
	"\x16rmse_calculate_trigger\x18\x06 \x01(\bH\x00R\x14rmseCalculateTrigger\x12\x16\n" +
	"\x06result\x18\a \x01(\x11R\x06resultB\v\n" +
	"\tmanual_op\"\x9a\x02\n" +
	"\n" +
	"AlscStatus\x12*\n" +
	"\x11auto_mode_enabled\x18\x01 \x01(\bR\x0fautoModeEnabled\x12,\n" +
	"\x12auto_mode_interval\x18\x02 \x01(\rR\x10autoModeInterval\x12$\n" +
	"\x0eds_gain_adjust\x18\x04 \x01(\x11R\fdsGainAdjust\x12&\n" +
	"\x0fds_slope_adjust\x18\x05 \x01(\x11R\rdsSlopeAdjust\x12$\n" +
	"\x0eus_gain_adjust\x18\x06 \x01(\x11R\fusGainAdjust\x12&\n" +
	"\x0fus_slope_adjust\x18\a \x01(\x11R\rusSlopeAdjust\x12\x16\n" +
	"\x06result\x18\b \x01(\x11R\x06result\"s\n" +
	"\x0eAlscStatistics\x12\x1b\n" +
	"\tcalc_rmse\x18\x01 \x01(\x02R\bcalcRmse\x12,\n" +
	"\x12pilot_measured_pwr\x18\x02 \x03(\x11R\x10pilotMeasuredPwr\x12\x16\n" +
	"\x06result\x18\t \x01(\x11R\x06result\"\xdd\x01\n" +
	"\n" +
	"Db2MvTable\x12\x10\n" +
	"\x03idx\x18\x01 \x01(\rR\x03idx\x12 \n" +
	"\fdb_val_start\x18\x02 \x01(\rR\n" +
	"dbValStart\x12\x1c\n" +
	"\n" +
	"db_val_end\x18\x03 \x01(\rR\bdbValEnd\x12\x17\n" +
	"\adb_step\x18\x04 \x01(\rR\x06dbStep\x12\x12\n" +
	"\x04temp\x18\x05 \x01(\rR\x04temp\x12\x1b\n" +
	"\tmv_values\x18\x06 \x03(\x11R\bmvValues\x12\x1b\n" +
	"\tdb_values\x18\a \x03(\x11R\bdbValues\x12\x16\n" +
	"\x06result\x18\b \x01(\x11R\x06result\"=\n" +
	"\x14HGD_SetUpstreamAttn2\x12%\n" +
	"\x0eattenuation_dB\x18\x01 \x01(\x02R\rattenuationDB\"=\n" +
	"\x14HGD_GetUpstreamAttn2\x12%\n" +
	"\x0eattenuation_dB\x18\x01 \x01(\x02R\rattenuationDB\"H\n" +
	"\x14HGD_SetBandwidthMode\x120\n" +
	"\x05value\x18\x01 \x01(\x0e2\x1a.scte.amp.bandwidth_mode_eR\x05value\"H\n" +
	"\x14HGD_GetBandwidthMode\x120\n" +
	"\x05value\x18\x01 \x01(\x0e2\x1a.scte.amp.bandwidth_mode_eR\x05value\"'\n" +
	"\x0fHGD_SetMainWink\x12\x14\n" +
	"\x05value\x18\x01 \x01(\rR\x05value\"<\n" +
	"\x0eHGD_SetAuxWink\x12\x14\n" +
	"\x05value\x18\x01 \x01(\rR\x05value\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\"Y\n" +
	"\x05Pilot\x12\x1c\n" +
	"\tfrequency\x18\x01 \x01(\rR\tfrequency\x12\x14\n" +
	"\x05level\x18\x02 \x01(\rR\x05level\x12\x1c\n" +
	"\treference\x18\x03 \x01(\rR\treference*\xd2\x01\n" +
	"\x0foutput_select_e\x12\x0e\n" +
	"\n" +
	"OUTSEL_SW1\x10\x00\x12\x0e\n" +
	"\n" +
	"OUTSEL_SW2\x10\x01\x12\x15\n" +
	"\x11OUTSEL_MIXER_MODE\x10\x02\x12\x17\n" +
	"\x13OUTSEL_MIXER_ENABLE\x10\x03\x12\x14\n" +
	"\x10OUTSEL_MIXER_ENX\x10\x04\x12\x15\n" +
	"\x11OUTSEL_MIXER_RSTB\x10\x05\x12\x13\n" +
	"\x0fOUTSEL_INPUT_TP\x10\x06\x12\x14\n" +
	"\x10OUTSEL_OUTPUT_TP\x10\a\x12\x17\n" +
	"\x13OUTSEL_CURRENT_CTRL\x10\bB=\n" +
	"\rorg.scte.ampsP\x01Z*github.com/enshure/scte-go/amps_go;scteampP\x00"

var (
	file_amps_debug_proto_rawDescOnce sync.Once
	file_amps_debug_proto_rawDescData []byte
)

func file_amps_debug_proto_rawDescGZIP() []byte {
	file_amps_debug_proto_rawDescOnce.Do(func() {
		file_amps_debug_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amps_debug_proto_rawDesc), len(file_amps_debug_proto_rawDesc)))
	})
	return file_amps_debug_proto_rawDescData
}

var file_amps_debug_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_amps_debug_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_amps_debug_proto_goTypes = []any{
	(OutputSelectE)(0),               // 0: scte.amp.output_select_e
	(*SetOutputLevel)(nil),           // 1: scte.amp.SetOutputLevel
	(*GetRfMixerRegRead)(nil),        // 2: scte.amp.GetRfMixerRegRead
	(*SendRfMixerSingleWrite)(nil),   // 3: scte.amp.SendRfMixerSingleWrite
	(*SendRfMixerPnSetWrite)(nil),    // 4: scte.amp.SendRfMixerPnSetWrite
	(*GetUpTimeCount)(nil),           // 5: scte.amp.GetUpTimeCount
	(*RfsScanModeDisable)(nil),       // 6: scte.amp.RfsScanModeDisable
	(*RfsCoeffBlockRW)(nil),          // 7: scte.amp.RfsCoeffBlockRW
	(*RfsCoeffSaveToFlashWrite)(nil), // 8: scte.amp.RfsCoeffSaveToFlashWrite
	(*RfsMeasureChannelPower)(nil),   // 9: scte.amp.RfsMeasureChannelPower
	(*DownstreamAutoAlignRMSE)(nil),  // 10: scte.amp.DownstreamAutoAlignRMSE
	(*UpstreamAutoAlignCSM)(nil),     // 11: scte.amp.UpstreamAutoAlignCSM
	(*RfDetectorRead)(nil),           // 12: scte.amp.RfDetectorRead
	(*AlscControl)(nil),              // 13: scte.amp.AlscControl
	(*AlscStatus)(nil),               // 14: scte.amp.AlscStatus
	(*AlscStatistics)(nil),           // 15: scte.amp.AlscStatistics
	(*Db2MvTable)(nil),               // 16: scte.amp.Db2MvTable
	(*HGD_SetUpstreamAttn2)(nil),     // 17: scte.amp.HGD_SetUpstreamAttn2
	(*HGD_GetUpstreamAttn2)(nil),     // 18: scte.amp.HGD_GetUpstreamAttn2
	(*HGD_SetBandwidthMode)(nil),     // 19: scte.amp.HGD_SetBandwidthMode
	(*HGD_GetBandwidthMode)(nil),     // 20: scte.amp.HGD_GetBandwidthMode
	(*HGD_SetMainWink)(nil),          // 21: scte.amp.HGD_SetMainWink
	(*HGD_SetAuxWink)(nil),           // 22: scte.amp.HGD_SetAuxWink
	(*Pilot)(nil),                    // 23: scte.amp.Pilot
	(BandwidthModeE)(0),              // 24: scte.amp.bandwidth_mode_e
}
var file_amps_debug_proto_depIdxs = []int32{
	0,  // 0: scte.amp.SetOutputLevel.output_select:type_name -> scte.amp.output_select_e
	24, // 1: scte.amp.HGD_SetBandwidthMode.value:type_name -> scte.amp.bandwidth_mode_e
	24, // 2: scte.amp.HGD_GetBandwidthMode.value:type_name -> scte.amp.bandwidth_mode_e
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_amps_debug_proto_init() }
func file_amps_debug_proto_init() {
	if File_amps_debug_proto != nil {
		return
	}
	file_amps_common_proto_init()
	file_amps_debug_proto_msgTypes[12].OneofWrappers = []any{
		(*AlscControl_ManualTriggerFull)(nil),
		(*AlscControl_ManualTriggerDsOnly)(nil),
		(*AlscControl_ManualTriggerUsOnly)(nil),
		(*AlscControl_RmseCalculateTrigger)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amps_debug_proto_rawDesc), len(file_amps_debug_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_amps_debug_proto_goTypes,
		DependencyIndexes: file_amps_debug_proto_depIdxs,
		EnumInfos:         file_amps_debug_proto_enumTypes,
		MessageInfos:      file_amps_debug_proto_msgTypes,
	}.Build()
	File_amps_debug_proto = out.File
	file_amps_debug_proto_goTypes = nil
	file_amps_debug_proto_depIdxs = nil
}
