// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: amps/reset.proto

package scteamp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResetCapabilities struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ResetTypesSupported *uint32                `protobuf:"varint,1,opt,name=reset_types_supported,json=resetTypesSupported" json:"reset_types_supported,omitempty"`
	ResetHistorySize    *uint32                `protobuf:"varint,2,opt,name=reset_history_size,json=resetHistorySize" json:"reset_history_size,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ResetCapabilities) Reset() {
	*x = ResetCapabilities{}
	mi := &file_amps_reset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetCapabilities) ProtoMessage() {}

func (x *ResetCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_amps_reset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetCapabilities.ProtoReflect.Descriptor instead.
func (*ResetCapabilities) Descriptor() ([]byte, []int) {
	return file_amps_reset_proto_rawDescGZIP(), []int{0}
}

func (x *ResetCapabilities) GetResetTypesSupported() uint32 {
	if x != nil && x.ResetTypesSupported != nil {
		return *x.ResetTypesSupported
	}
	return 0
}

func (x *ResetCapabilities) GetResetHistorySize() uint32 {
	if x != nil && x.ResetHistorySize != nil {
		return *x.ResetHistorySize
	}
	return 0
}

type ResetHistoryStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Index          *uint32                `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	ResetTimestamp *string                `protobuf:"bytes,2,opt,name=reset_timestamp,json=resetTimestamp" json:"reset_timestamp,omitempty"`
	Type           *ResetTypeE            `protobuf:"varint,3,opt,name=type,enum=scte.amp.ResetTypeE" json:"type,omitempty"`
	Reason         *string                `protobuf:"bytes,4,opt,name=reason" json:"reason,omitempty"`
	EventIdRef     *uint32                `protobuf:"varint,5,opt,name=event_id_ref,json=eventIdRef" json:"event_id_ref,omitempty"`
	RecoveryTime   *uint32                `protobuf:"varint,6,opt,name=recovery_time,json=recoveryTime" json:"recovery_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResetHistoryStatus) Reset() {
	*x = ResetHistoryStatus{}
	mi := &file_amps_reset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetHistoryStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetHistoryStatus) ProtoMessage() {}

func (x *ResetHistoryStatus) ProtoReflect() protoreflect.Message {
	mi := &file_amps_reset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetHistoryStatus.ProtoReflect.Descriptor instead.
func (*ResetHistoryStatus) Descriptor() ([]byte, []int) {
	return file_amps_reset_proto_rawDescGZIP(), []int{1}
}

func (x *ResetHistoryStatus) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *ResetHistoryStatus) GetResetTimestamp() string {
	if x != nil && x.ResetTimestamp != nil {
		return *x.ResetTimestamp
	}
	return ""
}

func (x *ResetHistoryStatus) GetType() ResetTypeE {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ResetTypeE_SOFT_RESET
}

func (x *ResetHistoryStatus) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

func (x *ResetHistoryStatus) GetEventIdRef() uint32 {
	if x != nil && x.EventIdRef != nil {
		return *x.EventIdRef
	}
	return 0
}

func (x *ResetHistoryStatus) GetRecoveryTime() uint32 {
	if x != nil && x.RecoveryTime != nil {
		return *x.RecoveryTime
	}
	return 0
}

type Reset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *ResetTypeE            `protobuf:"varint,1,opt,name=type,enum=scte.amp.ResetTypeE" json:"type,omitempty"`
	Result        *bool                  `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reset) Reset() {
	*x = Reset{}
	mi := &file_amps_reset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reset) ProtoMessage() {}

func (x *Reset) ProtoReflect() protoreflect.Message {
	mi := &file_amps_reset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reset.ProtoReflect.Descriptor instead.
func (*Reset) Descriptor() ([]byte, []int) {
	return file_amps_reset_proto_rawDescGZIP(), []int{2}
}

func (x *Reset) GetType() ResetTypeE {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ResetTypeE_SOFT_RESET
}

func (x *Reset) GetResult() bool {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return false
}

type DisableAutoReboot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timeout       *uint32                `protobuf:"varint,1,opt,name=timeout" json:"timeout,omitempty"`
	Result        *bool                  `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableAutoReboot) Reset() {
	*x = DisableAutoReboot{}
	mi := &file_amps_reset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableAutoReboot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableAutoReboot) ProtoMessage() {}

func (x *DisableAutoReboot) ProtoReflect() protoreflect.Message {
	mi := &file_amps_reset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableAutoReboot.ProtoReflect.Descriptor instead.
func (*DisableAutoReboot) Descriptor() ([]byte, []int) {
	return file_amps_reset_proto_rawDescGZIP(), []int{3}
}

func (x *DisableAutoReboot) GetTimeout() uint32 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

func (x *DisableAutoReboot) GetResult() bool {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return false
}

type EnableAutoReboot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *bool                  `protobuf:"varint,2,opt,name=result" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableAutoReboot) Reset() {
	*x = EnableAutoReboot{}
	mi := &file_amps_reset_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableAutoReboot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableAutoReboot) ProtoMessage() {}

func (x *EnableAutoReboot) ProtoReflect() protoreflect.Message {
	mi := &file_amps_reset_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableAutoReboot.ProtoReflect.Descriptor instead.
func (*EnableAutoReboot) Descriptor() ([]byte, []int) {
	return file_amps_reset_proto_rawDescGZIP(), []int{4}
}

func (x *EnableAutoReboot) GetResult() bool {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return false
}

var File_amps_reset_proto protoreflect.FileDescriptor

const file_amps_reset_proto_rawDesc = "" +
	"\n" +
	"\x10amps/reset.proto\x12\bscte.amp\x1a\x11amps/common.proto\"u\n" +
	"\x11ResetCapabilities\x122\n" +
	"\x15reset_types_supported\x18\x01 \x01(\rR\x13resetTypesSupported\x12,\n" +
	"\x12reset_history_size\x18\x02 \x01(\rR\x10resetHistorySize\"\xde\x01\n" +
	"\x12ResetHistoryStatus\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12'\n" +
	"\x0freset_timestamp\x18\x02 \x01(\tR\x0eresetTimestamp\x12*\n" +
	"\x04type\x18\x03 \x01(\x0e2\x16.scte.amp.reset_type_eR\x04type\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12 \n" +
	"\fevent_id_ref\x18\x05 \x01(\rR\n" +
	"eventIdRef\x12#\n" +
	"\rrecovery_time\x18\x06 \x01(\rR\frecoveryTime\"K\n" +
	"\x05Reset\x12*\n" +
	"\x04type\x18\x01 \x01(\x0e2\x16.scte.amp.reset_type_eR\x04type\x12\x16\n" +
	"\x06result\x18\x02 \x01(\bR\x06result\"E\n" +
	"\x11DisableAutoReboot\x12\x18\n" +
	"\atimeout\x18\x01 \x01(\rR\atimeout\x12\x16\n" +
	"\x06result\x18\x02 \x01(\bR\x06result\"*\n" +
	"\x10EnableAutoReboot\x12\x16\n" +
	"\x06result\x18\x02 \x01(\bR\x06resultB6Z4github.com/enshure/scte-go/amps_go;scteampP\x00"

var (
	file_amps_reset_proto_rawDescOnce sync.Once
	file_amps_reset_proto_rawDescData []byte
)

func file_amps_reset_proto_rawDescGZIP() []byte {
	file_amps_reset_proto_rawDescOnce.Do(func() {
		file_amps_reset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amps_reset_proto_rawDesc), len(file_amps_reset_proto_rawDesc)))
	})
	return file_amps_reset_proto_rawDescData
}

var file_amps_reset_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_amps_reset_proto_goTypes = []any{
	(*ResetCapabilities)(nil),  // 0: scte.amp.ResetCapabilities
	(*ResetHistoryStatus)(nil), // 1: scte.amp.ResetHistoryStatus
	(*Reset)(nil),              // 2: scte.amp.Reset
	(*DisableAutoReboot)(nil),  // 3: scte.amp.DisableAutoReboot
	(*EnableAutoReboot)(nil),   // 4: scte.amp.EnableAutoReboot
	(ResetTypeE)(0),            // 5: scte.amp.reset_type_e
}
var file_amps_reset_proto_depIdxs = []int32{
	5, // 0: scte.amp.ResetHistoryStatus.type:type_name -> scte.amp.reset_type_e
	5, // 1: scte.amp.Reset.type:type_name -> scte.amp.reset_type_e
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_amps_reset_proto_init() }
func file_amps_reset_proto_init() {
	if File_amps_reset_proto != nil {
		return
	}
	file_amps_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amps_reset_proto_rawDesc), len(file_amps_reset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_amps_reset_proto_goTypes,
		DependencyIndexes: file_amps_reset_proto_depIdxs,
		MessageInfos:      file_amps_reset_proto_msgTypes,
	}.Build()
	File_amps_reset_proto = out.File
	file_amps_reset_proto_goTypes = nil
	file_amps_reset_proto_depIdxs = nil
}
