// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: amps/rf_capabilities_grp.proto

package scteamp

import (
	common_go "github.com/enshure/scte-go/common_go"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RfSpectrumCaptureTypeE int32

const (
	RfSpectrumCaptureTypeE_PORT1_UPSTREAM      RfSpectrumCaptureTypeE = 1
	RfSpectrumCaptureTypeE_PORT1_DOWNSTREAM    RfSpectrumCaptureTypeE = 2
	RfSpectrumCaptureTypeE_PORT2_UPSTREAM      RfSpectrumCaptureTypeE = 4
	RfSpectrumCaptureTypeE_PORT2_DOWNSTREAM    RfSpectrumCaptureTypeE = 8
	RfSpectrumCaptureTypeE_PORT3_UPSTREAM      RfSpectrumCaptureTypeE = 16
	RfSpectrumCaptureTypeE_PORT3_DOWNSTREAM    RfSpectrumCaptureTypeE = 32
	RfSpectrumCaptureTypeE_PORT4_UPSTREAM      RfSpectrumCaptureTypeE = 64
	RfSpectrumCaptureTypeE_PORT4_DOWNSTREAM    RfSpectrumCaptureTypeE = 128
	RfSpectrumCaptureTypeE_PORT_UPSTREAM_ALL   RfSpectrumCaptureTypeE = 256
	RfSpectrumCaptureTypeE_PORT_DOWNSTREAM_ALL RfSpectrumCaptureTypeE = 512
)

// Enum value maps for RfSpectrumCaptureTypeE.
var (
	RfSpectrumCaptureTypeE_name = map[int32]string{
		1:   "PORT1_UPSTREAM",
		2:   "PORT1_DOWNSTREAM",
		4:   "PORT2_UPSTREAM",
		8:   "PORT2_DOWNSTREAM",
		16:  "PORT3_UPSTREAM",
		32:  "PORT3_DOWNSTREAM",
		64:  "PORT4_UPSTREAM",
		128: "PORT4_DOWNSTREAM",
		256: "PORT_UPSTREAM_ALL",
		512: "PORT_DOWNSTREAM_ALL",
	}
	RfSpectrumCaptureTypeE_value = map[string]int32{
		"PORT1_UPSTREAM":      1,
		"PORT1_DOWNSTREAM":    2,
		"PORT2_UPSTREAM":      4,
		"PORT2_DOWNSTREAM":    8,
		"PORT3_UPSTREAM":      16,
		"PORT3_DOWNSTREAM":    32,
		"PORT4_UPSTREAM":      64,
		"PORT4_DOWNSTREAM":    128,
		"PORT_UPSTREAM_ALL":   256,
		"PORT_DOWNSTREAM_ALL": 512,
	}
)

func (x RfSpectrumCaptureTypeE) Enum() *RfSpectrumCaptureTypeE {
	p := new(RfSpectrumCaptureTypeE)
	*p = x
	return p
}

func (x RfSpectrumCaptureTypeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RfSpectrumCaptureTypeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_rf_capabilities_grp_proto_enumTypes[0].Descriptor()
}

func (RfSpectrumCaptureTypeE) Type() protoreflect.EnumType {
	return &file_amps_rf_capabilities_grp_proto_enumTypes[0]
}

func (x RfSpectrumCaptureTypeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RfSpectrumCaptureTypeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RfSpectrumCaptureTypeE(num)
	return nil
}

// Deprecated: Use RfSpectrumCaptureTypeE.Descriptor instead.
func (RfSpectrumCaptureTypeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_rf_capabilities_grp_proto_rawDescGZIP(), []int{0}
}

type RfPortIndexE int32

const (
	RfPortIndexE_RF_PORT_INDEX_2 RfPortIndexE = 2
	RfPortIndexE_RF_PORT_INDEX_3 RfPortIndexE = 3
	RfPortIndexE_RF_PORT_INDEX_4 RfPortIndexE = 4
	RfPortIndexE_RF_PORT_ALL     RfPortIndexE = 255
)

// Enum value maps for RfPortIndexE.
var (
	RfPortIndexE_name = map[int32]string{
		2:   "RF_PORT_INDEX_2",
		3:   "RF_PORT_INDEX_3",
		4:   "RF_PORT_INDEX_4",
		255: "RF_PORT_ALL",
	}
	RfPortIndexE_value = map[string]int32{
		"RF_PORT_INDEX_2": 2,
		"RF_PORT_INDEX_3": 3,
		"RF_PORT_INDEX_4": 4,
		"RF_PORT_ALL":     255,
	}
)

func (x RfPortIndexE) Enum() *RfPortIndexE {
	p := new(RfPortIndexE)
	*p = x
	return p
}

func (x RfPortIndexE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RfPortIndexE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_rf_capabilities_grp_proto_enumTypes[1].Descriptor()
}

func (RfPortIndexE) Type() protoreflect.EnumType {
	return &file_amps_rf_capabilities_grp_proto_enumTypes[1]
}

func (x RfPortIndexE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RfPortIndexE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RfPortIndexE(num)
	return nil
}

// Deprecated: Use RfPortIndexE.Descriptor instead.
func (RfPortIndexE) EnumDescriptor() ([]byte, []int) {
	return file_amps_rf_capabilities_grp_proto_rawDescGZIP(), []int{1}
}

type AlignmentTypeE int32

const (
	AlignmentTypeE_ALIGNMENT_TYPE_DS_AUTO   AlignmentTypeE = 1
	AlignmentTypeE_ALIGNMENT_TYPE_US_AUTO   AlignmentTypeE = 2
	AlignmentTypeE_ALIGNMENT_TYPE_DS_MANUAL AlignmentTypeE = 4
	AlignmentTypeE_ALIGNMENT_TYPE_US_MANUAL AlignmentTypeE = 8
)

// Enum value maps for AlignmentTypeE.
var (
	AlignmentTypeE_name = map[int32]string{
		1: "ALIGNMENT_TYPE_DS_AUTO",
		2: "ALIGNMENT_TYPE_US_AUTO",
		4: "ALIGNMENT_TYPE_DS_MANUAL",
		8: "ALIGNMENT_TYPE_US_MANUAL",
	}
	AlignmentTypeE_value = map[string]int32{
		"ALIGNMENT_TYPE_DS_AUTO":   1,
		"ALIGNMENT_TYPE_US_AUTO":   2,
		"ALIGNMENT_TYPE_DS_MANUAL": 4,
		"ALIGNMENT_TYPE_US_MANUAL": 8,
	}
)

func (x AlignmentTypeE) Enum() *AlignmentTypeE {
	p := new(AlignmentTypeE)
	*p = x
	return p
}

func (x AlignmentTypeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlignmentTypeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_rf_capabilities_grp_proto_enumTypes[2].Descriptor()
}

func (AlignmentTypeE) Type() protoreflect.EnumType {
	return &file_amps_rf_capabilities_grp_proto_enumTypes[2]
}

func (x AlignmentTypeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AlignmentTypeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AlignmentTypeE(num)
	return nil
}

// Deprecated: Use AlignmentTypeE.Descriptor instead.
func (AlignmentTypeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_rf_capabilities_grp_proto_rawDescGZIP(), []int{2}
}

type RfLevelControlTypeE int32

const (
	RfLevelControlTypeE_RF_LEVEL_CONTROL_OTHER                        RfLevelControlTypeE = 0
	RfLevelControlTypeE_RF_LEVEL_CONTROL_UNKNOWN                      RfLevelControlTypeE = 1
	RfLevelControlTypeE_RF_LEVEL_CONTROL_QUASI_AGC                    RfLevelControlTypeE = 2
	RfLevelControlTypeE_RF_LEVEL_CONTROL_THERMAL_LEVEL_CONTROL        RfLevelControlTypeE = 3
	RfLevelControlTypeE_RF_LEVEL_CONTROL_THERMAL_LEVEL_CONTROL_SELECT RfLevelControlTypeE = 4
)

// Enum value maps for RfLevelControlTypeE.
var (
	RfLevelControlTypeE_name = map[int32]string{
		0: "RF_LEVEL_CONTROL_OTHER",
		1: "RF_LEVEL_CONTROL_UNKNOWN",
		2: "RF_LEVEL_CONTROL_QUASI_AGC",
		3: "RF_LEVEL_CONTROL_THERMAL_LEVEL_CONTROL",
		4: "RF_LEVEL_CONTROL_THERMAL_LEVEL_CONTROL_SELECT",
	}
	RfLevelControlTypeE_value = map[string]int32{
		"RF_LEVEL_CONTROL_OTHER":                        0,
		"RF_LEVEL_CONTROL_UNKNOWN":                      1,
		"RF_LEVEL_CONTROL_QUASI_AGC":                    2,
		"RF_LEVEL_CONTROL_THERMAL_LEVEL_CONTROL":        3,
		"RF_LEVEL_CONTROL_THERMAL_LEVEL_CONTROL_SELECT": 4,
	}
)

func (x RfLevelControlTypeE) Enum() *RfLevelControlTypeE {
	p := new(RfLevelControlTypeE)
	*p = x
	return p
}

func (x RfLevelControlTypeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RfLevelControlTypeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_rf_capabilities_grp_proto_enumTypes[3].Descriptor()
}

func (RfLevelControlTypeE) Type() protoreflect.EnumType {
	return &file_amps_rf_capabilities_grp_proto_enumTypes[3]
}

func (x RfLevelControlTypeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RfLevelControlTypeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RfLevelControlTypeE(num)
	return nil
}

// Deprecated: Use RfLevelControlTypeE.Descriptor instead.
func (RfLevelControlTypeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_rf_capabilities_grp_proto_rawDescGZIP(), []int{3}
}

type StageTypeE int32

const (
	StageTypeE_STAGE_TYPE_OTHER      StageTypeE = 0
	StageTypeE_STAGE_TYPE_UNKNOWN    StageTypeE = 1
	StageTypeE_STAGE_TYPE_ATTENUATOR StageTypeE = 2
	StageTypeE_STAGE_TYPE_EQUALIZER  StageTypeE = 3
)

// Enum value maps for StageTypeE.
var (
	StageTypeE_name = map[int32]string{
		0: "STAGE_TYPE_OTHER",
		1: "STAGE_TYPE_UNKNOWN",
		2: "STAGE_TYPE_ATTENUATOR",
		3: "STAGE_TYPE_EQUALIZER",
	}
	StageTypeE_value = map[string]int32{
		"STAGE_TYPE_OTHER":      0,
		"STAGE_TYPE_UNKNOWN":    1,
		"STAGE_TYPE_ATTENUATOR": 2,
		"STAGE_TYPE_EQUALIZER":  3,
	}
)

func (x StageTypeE) Enum() *StageTypeE {
	p := new(StageTypeE)
	*p = x
	return p
}

func (x StageTypeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StageTypeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_rf_capabilities_grp_proto_enumTypes[4].Descriptor()
}

func (StageTypeE) Type() protoreflect.EnumType {
	return &file_amps_rf_capabilities_grp_proto_enumTypes[4]
}

func (x StageTypeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StageTypeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StageTypeE(num)
	return nil
}

// Deprecated: Use StageTypeE.Descriptor instead.
func (StageTypeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_rf_capabilities_grp_proto_rawDescGZIP(), []int{4}
}

type StageLocationE int32

const (
	StageLocationE_STAGE_LOCATION_OTHER       StageLocationE = 0
	StageLocationE_STAGE_LOCATION_UNKNOWN     StageLocationE = 1
	StageLocationE_STAGE_LOCATION_INPUT       StageLocationE = 2
	StageLocationE_STAGE_LOCATION_INTER_STAGE StageLocationE = 3
	StageLocationE_STAGE_LOCATION_OUTPUT      StageLocationE = 4
	StageLocationE_STAGE_LOCATION_CUMULATIVE  StageLocationE = 5
)

// Enum value maps for StageLocationE.
var (
	StageLocationE_name = map[int32]string{
		0: "STAGE_LOCATION_OTHER",
		1: "STAGE_LOCATION_UNKNOWN",
		2: "STAGE_LOCATION_INPUT",
		3: "STAGE_LOCATION_INTER_STAGE",
		4: "STAGE_LOCATION_OUTPUT",
		5: "STAGE_LOCATION_CUMULATIVE",
	}
	StageLocationE_value = map[string]int32{
		"STAGE_LOCATION_OTHER":       0,
		"STAGE_LOCATION_UNKNOWN":     1,
		"STAGE_LOCATION_INPUT":       2,
		"STAGE_LOCATION_INTER_STAGE": 3,
		"STAGE_LOCATION_OUTPUT":      4,
		"STAGE_LOCATION_CUMULATIVE":  5,
	}
)

func (x StageLocationE) Enum() *StageLocationE {
	p := new(StageLocationE)
	*p = x
	return p
}

func (x StageLocationE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StageLocationE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_rf_capabilities_grp_proto_enumTypes[5].Descriptor()
}

func (StageLocationE) Type() protoreflect.EnumType {
	return &file_amps_rf_capabilities_grp_proto_enumTypes[5]
}

func (x StageLocationE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *StageLocationE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = StageLocationE(num)
	return nil
}

// Deprecated: Use StageLocationE.Descriptor instead.
func (StageLocationE) EnumDescriptor() ([]byte, []int) {
	return file_amps_rf_capabilities_grp_proto_rawDescGZIP(), []int{5}
}

type AgcTypeE int32

const (
	AgcTypeE_AGC_TYPE_OTHER                     AgcTypeE = 0
	AgcTypeE_AGC_TYPE_UNKNOWN                   AgcTypeE = 1
	AgcTypeE_AGC_TYPE_MF_AGC                    AgcTypeE = 2
	AgcTypeE_AGC_TYPE_AGILE_AGC                 AgcTypeE = 3
	AgcTypeE_AGC_TYPE_AGC_PILOT_LOSS_PROTECTION AgcTypeE = 4
)

// Enum value maps for AgcTypeE.
var (
	AgcTypeE_name = map[int32]string{
		0: "AGC_TYPE_OTHER",
		1: "AGC_TYPE_UNKNOWN",
		2: "AGC_TYPE_MF_AGC",
		3: "AGC_TYPE_AGILE_AGC",
		4: "AGC_TYPE_AGC_PILOT_LOSS_PROTECTION",
	}
	AgcTypeE_value = map[string]int32{
		"AGC_TYPE_OTHER":                     0,
		"AGC_TYPE_UNKNOWN":                   1,
		"AGC_TYPE_MF_AGC":                    2,
		"AGC_TYPE_AGILE_AGC":                 3,
		"AGC_TYPE_AGC_PILOT_LOSS_PROTECTION": 4,
	}
)

func (x AgcTypeE) Enum() *AgcTypeE {
	p := new(AgcTypeE)
	*p = x
	return p
}

func (x AgcTypeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgcTypeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_rf_capabilities_grp_proto_enumTypes[6].Descriptor()
}

func (AgcTypeE) Type() protoreflect.EnumType {
	return &file_amps_rf_capabilities_grp_proto_enumTypes[6]
}

func (x AgcTypeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AgcTypeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AgcTypeE(num)
	return nil
}

// Deprecated: Use AgcTypeE.Descriptor instead.
func (AgcTypeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_rf_capabilities_grp_proto_rawDescGZIP(), []int{6}
}

type UsDsStageCapabilities struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	StageIndex                   *uint32                `protobuf:"varint,1,opt,name=stage_index,json=stageIndex" json:"stage_index,omitempty"`
	StageType                    *StageTypeE            `protobuf:"varint,2,opt,name=stage_type,json=stageType,enum=scte.amp.StageTypeE" json:"stage_type,omitempty"`
	StageLocation                *StageLocationE        `protobuf:"varint,3,opt,name=stage_location,json=stageLocation,enum=scte.amp.StageLocationE" json:"stage_location,omitempty"`
	MinAttenuationTenthsDb       *uint32                `protobuf:"varint,4,opt,name=min_attenuation_tenths_db,json=minAttenuationTenthsDb" json:"min_attenuation_tenths_db,omitempty"`
	MaxAttenuationTenthsDb       *uint32                `protobuf:"varint,5,opt,name=max_attenuation_tenths_db,json=maxAttenuationTenthsDb" json:"max_attenuation_tenths_db,omitempty"`
	AttenuationStepSizeTenthsDb  *uint32                `protobuf:"varint,6,opt,name=attenuation_step_size_tenths_db,json=attenuationStepSizeTenthsDb" json:"attenuation_step_size_tenths_db,omitempty"`
	MinEqualization              *uint32                `protobuf:"varint,7,opt,name=min_equalization,json=minEqualization" json:"min_equalization,omitempty"`
	MaxEqualization              *uint32                `protobuf:"varint,8,opt,name=max_equalization,json=maxEqualization" json:"max_equalization,omitempty"`
	EqualizationStepSizeTenthsDb *uint32                `protobuf:"varint,9,opt,name=equalization_step_size_tenths_db,json=equalizationStepSizeTenthsDb" json:"equalization_step_size_tenths_db,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *UsDsStageCapabilities) Reset() {
	*x = UsDsStageCapabilities{}
	mi := &file_amps_rf_capabilities_grp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsDsStageCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsDsStageCapabilities) ProtoMessage() {}

func (x *UsDsStageCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_amps_rf_capabilities_grp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsDsStageCapabilities.ProtoReflect.Descriptor instead.
func (*UsDsStageCapabilities) Descriptor() ([]byte, []int) {
	return file_amps_rf_capabilities_grp_proto_rawDescGZIP(), []int{0}
}

func (x *UsDsStageCapabilities) GetStageIndex() uint32 {
	if x != nil && x.StageIndex != nil {
		return *x.StageIndex
	}
	return 0
}

func (x *UsDsStageCapabilities) GetStageType() StageTypeE {
	if x != nil && x.StageType != nil {
		return *x.StageType
	}
	return StageTypeE_STAGE_TYPE_OTHER
}

func (x *UsDsStageCapabilities) GetStageLocation() StageLocationE {
	if x != nil && x.StageLocation != nil {
		return *x.StageLocation
	}
	return StageLocationE_STAGE_LOCATION_OTHER
}

func (x *UsDsStageCapabilities) GetMinAttenuationTenthsDb() uint32 {
	if x != nil && x.MinAttenuationTenthsDb != nil {
		return *x.MinAttenuationTenthsDb
	}
	return 0
}

func (x *UsDsStageCapabilities) GetMaxAttenuationTenthsDb() uint32 {
	if x != nil && x.MaxAttenuationTenthsDb != nil {
		return *x.MaxAttenuationTenthsDb
	}
	return 0
}

func (x *UsDsStageCapabilities) GetAttenuationStepSizeTenthsDb() uint32 {
	if x != nil && x.AttenuationStepSizeTenthsDb != nil {
		return *x.AttenuationStepSizeTenthsDb
	}
	return 0
}

func (x *UsDsStageCapabilities) GetMinEqualization() uint32 {
	if x != nil && x.MinEqualization != nil {
		return *x.MinEqualization
	}
	return 0
}

func (x *UsDsStageCapabilities) GetMaxEqualization() uint32 {
	if x != nil && x.MaxEqualization != nil {
		return *x.MaxEqualization
	}
	return 0
}

func (x *UsDsStageCapabilities) GetEqualizationStepSizeTenthsDb() uint32 {
	if x != nil && x.EqualizationStepSizeTenthsDb != nil {
		return *x.EqualizationStepSizeTenthsDb
	}
	return 0
}

type UsLogicalPortCapabilities struct {
	state                                    protoimpl.MessageState   `protogen:"open.v1"`
	MinUsFreq                                *uint32                  `protobuf:"varint,1,opt,name=min_us_freq,json=minUsFreq" json:"min_us_freq,omitempty"`
	MaxUsFreq                                *uint32                  `protobuf:"varint,2,opt,name=max_us_freq,json=maxUsFreq" json:"max_us_freq,omitempty"`
	OperationalGainTenthsDb                  *uint32                  `protobuf:"varint,3,opt,name=operational_gain_tenths_db,json=operationalGainTenthsDb" json:"operational_gain_tenths_db,omitempty"`
	NumUsStages                              *uint32                  `protobuf:"varint,4,opt,name=num_us_stages,json=numUsStages" json:"num_us_stages,omitempty"`
	RfTestpointSupported                     *bool                    `protobuf:"varint,5,opt,name=rf_testpoint_supported,json=rfTestpointSupported" json:"rf_testpoint_supported,omitempty"`
	RfTestpointNumPoints                     *uint32                  `protobuf:"varint,6,opt,name=rf_testpoint_num_points,json=rfTestpointNumPoints" json:"rf_testpoint_num_points,omitempty"`
	SupportsIngressSwitch                    *bool                    `protobuf:"varint,7,opt,name=supports_ingress_switch,json=supportsIngressSwitch" json:"supports_ingress_switch,omitempty"`
	IngressSwitchAttenuationMinValueTenthsDb *uint32                  `protobuf:"varint,8,opt,name=ingress_switch_attenuation_min_value_tenths_db,json=ingressSwitchAttenuationMinValueTenthsDb" json:"ingress_switch_attenuation_min_value_tenths_db,omitempty"`
	IngressSwitchAttenuationMaxValueTenthsDb *uint32                  `protobuf:"varint,9,opt,name=ingress_switch_attenuation_max_value_tenths_db,json=ingressSwitchAttenuationMaxValueTenthsDb" json:"ingress_switch_attenuation_max_value_tenths_db,omitempty"`
	IngressSwitchAttenuationStepSizeTenthsDb *uint32                  `protobuf:"varint,10,opt,name=ingress_switch_attenuation_step_size_tenths_db,json=ingressSwitchAttenuationStepSizeTenthsDb" json:"ingress_switch_attenuation_step_size_tenths_db,omitempty"`
	RfLevelControlType                       *uint32                  `protobuf:"varint,11,opt,name=rf_level_control_type,json=rfLevelControlType" json:"rf_level_control_type,omitempty"`
	ThermalLevelControlSelectMinValue        *uint32                  `protobuf:"varint,12,opt,name=thermal_level_control_select_min_value,json=thermalLevelControlSelectMinValue" json:"thermal_level_control_select_min_value,omitempty"`
	ThermalLevelControlSelectMaxValue        *uint32                  `protobuf:"varint,13,opt,name=thermal_level_control_select_max_value,json=thermalLevelControlSelectMaxValue" json:"thermal_level_control_select_max_value,omitempty"`
	ThermalLevelControlSelectStepSize        *uint32                  `protobuf:"varint,14,opt,name=thermal_level_control_select_step_size,json=thermalLevelControlSelectStepSize" json:"thermal_level_control_select_step_size,omitempty"`
	UsStageCapabilities                      []*UsDsStageCapabilities `protobuf:"bytes,15,rep,name=us_stage_capabilities,json=usStageCapabilities" json:"us_stage_capabilities,omitempty"`
	unknownFields                            protoimpl.UnknownFields
	sizeCache                                protoimpl.SizeCache
}

func (x *UsLogicalPortCapabilities) Reset() {
	*x = UsLogicalPortCapabilities{}
	mi := &file_amps_rf_capabilities_grp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsLogicalPortCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsLogicalPortCapabilities) ProtoMessage() {}

func (x *UsLogicalPortCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_amps_rf_capabilities_grp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsLogicalPortCapabilities.ProtoReflect.Descriptor instead.
func (*UsLogicalPortCapabilities) Descriptor() ([]byte, []int) {
	return file_amps_rf_capabilities_grp_proto_rawDescGZIP(), []int{1}
}

func (x *UsLogicalPortCapabilities) GetMinUsFreq() uint32 {
	if x != nil && x.MinUsFreq != nil {
		return *x.MinUsFreq
	}
	return 0
}

func (x *UsLogicalPortCapabilities) GetMaxUsFreq() uint32 {
	if x != nil && x.MaxUsFreq != nil {
		return *x.MaxUsFreq
	}
	return 0
}

func (x *UsLogicalPortCapabilities) GetOperationalGainTenthsDb() uint32 {
	if x != nil && x.OperationalGainTenthsDb != nil {
		return *x.OperationalGainTenthsDb
	}
	return 0
}

func (x *UsLogicalPortCapabilities) GetNumUsStages() uint32 {
	if x != nil && x.NumUsStages != nil {
		return *x.NumUsStages
	}
	return 0
}

func (x *UsLogicalPortCapabilities) GetRfTestpointSupported() bool {
	if x != nil && x.RfTestpointSupported != nil {
		return *x.RfTestpointSupported
	}
	return false
}

func (x *UsLogicalPortCapabilities) GetRfTestpointNumPoints() uint32 {
	if x != nil && x.RfTestpointNumPoints != nil {
		return *x.RfTestpointNumPoints
	}
	return 0
}

func (x *UsLogicalPortCapabilities) GetSupportsIngressSwitch() bool {
	if x != nil && x.SupportsIngressSwitch != nil {
		return *x.SupportsIngressSwitch
	}
	return false
}

func (x *UsLogicalPortCapabilities) GetIngressSwitchAttenuationMinValueTenthsDb() uint32 {
	if x != nil && x.IngressSwitchAttenuationMinValueTenthsDb != nil {
		return *x.IngressSwitchAttenuationMinValueTenthsDb
	}
	return 0
}

func (x *UsLogicalPortCapabilities) GetIngressSwitchAttenuationMaxValueTenthsDb() uint32 {
	if x != nil && x.IngressSwitchAttenuationMaxValueTenthsDb != nil {
		return *x.IngressSwitchAttenuationMaxValueTenthsDb
	}
	return 0
}

func (x *UsLogicalPortCapabilities) GetIngressSwitchAttenuationStepSizeTenthsDb() uint32 {
	if x != nil && x.IngressSwitchAttenuationStepSizeTenthsDb != nil {
		return *x.IngressSwitchAttenuationStepSizeTenthsDb
	}
	return 0
}

func (x *UsLogicalPortCapabilities) GetRfLevelControlType() uint32 {
	if x != nil && x.RfLevelControlType != nil {
		return *x.RfLevelControlType
	}
	return 0
}

func (x *UsLogicalPortCapabilities) GetThermalLevelControlSelectMinValue() uint32 {
	if x != nil && x.ThermalLevelControlSelectMinValue != nil {
		return *x.ThermalLevelControlSelectMinValue
	}
	return 0
}

func (x *UsLogicalPortCapabilities) GetThermalLevelControlSelectMaxValue() uint32 {
	if x != nil && x.ThermalLevelControlSelectMaxValue != nil {
		return *x.ThermalLevelControlSelectMaxValue
	}
	return 0
}

func (x *UsLogicalPortCapabilities) GetThermalLevelControlSelectStepSize() uint32 {
	if x != nil && x.ThermalLevelControlSelectStepSize != nil {
		return *x.ThermalLevelControlSelectStepSize
	}
	return 0
}

func (x *UsLogicalPortCapabilities) GetUsStageCapabilities() []*UsDsStageCapabilities {
	if x != nil {
		return x.UsStageCapabilities
	}
	return nil
}

type DsLogicalPortCapabilities struct {
	state                      protoimpl.MessageState   `protogen:"open.v1"`
	MinDsFreq                  *uint32                  `protobuf:"varint,1,opt,name=min_ds_freq,json=minDsFreq" json:"min_ds_freq,omitempty"`
	MaxDsFreq                  *uint32                  `protobuf:"varint,2,opt,name=max_ds_freq,json=maxDsFreq" json:"max_ds_freq,omitempty"`
	OperationalGainTenthsDb    *uint32                  `protobuf:"varint,3,opt,name=operational_gain_tenths_db,json=operationalGainTenthsDb" json:"operational_gain_tenths_db,omitempty"`
	NumDsStages                *uint32                  `protobuf:"varint,4,opt,name=num_ds_stages,json=numDsStages" json:"num_ds_stages,omitempty"`
	RfTestpointSupported       *bool                    `protobuf:"varint,5,opt,name=rf_testpoint_supported,json=rfTestpointSupported" json:"rf_testpoint_supported,omitempty"`
	RfTestpointNumPoints       *uint32                  `protobuf:"varint,6,opt,name=rf_testpoint_num_points,json=rfTestpointNumPoints" json:"rf_testpoint_num_points,omitempty"`
	AgcType                    *uint32                  `protobuf:"varint,7,opt,name=agc_type,json=agcType" json:"agc_type,omitempty"`
	AgcNumAgilePilots          *uint32                  `protobuf:"varint,8,opt,name=agc_num_agile_pilots,json=agcNumAgilePilots" json:"agc_num_agile_pilots,omitempty"`
	AgcPilotlossProtectionType *string                  `protobuf:"bytes,9,opt,name=agc_pilotloss_protection_type,json=agcPilotlossProtectionType" json:"agc_pilotloss_protection_type,omitempty"`
	DsStageCapabilities        []*UsDsStageCapabilities `protobuf:"bytes,10,rep,name=ds_stage_capabilities,json=dsStageCapabilities" json:"ds_stage_capabilities,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *DsLogicalPortCapabilities) Reset() {
	*x = DsLogicalPortCapabilities{}
	mi := &file_amps_rf_capabilities_grp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DsLogicalPortCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DsLogicalPortCapabilities) ProtoMessage() {}

func (x *DsLogicalPortCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_amps_rf_capabilities_grp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DsLogicalPortCapabilities.ProtoReflect.Descriptor instead.
func (*DsLogicalPortCapabilities) Descriptor() ([]byte, []int) {
	return file_amps_rf_capabilities_grp_proto_rawDescGZIP(), []int{2}
}

func (x *DsLogicalPortCapabilities) GetMinDsFreq() uint32 {
	if x != nil && x.MinDsFreq != nil {
		return *x.MinDsFreq
	}
	return 0
}

func (x *DsLogicalPortCapabilities) GetMaxDsFreq() uint32 {
	if x != nil && x.MaxDsFreq != nil {
		return *x.MaxDsFreq
	}
	return 0
}

func (x *DsLogicalPortCapabilities) GetOperationalGainTenthsDb() uint32 {
	if x != nil && x.OperationalGainTenthsDb != nil {
		return *x.OperationalGainTenthsDb
	}
	return 0
}

func (x *DsLogicalPortCapabilities) GetNumDsStages() uint32 {
	if x != nil && x.NumDsStages != nil {
		return *x.NumDsStages
	}
	return 0
}

func (x *DsLogicalPortCapabilities) GetRfTestpointSupported() bool {
	if x != nil && x.RfTestpointSupported != nil {
		return *x.RfTestpointSupported
	}
	return false
}

func (x *DsLogicalPortCapabilities) GetRfTestpointNumPoints() uint32 {
	if x != nil && x.RfTestpointNumPoints != nil {
		return *x.RfTestpointNumPoints
	}
	return 0
}

func (x *DsLogicalPortCapabilities) GetAgcType() uint32 {
	if x != nil && x.AgcType != nil {
		return *x.AgcType
	}
	return 0
}

func (x *DsLogicalPortCapabilities) GetAgcNumAgilePilots() uint32 {
	if x != nil && x.AgcNumAgilePilots != nil {
		return *x.AgcNumAgilePilots
	}
	return 0
}

func (x *DsLogicalPortCapabilities) GetAgcPilotlossProtectionType() string {
	if x != nil && x.AgcPilotlossProtectionType != nil {
		return *x.AgcPilotlossProtectionType
	}
	return ""
}

func (x *DsLogicalPortCapabilities) GetDsStageCapabilities() []*UsDsStageCapabilities {
	if x != nil {
		return x.DsStageCapabilities
	}
	return nil
}

type DiplexFilterCapabilities struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	DiplexFilterIndex           *uint32                `protobuf:"varint,1,opt,name=diplex_filter_index,json=diplexFilterIndex" json:"diplex_filter_index,omitempty"`
	DiplexFilterUsUpperBandEdge *uint32                `protobuf:"varint,2,opt,name=diplex_filter_us_upper_band_edge,json=diplexFilterUsUpperBandEdge" json:"diplex_filter_us_upper_band_edge,omitempty"`
	DiplexFilterDsLowerBandEdge *uint32                `protobuf:"varint,3,opt,name=diplex_filter_ds_lower_band_edge,json=diplexFilterDsLowerBandEdge" json:"diplex_filter_ds_lower_band_edge,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *DiplexFilterCapabilities) Reset() {
	*x = DiplexFilterCapabilities{}
	mi := &file_amps_rf_capabilities_grp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiplexFilterCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiplexFilterCapabilities) ProtoMessage() {}

func (x *DiplexFilterCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_amps_rf_capabilities_grp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiplexFilterCapabilities.ProtoReflect.Descriptor instead.
func (*DiplexFilterCapabilities) Descriptor() ([]byte, []int) {
	return file_amps_rf_capabilities_grp_proto_rawDescGZIP(), []int{3}
}

func (x *DiplexFilterCapabilities) GetDiplexFilterIndex() uint32 {
	if x != nil && x.DiplexFilterIndex != nil {
		return *x.DiplexFilterIndex
	}
	return 0
}

func (x *DiplexFilterCapabilities) GetDiplexFilterUsUpperBandEdge() uint32 {
	if x != nil && x.DiplexFilterUsUpperBandEdge != nil {
		return *x.DiplexFilterUsUpperBandEdge
	}
	return 0
}

func (x *DiplexFilterCapabilities) GetDiplexFilterDsLowerBandEdge() uint32 {
	if x != nil && x.DiplexFilterDsLowerBandEdge != nil {
		return *x.DiplexFilterDsLowerBandEdge
	}
	return 0
}

type BiDirLogicalPortCapabilities struct {
	state                    protoimpl.MessageState      `protogen:"open.v1"`
	DiplexFilterCapabilities []*DiplexFilterCapabilities `protobuf:"bytes,1,rep,name=diplex_filter_capabilities,json=diplexFilterCapabilities" json:"diplex_filter_capabilities,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BiDirLogicalPortCapabilities) Reset() {
	*x = BiDirLogicalPortCapabilities{}
	mi := &file_amps_rf_capabilities_grp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BiDirLogicalPortCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiDirLogicalPortCapabilities) ProtoMessage() {}

func (x *BiDirLogicalPortCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_amps_rf_capabilities_grp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiDirLogicalPortCapabilities.ProtoReflect.Descriptor instead.
func (*BiDirLogicalPortCapabilities) Descriptor() ([]byte, []int) {
	return file_amps_rf_capabilities_grp_proto_rawDescGZIP(), []int{4}
}

func (x *BiDirLogicalPortCapabilities) GetDiplexFilterCapabilities() []*DiplexFilterCapabilities {
	if x != nil {
		return x.DiplexFilterCapabilities
	}
	return nil
}

type RfPortCapabilities struct {
	state                        protoimpl.MessageState        `protogen:"open.v1"`
	Index                        *RfPortIndexE                 `protobuf:"varint,1,opt,name=index,enum=scte.amp.RfPortIndexE" json:"index,omitempty"`
	DsLogicalPortCapabilities    *DsLogicalPortCapabilities    `protobuf:"bytes,2,opt,name=ds_logical_port_capabilities,json=dsLogicalPortCapabilities" json:"ds_logical_port_capabilities,omitempty"`
	UsLogicalPortCapabilities    *UsLogicalPortCapabilities    `protobuf:"bytes,3,opt,name=us_logical_port_capabilities,json=usLogicalPortCapabilities" json:"us_logical_port_capabilities,omitempty"`
	BidirLogicalPortCapabilities *BiDirLogicalPortCapabilities `protobuf:"bytes,4,opt,name=bidir_logical_port_capabilities,json=bidirLogicalPortCapabilities" json:"bidir_logical_port_capabilities,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *RfPortCapabilities) Reset() {
	*x = RfPortCapabilities{}
	mi := &file_amps_rf_capabilities_grp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RfPortCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RfPortCapabilities) ProtoMessage() {}

func (x *RfPortCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_amps_rf_capabilities_grp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RfPortCapabilities.ProtoReflect.Descriptor instead.
func (*RfPortCapabilities) Descriptor() ([]byte, []int) {
	return file_amps_rf_capabilities_grp_proto_rawDescGZIP(), []int{5}
}

func (x *RfPortCapabilities) GetIndex() RfPortIndexE {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return RfPortIndexE_RF_PORT_INDEX_2
}

func (x *RfPortCapabilities) GetDsLogicalPortCapabilities() *DsLogicalPortCapabilities {
	if x != nil {
		return x.DsLogicalPortCapabilities
	}
	return nil
}

func (x *RfPortCapabilities) GetUsLogicalPortCapabilities() *UsLogicalPortCapabilities {
	if x != nil {
		return x.UsLogicalPortCapabilities
	}
	return nil
}

func (x *RfPortCapabilities) GetBidirLogicalPortCapabilities() *BiDirLogicalPortCapabilities {
	if x != nil {
		return x.BidirLogicalPortCapabilities
	}
	return nil
}

type RfCapabilities struct {
	state                     protoimpl.MessageState            `protogen:"open.v1"`
	NumRfPorts                *uint32                           `protobuf:"varint,1,opt,name=num_rf_ports,json=numRfPorts" json:"num_rf_ports,omitempty"`
	SupportsUniversalPlugin   *bool                             `protobuf:"varint,2,opt,name=supports_universal_plugin,json=supportsUniversalPlugin" json:"supports_universal_plugin,omitempty"`
	NumDiplexFilters          *uint32                           `protobuf:"varint,3,opt,name=num_diplex_filters,json=numDiplexFilters" json:"num_diplex_filters,omitempty"`
	SupportsRfSpectrumCapture *RfSpectrumCaptureTypeE           `protobuf:"varint,4,opt,name=supports_rf_spectrum_capture,json=supportsRfSpectrumCapture,enum=scte.amp.RfSpectrumCaptureTypeE" json:"supports_rf_spectrum_capture,omitempty"`
	RfPortCapabilities        []*RfPortCapabilities             `protobuf:"bytes,9,rep,name=rf_port_capabilities,json=rfPortCapabilities" json:"rf_port_capabilities,omitempty"`
	VendorRfCapabilities      []*common_go.VendorExtension      `protobuf:"bytes,99,rep,name=vendor_rf_capabilities,json=vendorRfCapabilities" json:"vendor_rf_capabilities,omitempty"`
	Page                      *common_go.ResponsePaginationInfo `protobuf:"bytes,100,opt,name=page" json:"page,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RfCapabilities) Reset() {
	*x = RfCapabilities{}
	mi := &file_amps_rf_capabilities_grp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RfCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RfCapabilities) ProtoMessage() {}

func (x *RfCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_amps_rf_capabilities_grp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RfCapabilities.ProtoReflect.Descriptor instead.
func (*RfCapabilities) Descriptor() ([]byte, []int) {
	return file_amps_rf_capabilities_grp_proto_rawDescGZIP(), []int{6}
}

func (x *RfCapabilities) GetNumRfPorts() uint32 {
	if x != nil && x.NumRfPorts != nil {
		return *x.NumRfPorts
	}
	return 0
}

func (x *RfCapabilities) GetSupportsUniversalPlugin() bool {
	if x != nil && x.SupportsUniversalPlugin != nil {
		return *x.SupportsUniversalPlugin
	}
	return false
}

func (x *RfCapabilities) GetNumDiplexFilters() uint32 {
	if x != nil && x.NumDiplexFilters != nil {
		return *x.NumDiplexFilters
	}
	return 0
}

func (x *RfCapabilities) GetSupportsRfSpectrumCapture() RfSpectrumCaptureTypeE {
	if x != nil && x.SupportsRfSpectrumCapture != nil {
		return *x.SupportsRfSpectrumCapture
	}
	return RfSpectrumCaptureTypeE_PORT1_UPSTREAM
}

func (x *RfCapabilities) GetRfPortCapabilities() []*RfPortCapabilities {
	if x != nil {
		return x.RfPortCapabilities
	}
	return nil
}

func (x *RfCapabilities) GetVendorRfCapabilities() []*common_go.VendorExtension {
	if x != nil {
		return x.VendorRfCapabilities
	}
	return nil
}

func (x *RfCapabilities) GetPage() *common_go.ResponsePaginationInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_amps_rf_capabilities_grp_proto protoreflect.FileDescriptor

const file_amps_rf_capabilities_grp_proto_rawDesc = "" +
	"\n" +
	"\x1eamps/rf_capabilities_grp.proto\x12\bscte.amp\x1a\x17common/pagination.proto\x1a\x1acommon/vendor_common.proto\"\x8c\x04\n" +
	"\x15UsDsStageCapabilities\x12\x1f\n" +
	"\vstage_index\x18\x01 \x01(\rR\n" +
	"stageIndex\x125\n" +
	"\n" +
	"stage_type\x18\x02 \x01(\x0e2\x16.scte.amp.stage_type_eR\tstageType\x12A\n" +
	"\x0estage_location\x18\x03 \x01(\x0e2\x1a.scte.amp.stage_location_eR\rstageLocation\x129\n" +
	"\x19min_attenuation_tenths_db\x18\x04 \x01(\rR\x16minAttenuationTenthsDb\x129\n" +
	"\x19max_attenuation_tenths_db\x18\x05 \x01(\rR\x16maxAttenuationTenthsDb\x12D\n" +
	"\x1fattenuation_step_size_tenths_db\x18\x06 \x01(\rR\x1battenuationStepSizeTenthsDb\x12)\n" +
	"\x10min_equalization\x18\a \x01(\rR\x0fminEqualization\x12)\n" +
	"\x10max_equalization\x18\b \x01(\rR\x0fmaxEqualization\x12F\n" +
	" equalization_step_size_tenths_db\x18\t \x01(\rR\x1cequalizationStepSizeTenthsDb\"\x88\b\n" +
	"\x19UsLogicalPortCapabilities\x12\x1e\n" +
	"\vmin_us_freq\x18\x01 \x01(\rR\tminUsFreq\x12\x1e\n" +
	"\vmax_us_freq\x18\x02 \x01(\rR\tmaxUsFreq\x12;\n" +
	"\x1aoperational_gain_tenths_db\x18\x03 \x01(\rR\x17operationalGainTenthsDb\x12\"\n" +
	"\rnum_us_stages\x18\x04 \x01(\rR\vnumUsStages\x124\n" +
	"\x16rf_testpoint_supported\x18\x05 \x01(\bR\x14rfTestpointSupported\x125\n" +
	"\x17rf_testpoint_num_points\x18\x06 \x01(\rR\x14rfTestpointNumPoints\x126\n" +
	"\x17supports_ingress_switch\x18\a \x01(\bR\x15supportsIngressSwitch\x12`\n" +
	".ingress_switch_attenuation_min_value_tenths_db\x18\b \x01(\rR(ingressSwitchAttenuationMinValueTenthsDb\x12`\n" +
	".ingress_switch_attenuation_max_value_tenths_db\x18\t \x01(\rR(ingressSwitchAttenuationMaxValueTenthsDb\x12`\n" +
	".ingress_switch_attenuation_step_size_tenths_db\x18\n" +
	" \x01(\rR(ingressSwitchAttenuationStepSizeTenthsDb\x121\n" +
	"\x15rf_level_control_type\x18\v \x01(\rR\x12rfLevelControlType\x12Q\n" +
	"&thermal_level_control_select_min_value\x18\f \x01(\rR!thermalLevelControlSelectMinValue\x12Q\n" +
	"&thermal_level_control_select_max_value\x18\r \x01(\rR!thermalLevelControlSelectMaxValue\x12Q\n" +
	"&thermal_level_control_select_step_size\x18\x0e \x01(\rR!thermalLevelControlSelectStepSize\x12S\n" +
	"\x15us_stage_capabilities\x18\x0f \x03(\v2\x1f.scte.amp.UsDsStageCapabilitiesR\x13usStageCapabilities\"\x8d\x04\n" +
	"\x19DsLogicalPortCapabilities\x12\x1e\n" +
	"\vmin_ds_freq\x18\x01 \x01(\rR\tminDsFreq\x12\x1e\n" +
	"\vmax_ds_freq\x18\x02 \x01(\rR\tmaxDsFreq\x12;\n" +
	"\x1aoperational_gain_tenths_db\x18\x03 \x01(\rR\x17operationalGainTenthsDb\x12\"\n" +
	"\rnum_ds_stages\x18\x04 \x01(\rR\vnumDsStages\x124\n" +
	"\x16rf_testpoint_supported\x18\x05 \x01(\bR\x14rfTestpointSupported\x125\n" +
	"\x17rf_testpoint_num_points\x18\x06 \x01(\rR\x14rfTestpointNumPoints\x12\x19\n" +
	"\bagc_type\x18\a \x01(\rR\aagcType\x12/\n" +
	"\x14agc_num_agile_pilots\x18\b \x01(\rR\x11agcNumAgilePilots\x12A\n" +
	"\x1dagc_pilotloss_protection_type\x18\t \x01(\tR\x1aagcPilotlossProtectionType\x12S\n" +
	"\x15ds_stage_capabilities\x18\n" +
	" \x03(\v2\x1f.scte.amp.UsDsStageCapabilitiesR\x13dsStageCapabilities\"\xd8\x01\n" +
	"\x18DiplexFilterCapabilities\x12.\n" +
	"\x13diplex_filter_index\x18\x01 \x01(\rR\x11diplexFilterIndex\x12E\n" +
	" diplex_filter_us_upper_band_edge\x18\x02 \x01(\rR\x1bdiplexFilterUsUpperBandEdge\x12E\n" +
	" diplex_filter_ds_lower_band_edge\x18\x03 \x01(\rR\x1bdiplexFilterDsLowerBandEdge\"\x80\x01\n" +
	"\x1cBiDirLogicalPortCapabilities\x12`\n" +
	"\x1adiplex_filter_capabilities\x18\x01 \x03(\v2\".scte.amp.DiplexFilterCapabilitiesR\x18diplexFilterCapabilities\"\x80\x03\n" +
	"\x12RfPortCapabilities\x12/\n" +
	"\x05index\x18\x01 \x01(\x0e2\x19.scte.amp.rf_port_index_eR\x05index\x12d\n" +
	"\x1cds_logical_port_capabilities\x18\x02 \x01(\v2#.scte.amp.DsLogicalPortCapabilitiesR\x19dsLogicalPortCapabilities\x12d\n" +
	"\x1cus_logical_port_capabilities\x18\x03 \x01(\v2#.scte.amp.UsLogicalPortCapabilitiesR\x19usLogicalPortCapabilities\x12m\n" +
	"\x1fbidir_logical_port_capabilities\x18\x04 \x01(\v2&.scte.amp.BiDirLogicalPortCapabilitiesR\x1cbidirLogicalPortCapabilities\"\xe0\x03\n" +
	"\x0eRfCapabilities\x12 \n" +
	"\fnum_rf_ports\x18\x01 \x01(\rR\n" +
	"numRfPorts\x12:\n" +
	"\x19supports_universal_plugin\x18\x02 \x01(\bR\x17supportsUniversalPlugin\x12,\n" +
	"\x12num_diplex_filters\x18\x03 \x01(\rR\x10numDiplexFilters\x12e\n" +
	"\x1csupports_rf_spectrum_capture\x18\x04 \x01(\x0e2$.scte.amp.rf_spectrum_capture_type_eR\x19supportsRfSpectrumCapture\x12N\n" +
	"\x14rf_port_capabilities\x18\t \x03(\v2\x1c.scte.amp.RfPortCapabilitiesR\x12rfPortCapabilities\x12R\n" +
	"\x16vendor_rf_capabilities\x18c \x03(\v2\x1c.scte.common.VendorExtensionR\x14vendorRfCapabilities\x127\n" +
	"\x04page\x18d \x01(\v2#.scte.common.ResponsePaginationInfoR\x04page*\xf7\x01\n" +
	"\x1arf_spectrum_capture_type_e\x12\x12\n" +
	"\x0ePORT1_UPSTREAM\x10\x01\x12\x14\n" +
	"\x10PORT1_DOWNSTREAM\x10\x02\x12\x12\n" +
	"\x0ePORT2_UPSTREAM\x10\x04\x12\x14\n" +
	"\x10PORT2_DOWNSTREAM\x10\b\x12\x12\n" +
	"\x0ePORT3_UPSTREAM\x10\x10\x12\x14\n" +
	"\x10PORT3_DOWNSTREAM\x10 \x12\x12\n" +
	"\x0ePORT4_UPSTREAM\x10@\x12\x15\n" +
	"\x10PORT4_DOWNSTREAM\x10\x80\x01\x12\x16\n" +
	"\x11PORT_UPSTREAM_ALL\x10\x80\x02\x12\x18\n" +
	"\x13PORT_DOWNSTREAM_ALL\x10\x80\x04*b\n" +
	"\x0frf_port_index_e\x12\x13\n" +
	"\x0fRF_PORT_INDEX_2\x10\x02\x12\x13\n" +
	"\x0fRF_PORT_INDEX_3\x10\x03\x12\x13\n" +
	"\x0fRF_PORT_INDEX_4\x10\x04\x12\x10\n" +
	"\vRF_PORT_ALL\x10\xff\x01*\x86\x01\n" +
	"\x10alignment_type_e\x12\x1a\n" +
	"\x16ALIGNMENT_TYPE_DS_AUTO\x10\x01\x12\x1a\n" +
	"\x16ALIGNMENT_TYPE_US_AUTO\x10\x02\x12\x1c\n" +
	"\x18ALIGNMENT_TYPE_DS_MANUAL\x10\x04\x12\x1c\n" +
	"\x18ALIGNMENT_TYPE_US_MANUAL\x10\b*\xd2\x01\n" +
	"\x17rf_level_control_type_e\x12\x1a\n" +
	"\x16RF_LEVEL_CONTROL_OTHER\x10\x00\x12\x1c\n" +
	"\x18RF_LEVEL_CONTROL_UNKNOWN\x10\x01\x12\x1e\n" +
	"\x1aRF_LEVEL_CONTROL_QUASI_AGC\x10\x02\x12*\n" +
	"&RF_LEVEL_CONTROL_THERMAL_LEVEL_CONTROL\x10\x03\x121\n" +
	"-RF_LEVEL_CONTROL_THERMAL_LEVEL_CONTROL_SELECT\x10\x04*q\n" +
	"\fstage_type_e\x12\x14\n" +
	"\x10STAGE_TYPE_OTHER\x10\x00\x12\x16\n" +
	"\x12STAGE_TYPE_UNKNOWN\x10\x01\x12\x19\n" +
	"\x15STAGE_TYPE_ATTENUATOR\x10\x02\x12\x18\n" +
	"\x14STAGE_TYPE_EQUALIZER\x10\x03*\xbc\x01\n" +
	"\x10stage_location_e\x12\x18\n" +
	"\x14STAGE_LOCATION_OTHER\x10\x00\x12\x1a\n" +
	"\x16STAGE_LOCATION_UNKNOWN\x10\x01\x12\x18\n" +
	"\x14STAGE_LOCATION_INPUT\x10\x02\x12\x1e\n" +
	"\x1aSTAGE_LOCATION_INTER_STAGE\x10\x03\x12\x19\n" +
	"\x15STAGE_LOCATION_OUTPUT\x10\x04\x12\x1d\n" +
	"\x19STAGE_LOCATION_CUMULATIVE\x10\x05*\x8b\x01\n" +
	"\n" +
	"agc_type_e\x12\x12\n" +
	"\x0eAGC_TYPE_OTHER\x10\x00\x12\x14\n" +
	"\x10AGC_TYPE_UNKNOWN\x10\x01\x12\x13\n" +
	"\x0fAGC_TYPE_MF_AGC\x10\x02\x12\x16\n" +
	"\x12AGC_TYPE_AGILE_AGC\x10\x03\x12&\n" +
	"\"AGC_TYPE_AGC_PILOT_LOSS_PROTECTION\x10\x04B,Z*github.com/enshure/scte-go/amps_go;scteamp"

var (
	file_amps_rf_capabilities_grp_proto_rawDescOnce sync.Once
	file_amps_rf_capabilities_grp_proto_rawDescData []byte
)

func file_amps_rf_capabilities_grp_proto_rawDescGZIP() []byte {
	file_amps_rf_capabilities_grp_proto_rawDescOnce.Do(func() {
		file_amps_rf_capabilities_grp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amps_rf_capabilities_grp_proto_rawDesc), len(file_amps_rf_capabilities_grp_proto_rawDesc)))
	})
	return file_amps_rf_capabilities_grp_proto_rawDescData
}

var file_amps_rf_capabilities_grp_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_amps_rf_capabilities_grp_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_amps_rf_capabilities_grp_proto_goTypes = []any{
	(RfSpectrumCaptureTypeE)(0),              // 0: scte.amp.rf_spectrum_capture_type_e
	(RfPortIndexE)(0),                        // 1: scte.amp.rf_port_index_e
	(AlignmentTypeE)(0),                      // 2: scte.amp.alignment_type_e
	(RfLevelControlTypeE)(0),                 // 3: scte.amp.rf_level_control_type_e
	(StageTypeE)(0),                          // 4: scte.amp.stage_type_e
	(StageLocationE)(0),                      // 5: scte.amp.stage_location_e
	(AgcTypeE)(0),                            // 6: scte.amp.agc_type_e
	(*UsDsStageCapabilities)(nil),            // 7: scte.amp.UsDsStageCapabilities
	(*UsLogicalPortCapabilities)(nil),        // 8: scte.amp.UsLogicalPortCapabilities
	(*DsLogicalPortCapabilities)(nil),        // 9: scte.amp.DsLogicalPortCapabilities
	(*DiplexFilterCapabilities)(nil),         // 10: scte.amp.DiplexFilterCapabilities
	(*BiDirLogicalPortCapabilities)(nil),     // 11: scte.amp.BiDirLogicalPortCapabilities
	(*RfPortCapabilities)(nil),               // 12: scte.amp.RfPortCapabilities
	(*RfCapabilities)(nil),                   // 13: scte.amp.RfCapabilities
	(*common_go.VendorExtension)(nil),        // 14: scte.common.VendorExtension
	(*common_go.ResponsePaginationInfo)(nil), // 15: scte.common.ResponsePaginationInfo
}
var file_amps_rf_capabilities_grp_proto_depIdxs = []int32{
	4,  // 0: scte.amp.UsDsStageCapabilities.stage_type:type_name -> scte.amp.stage_type_e
	5,  // 1: scte.amp.UsDsStageCapabilities.stage_location:type_name -> scte.amp.stage_location_e
	7,  // 2: scte.amp.UsLogicalPortCapabilities.us_stage_capabilities:type_name -> scte.amp.UsDsStageCapabilities
	7,  // 3: scte.amp.DsLogicalPortCapabilities.ds_stage_capabilities:type_name -> scte.amp.UsDsStageCapabilities
	10, // 4: scte.amp.BiDirLogicalPortCapabilities.diplex_filter_capabilities:type_name -> scte.amp.DiplexFilterCapabilities
	1,  // 5: scte.amp.RfPortCapabilities.index:type_name -> scte.amp.rf_port_index_e
	9,  // 6: scte.amp.RfPortCapabilities.ds_logical_port_capabilities:type_name -> scte.amp.DsLogicalPortCapabilities
	8,  // 7: scte.amp.RfPortCapabilities.us_logical_port_capabilities:type_name -> scte.amp.UsLogicalPortCapabilities
	11, // 8: scte.amp.RfPortCapabilities.bidir_logical_port_capabilities:type_name -> scte.amp.BiDirLogicalPortCapabilities
	0,  // 9: scte.amp.RfCapabilities.supports_rf_spectrum_capture:type_name -> scte.amp.rf_spectrum_capture_type_e
	12, // 10: scte.amp.RfCapabilities.rf_port_capabilities:type_name -> scte.amp.RfPortCapabilities
	14, // 11: scte.amp.RfCapabilities.vendor_rf_capabilities:type_name -> scte.common.VendorExtension
	15, // 12: scte.amp.RfCapabilities.page:type_name -> scte.common.ResponsePaginationInfo
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_amps_rf_capabilities_grp_proto_init() }
func file_amps_rf_capabilities_grp_proto_init() {
	if File_amps_rf_capabilities_grp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amps_rf_capabilities_grp_proto_rawDesc), len(file_amps_rf_capabilities_grp_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_amps_rf_capabilities_grp_proto_goTypes,
		DependencyIndexes: file_amps_rf_capabilities_grp_proto_depIdxs,
		EnumInfos:         file_amps_rf_capabilities_grp_proto_enumTypes,
		MessageInfos:      file_amps_rf_capabilities_grp_proto_msgTypes,
	}.Build()
	File_amps_rf_capabilities_grp_proto = out.File
	file_amps_rf_capabilities_grp_proto_goTypes = nil
	file_amps_rf_capabilities_grp_proto_depIdxs = nil
}
