// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: amps/sensor.proto

package scteamp

import (
	common_go "github.com/enshure/scte-go/common_go"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Symbols defined in public import of common/sensor_common.proto.

type Sensor = common_go.Sensor
type Sensors = common_go.Sensors
type SensorDescriptor = common_go.SensorDescriptor
type SensorDescriptors = common_go.SensorDescriptors
type SensorData = common_go.SensorData
type SensorsData = common_go.SensorsData
type TelemetryIntervalEntry = common_go.TelemetryIntervalEntry
type TelemetryIntervalConfig = common_go.TelemetryIntervalConfig

var File_amps_sensor_proto protoreflect.FileDescriptor

const file_amps_sensor_proto_rawDesc = "" +
	"\n" +
	"\x11amps/sensor.proto\x12\bscte.amp\x1a\x1acommon/sensor_common.protoB6Z4github.com/enshure/scte-go/amps_go;scteampP\x00"

var file_amps_sensor_proto_goTypes = []any{}
var file_amps_sensor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_amps_sensor_proto_init() }
func file_amps_sensor_proto_init() {
	if File_amps_sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amps_sensor_proto_rawDesc), len(file_amps_sensor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_amps_sensor_proto_goTypes,
		DependencyIndexes: file_amps_sensor_proto_depIdxs,
	}.Build()
	File_amps_sensor_proto = out.File
	file_amps_sensor_proto_goTypes = nil
	file_amps_sensor_proto_depIdxs = nil
}
