// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: amps/spectrum.proto

package scteamp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpectrumCaptureDataTypeE int32

const (
	SpectrumCaptureDataTypeE_REFERENCE_VALUE SpectrumCaptureDataTypeE = 1
	SpectrumCaptureDataTypeE_MEASURED_VALUE  SpectrumCaptureDataTypeE = 2
)

// Enum value maps for SpectrumCaptureDataTypeE.
var (
	SpectrumCaptureDataTypeE_name = map[int32]string{
		1: "REFERENCE_VALUE",
		2: "MEASURED_VALUE",
	}
	SpectrumCaptureDataTypeE_value = map[string]int32{
		"REFERENCE_VALUE": 1,
		"MEASURED_VALUE":  2,
	}
)

func (x SpectrumCaptureDataTypeE) Enum() *SpectrumCaptureDataTypeE {
	p := new(SpectrumCaptureDataTypeE)
	*p = x
	return p
}

func (x SpectrumCaptureDataTypeE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpectrumCaptureDataTypeE) Descriptor() protoreflect.EnumDescriptor {
	return file_amps_spectrum_proto_enumTypes[0].Descriptor()
}

func (SpectrumCaptureDataTypeE) Type() protoreflect.EnumType {
	return &file_amps_spectrum_proto_enumTypes[0]
}

func (x SpectrumCaptureDataTypeE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SpectrumCaptureDataTypeE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SpectrumCaptureDataTypeE(num)
	return nil
}

// Deprecated: Use SpectrumCaptureDataTypeE.Descriptor instead.
func (SpectrumCaptureDataTypeE) EnumDescriptor() ([]byte, []int) {
	return file_amps_spectrum_proto_rawDescGZIP(), []int{0}
}

type SpectrumCaptureConfig struct {
	state                    protoimpl.MessageState    `protogen:"open.v1"`
	SpectrumCaptureModeE     *PathSelectorE            `protobuf:"varint,2,req,name=spectrum_capture_mode_e,json=spectrumCaptureModeE,enum=scte.amp.PathSelectorE" json:"spectrum_capture_mode_e,omitempty"`
	SpectrumCaptureDataTypeE *SpectrumCaptureDataTypeE `protobuf:"varint,3,req,name=spectrum_capture_data_type_e,json=spectrumCaptureDataTypeE,enum=scte.amp.SpectrumCaptureDataTypeE" json:"spectrum_capture_data_type_e,omitempty"`
	ScanMode                 *SpectrumScanDataE        `protobuf:"varint,4,req,name=scan_mode,json=scanMode,enum=scte.amp.SpectrumScanDataE" json:"scan_mode,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SpectrumCaptureConfig) Reset() {
	*x = SpectrumCaptureConfig{}
	mi := &file_amps_spectrum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpectrumCaptureConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpectrumCaptureConfig) ProtoMessage() {}

func (x *SpectrumCaptureConfig) ProtoReflect() protoreflect.Message {
	mi := &file_amps_spectrum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpectrumCaptureConfig.ProtoReflect.Descriptor instead.
func (*SpectrumCaptureConfig) Descriptor() ([]byte, []int) {
	return file_amps_spectrum_proto_rawDescGZIP(), []int{0}
}

func (x *SpectrumCaptureConfig) GetSpectrumCaptureModeE() PathSelectorE {
	if x != nil && x.SpectrumCaptureModeE != nil {
		return *x.SpectrumCaptureModeE
	}
	return PathSelectorE_DOWNSTREAM
}

func (x *SpectrumCaptureConfig) GetSpectrumCaptureDataTypeE() SpectrumCaptureDataTypeE {
	if x != nil && x.SpectrumCaptureDataTypeE != nil {
		return *x.SpectrumCaptureDataTypeE
	}
	return SpectrumCaptureDataTypeE_REFERENCE_VALUE
}

func (x *SpectrumCaptureConfig) GetScanMode() SpectrumScanDataE {
	if x != nil && x.ScanMode != nil {
		return *x.ScanMode
	}
	return SpectrumScanDataE_SCAN_AUTO_CACHED_DATA
}

type SpectrumCaptureRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartFreq     *uint32                `protobuf:"varint,1,req,name=start_freq,json=startFreq" json:"start_freq,omitempty"`
	StepSize      *uint32                `protobuf:"varint,2,opt,name=step_size,json=stepSize" json:"step_size,omitempty"` // defaults to 6 Mhz
	EndFreq       *uint32                `protobuf:"varint,3,req,name=end_freq,json=endFreq" json:"end_freq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpectrumCaptureRange) Reset() {
	*x = SpectrumCaptureRange{}
	mi := &file_amps_spectrum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpectrumCaptureRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpectrumCaptureRange) ProtoMessage() {}

func (x *SpectrumCaptureRange) ProtoReflect() protoreflect.Message {
	mi := &file_amps_spectrum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpectrumCaptureRange.ProtoReflect.Descriptor instead.
func (*SpectrumCaptureRange) Descriptor() ([]byte, []int) {
	return file_amps_spectrum_proto_rawDescGZIP(), []int{1}
}

func (x *SpectrumCaptureRange) GetStartFreq() uint32 {
	if x != nil && x.StartFreq != nil {
		return *x.StartFreq
	}
	return 0
}

func (x *SpectrumCaptureRange) GetStepSize() uint32 {
	if x != nil && x.StepSize != nil {
		return *x.StepSize
	}
	return 0
}

func (x *SpectrumCaptureRange) GetEndFreq() uint32 {
	if x != nil && x.EndFreq != nil {
		return *x.EndFreq
	}
	return 0
}

type SpectrumCaptureRangeValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartFreq     *uint32                `protobuf:"varint,1,req,name=start_freq,json=startFreq" json:"start_freq,omitempty"`
	StepSize      *uint32                `protobuf:"varint,2,opt,name=step_size,json=stepSize" json:"step_size,omitempty"` // defaults to 6 Mhz
	EndFreq       *uint32                `protobuf:"varint,3,req,name=end_freq,json=endFreq" json:"end_freq,omitempty"`
	Values        []uint32               `protobuf:"varint,4,rep,packed,name=values" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpectrumCaptureRangeValues) Reset() {
	*x = SpectrumCaptureRangeValues{}
	mi := &file_amps_spectrum_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpectrumCaptureRangeValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpectrumCaptureRangeValues) ProtoMessage() {}

func (x *SpectrumCaptureRangeValues) ProtoReflect() protoreflect.Message {
	mi := &file_amps_spectrum_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpectrumCaptureRangeValues.ProtoReflect.Descriptor instead.
func (*SpectrumCaptureRangeValues) Descriptor() ([]byte, []int) {
	return file_amps_spectrum_proto_rawDescGZIP(), []int{2}
}

func (x *SpectrumCaptureRangeValues) GetStartFreq() uint32 {
	if x != nil && x.StartFreq != nil {
		return *x.StartFreq
	}
	return 0
}

func (x *SpectrumCaptureRangeValues) GetStepSize() uint32 {
	if x != nil && x.StepSize != nil {
		return *x.StepSize
	}
	return 0
}

func (x *SpectrumCaptureRangeValues) GetEndFreq() uint32 {
	if x != nil && x.EndFreq != nil {
		return *x.EndFreq
	}
	return 0
}

func (x *SpectrumCaptureRangeValues) GetValues() []uint32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type SpectrumCaptureRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Config        *SpectrumCaptureConfig  `protobuf:"bytes,2,req,name=config" json:"config,omitempty"`
	Ranges        []*SpectrumCaptureRange `protobuf:"bytes,3,rep,name=ranges" json:"ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpectrumCaptureRequest) Reset() {
	*x = SpectrumCaptureRequest{}
	mi := &file_amps_spectrum_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpectrumCaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpectrumCaptureRequest) ProtoMessage() {}

func (x *SpectrumCaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_amps_spectrum_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpectrumCaptureRequest.ProtoReflect.Descriptor instead.
func (*SpectrumCaptureRequest) Descriptor() ([]byte, []int) {
	return file_amps_spectrum_proto_rawDescGZIP(), []int{3}
}

func (x *SpectrumCaptureRequest) GetConfig() *SpectrumCaptureConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SpectrumCaptureRequest) GetRanges() []*SpectrumCaptureRange {
	if x != nil {
		return x.Ranges
	}
	return nil
}

type SpectrumCapturePointValue struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FrequencyMhzX100 *uint32                `protobuf:"varint,1,opt,name=frequency_mhz_x100,json=frequencyMhzX100" json:"frequency_mhz_x100,omitempty"` // Frequency in MHz multiplied by 100, for example 261.0 MHz is 26100.
	PowerX100        *int32                 `protobuf:"zigzag32,2,opt,name=power_x100,json=powerX100" json:"power_x100,omitempty"`                      // Power multiplied by 100, for example 41.43 dBmV is 4143.
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SpectrumCapturePointValue) Reset() {
	*x = SpectrumCapturePointValue{}
	mi := &file_amps_spectrum_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpectrumCapturePointValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpectrumCapturePointValue) ProtoMessage() {}

func (x *SpectrumCapturePointValue) ProtoReflect() protoreflect.Message {
	mi := &file_amps_spectrum_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpectrumCapturePointValue.ProtoReflect.Descriptor instead.
func (*SpectrumCapturePointValue) Descriptor() ([]byte, []int) {
	return file_amps_spectrum_proto_rawDescGZIP(), []int{4}
}

func (x *SpectrumCapturePointValue) GetFrequencyMhzX100() uint32 {
	if x != nil && x.FrequencyMhzX100 != nil {
		return *x.FrequencyMhzX100
	}
	return 0
}

func (x *SpectrumCapturePointValue) GetPowerX100() int32 {
	if x != nil && x.PowerX100 != nil {
		return *x.PowerX100
	}
	return 0
}

type SpectrumCaptureResponse struct {
	state                    protoimpl.MessageState        `protogen:"open.v1"`
	SpectrumCaptureDataTypeE *SpectrumCaptureDataTypeE     `protobuf:"varint,2,req,name=spectrum_capture_data_type_e,json=spectrumCaptureDataTypeE,enum=scte.amp.SpectrumCaptureDataTypeE" json:"spectrum_capture_data_type_e,omitempty"` // 1 byte
	Values                   []*SpectrumCaptureRangeValues `protobuf:"bytes,3,rep,name=values" json:"values,omitempty"`                                                                                                                   // Power values multiplied by 100, for e.g. 43.5 will be sent as 4350 Max bytes - 7 bytes
	TotalCompositePower      *float32                      `protobuf:"fixed32,4,opt,name=total_composite_power,json=totalCompositePower" json:"total_composite_power,omitempty"`
	FragmentInfo             *FragmentInfo                 `protobuf:"bytes,5,opt,name=fragment_info,json=fragmentInfo" json:"fragment_info,omitempty"` // header for the response
	PointValues              []*SpectrumCapturePointValue  `protobuf:"bytes,6,rep,name=point_values,json=pointValues" json:"point_values,omitempty"`    // Sparse/non-uniform points, used for plot-ready REFERENCE_VALUE responses.
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *SpectrumCaptureResponse) Reset() {
	*x = SpectrumCaptureResponse{}
	mi := &file_amps_spectrum_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpectrumCaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpectrumCaptureResponse) ProtoMessage() {}

func (x *SpectrumCaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amps_spectrum_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpectrumCaptureResponse.ProtoReflect.Descriptor instead.
func (*SpectrumCaptureResponse) Descriptor() ([]byte, []int) {
	return file_amps_spectrum_proto_rawDescGZIP(), []int{5}
}

func (x *SpectrumCaptureResponse) GetSpectrumCaptureDataTypeE() SpectrumCaptureDataTypeE {
	if x != nil && x.SpectrumCaptureDataTypeE != nil {
		return *x.SpectrumCaptureDataTypeE
	}
	return SpectrumCaptureDataTypeE_REFERENCE_VALUE
}

func (x *SpectrumCaptureResponse) GetValues() []*SpectrumCaptureRangeValues {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *SpectrumCaptureResponse) GetTotalCompositePower() float32 {
	if x != nil && x.TotalCompositePower != nil {
		return *x.TotalCompositePower
	}
	return 0
}

func (x *SpectrumCaptureResponse) GetFragmentInfo() *FragmentInfo {
	if x != nil {
		return x.FragmentInfo
	}
	return nil
}

func (x *SpectrumCaptureResponse) GetPointValues() []*SpectrumCapturePointValue {
	if x != nil {
		return x.PointValues
	}
	return nil
}

type SpectrumCapture struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Id:
	//
	//	*SpectrumCapture_Request
	//	*SpectrumCapture_Response
	Id            isSpectrumCapture_Id `protobuf_oneof:"id"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpectrumCapture) Reset() {
	*x = SpectrumCapture{}
	mi := &file_amps_spectrum_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpectrumCapture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpectrumCapture) ProtoMessage() {}

func (x *SpectrumCapture) ProtoReflect() protoreflect.Message {
	mi := &file_amps_spectrum_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpectrumCapture.ProtoReflect.Descriptor instead.
func (*SpectrumCapture) Descriptor() ([]byte, []int) {
	return file_amps_spectrum_proto_rawDescGZIP(), []int{6}
}

func (x *SpectrumCapture) GetId() isSpectrumCapture_Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SpectrumCapture) GetRequest() *SpectrumCaptureRequest {
	if x != nil {
		if x, ok := x.Id.(*SpectrumCapture_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *SpectrumCapture) GetResponse() *SpectrumCaptureResponse {
	if x != nil {
		if x, ok := x.Id.(*SpectrumCapture_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isSpectrumCapture_Id interface {
	isSpectrumCapture_Id()
}

type SpectrumCapture_Request struct {
	Request *SpectrumCaptureRequest `protobuf:"bytes,1,opt,name=request,oneof"`
}

type SpectrumCapture_Response struct {
	Response *SpectrumCaptureResponse `protobuf:"bytes,2,opt,name=response,oneof"`
}

func (*SpectrumCapture_Request) isSpectrumCapture_Id() {}

func (*SpectrumCapture_Response) isSpectrumCapture_Id() {}

var File_amps_spectrum_proto protoreflect.FileDescriptor

const file_amps_spectrum_proto_rawDesc = "" +
	"\n" +
	"\x13amps/spectrum.proto\x12\bscte.amp\x1a\x11amps/common.proto\"\x90\x02\n" +
	"\x17spectrum_capture_config\x12P\n" +
	"\x17spectrum_capture_mode_e\x18\x02 \x02(\x0e2\x19.scte.amp.path_selector_eR\x14spectrumCaptureModeE\x12f\n" +
	"\x1cspectrum_capture_data_type_e\x18\x03 \x02(\x0e2&.scte.amp.spectrum_capture_data_type_eR\x18spectrumCaptureDataTypeE\x12;\n" +
	"\tscan_mode\x18\x04 \x02(\x0e2\x1e.scte.amp.spectrum_scan_data_eR\bscanMode\"o\n" +
	"\x16spectrum_capture_range\x12\x1d\n" +
	"\n" +
	"start_freq\x18\x01 \x02(\rR\tstartFreq\x12\x1b\n" +
	"\tstep_size\x18\x02 \x01(\rR\bstepSize\x12\x19\n" +
	"\bend_freq\x18\x03 \x02(\rR\aendFreq\"\x92\x01\n" +
	"\x1dspectrum_capture_range_values\x12\x1d\n" +
	"\n" +
	"start_freq\x18\x01 \x02(\rR\tstartFreq\x12\x1b\n" +
	"\tstep_size\x18\x02 \x01(\rR\bstepSize\x12\x19\n" +
	"\bend_freq\x18\x03 \x02(\rR\aendFreq\x12\x1a\n" +
	"\x06values\x18\x04 \x03(\rB\x02\x10\x01R\x06values\"\x8d\x01\n" +
	"\x16SpectrumCaptureRequest\x129\n" +
	"\x06config\x18\x02 \x02(\v2!.scte.amp.spectrum_capture_configR\x06config\x128\n" +
	"\x06ranges\x18\x03 \x03(\v2 .scte.amp.spectrum_capture_rangeR\x06ranges\"k\n" +
	"\x1cspectrum_capture_point_value\x12,\n" +
	"\x12frequency_mhz_x100\x18\x01 \x01(\rR\x10frequencyMhzX100\x12\x1d\n" +
	"\n" +
	"power_x100\x18\x02 \x01(\x11R\tpowerX100\"\xfe\x02\n" +
	"\x17SpectrumCaptureResponse\x12f\n" +
	"\x1cspectrum_capture_data_type_e\x18\x02 \x02(\x0e2&.scte.amp.spectrum_capture_data_type_eR\x18spectrumCaptureDataTypeE\x12?\n" +
	"\x06values\x18\x03 \x03(\v2'.scte.amp.spectrum_capture_range_valuesR\x06values\x122\n" +
	"\x15total_composite_power\x18\x04 \x01(\x02R\x13totalCompositePower\x12;\n" +
	"\rfragment_info\x18\x05 \x01(\v2\x16.scte.amp.FragmentInfoR\ffragmentInfo\x12I\n" +
	"\fpoint_values\x18\x06 \x03(\v2&.scte.amp.spectrum_capture_point_valueR\vpointValues\"\x96\x01\n" +
	"\x0fSpectrumCapture\x12<\n" +
	"\arequest\x18\x01 \x01(\v2 .scte.amp.SpectrumCaptureRequestH\x00R\arequest\x12?\n" +
	"\bresponse\x18\x02 \x01(\v2!.scte.amp.SpectrumCaptureResponseH\x00R\bresponseB\x04\n" +
	"\x02id*G\n" +
	"\x1cspectrum_capture_data_type_e\x12\x13\n" +
	"\x0fREFERENCE_VALUE\x10\x01\x12\x12\n" +
	"\x0eMEASURED_VALUE\x10\x02B,Z*github.com/enshure/scte-go/amps_go;scteamp"

var (
	file_amps_spectrum_proto_rawDescOnce sync.Once
	file_amps_spectrum_proto_rawDescData []byte
)

func file_amps_spectrum_proto_rawDescGZIP() []byte {
	file_amps_spectrum_proto_rawDescOnce.Do(func() {
		file_amps_spectrum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amps_spectrum_proto_rawDesc), len(file_amps_spectrum_proto_rawDesc)))
	})
	return file_amps_spectrum_proto_rawDescData
}

var file_amps_spectrum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_amps_spectrum_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_amps_spectrum_proto_goTypes = []any{
	(SpectrumCaptureDataTypeE)(0),      // 0: scte.amp.spectrum_capture_data_type_e
	(*SpectrumCaptureConfig)(nil),      // 1: scte.amp.spectrum_capture_config
	(*SpectrumCaptureRange)(nil),       // 2: scte.amp.spectrum_capture_range
	(*SpectrumCaptureRangeValues)(nil), // 3: scte.amp.spectrum_capture_range_values
	(*SpectrumCaptureRequest)(nil),     // 4: scte.amp.SpectrumCaptureRequest
	(*SpectrumCapturePointValue)(nil),  // 5: scte.amp.spectrum_capture_point_value
	(*SpectrumCaptureResponse)(nil),    // 6: scte.amp.SpectrumCaptureResponse
	(*SpectrumCapture)(nil),            // 7: scte.amp.SpectrumCapture
	(PathSelectorE)(0),                 // 8: scte.amp.path_selector_e
	(SpectrumScanDataE)(0),             // 9: scte.amp.spectrum_scan_data_e
	(*FragmentInfo)(nil),               // 10: scte.amp.FragmentInfo
}
var file_amps_spectrum_proto_depIdxs = []int32{
	8,  // 0: scte.amp.spectrum_capture_config.spectrum_capture_mode_e:type_name -> scte.amp.path_selector_e
	0,  // 1: scte.amp.spectrum_capture_config.spectrum_capture_data_type_e:type_name -> scte.amp.spectrum_capture_data_type_e
	9,  // 2: scte.amp.spectrum_capture_config.scan_mode:type_name -> scte.amp.spectrum_scan_data_e
	1,  // 3: scte.amp.SpectrumCaptureRequest.config:type_name -> scte.amp.spectrum_capture_config
	2,  // 4: scte.amp.SpectrumCaptureRequest.ranges:type_name -> scte.amp.spectrum_capture_range
	0,  // 5: scte.amp.SpectrumCaptureResponse.spectrum_capture_data_type_e:type_name -> scte.amp.spectrum_capture_data_type_e
	3,  // 6: scte.amp.SpectrumCaptureResponse.values:type_name -> scte.amp.spectrum_capture_range_values
	10, // 7: scte.amp.SpectrumCaptureResponse.fragment_info:type_name -> scte.amp.FragmentInfo
	5,  // 8: scte.amp.SpectrumCaptureResponse.point_values:type_name -> scte.amp.spectrum_capture_point_value
	4,  // 9: scte.amp.SpectrumCapture.request:type_name -> scte.amp.SpectrumCaptureRequest
	6,  // 10: scte.amp.SpectrumCapture.response:type_name -> scte.amp.SpectrumCaptureResponse
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_amps_spectrum_proto_init() }
func file_amps_spectrum_proto_init() {
	if File_amps_spectrum_proto != nil {
		return
	}
	file_amps_common_proto_init()
	file_amps_spectrum_proto_msgTypes[6].OneofWrappers = []any{
		(*SpectrumCapture_Request)(nil),
		(*SpectrumCapture_Response)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amps_spectrum_proto_rawDesc), len(file_amps_spectrum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_amps_spectrum_proto_goTypes,
		DependencyIndexes: file_amps_spectrum_proto_depIdxs,
		EnumInfos:         file_amps_spectrum_proto_enumTypes,
		MessageInfos:      file_amps_spectrum_proto_msgTypes,
	}.Build()
	File_amps_spectrum_proto = out.File
	file_amps_spectrum_proto_goTypes = nil
	file_amps_spectrum_proto_depIdxs = nil
}
