// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: amps/system_grp.proto

package scteamp

import (
	common_go "github.com/enshure/scte-go/common_go"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SystemCapabilities struct {
	state                         protoimpl.MessageState    `protogen:"open.v1"`
	AmplifierType                 *AmplifierTypeE           `protobuf:"varint,1,opt,name=amplifier_type,json=amplifierType,enum=scte.amp.AmplifierTypeE" json:"amplifier_type,omitempty"`
	SupportsPowerSupplyRedundancy *bool                     `protobuf:"varint,2,opt,name=supports_power_supply_redundancy,json=supportsPowerSupplyRedundancy" json:"supports_power_supply_redundancy,omitempty"`
	PowerSupplyRedundancyMode     *PwrSupplyRedundancyModeE `protobuf:"varint,3,opt,name=power_supply_redundancy_mode,json=powerSupplyRedundancyMode,enum=scte.amp.PwrSupplyRedundancyModeE" json:"power_supply_redundancy_mode,omitempty"`
	SupportsPowerSavingMode       *bool                     `protobuf:"varint,4,opt,name=supports_power_saving_mode,json=supportsPowerSavingMode" json:"supports_power_saving_mode,omitempty"`
	SupportsRfConfigFile          *bool                     `protobuf:"varint,5,opt,name=supports_rf_config_file,json=supportsRfConfigFile" json:"supports_rf_config_file,omitempty"`
	SupportsDebugFile             *bool                     `protobuf:"varint,6,opt,name=supports_debug_file,json=supportsDebugFile" json:"supports_debug_file,omitempty"`
	SupportsRfSpectrumCapture     *bool                     `protobuf:"varint,7,opt,name=supports_rf_spectrum_capture,json=supportsRfSpectrumCapture" json:"supports_rf_spectrum_capture,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *SystemCapabilities) Reset() {
	*x = SystemCapabilities{}
	mi := &file_amps_system_grp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemCapabilities) ProtoMessage() {}

func (x *SystemCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_amps_system_grp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemCapabilities.ProtoReflect.Descriptor instead.
func (*SystemCapabilities) Descriptor() ([]byte, []int) {
	return file_amps_system_grp_proto_rawDescGZIP(), []int{0}
}

func (x *SystemCapabilities) GetAmplifierType() AmplifierTypeE {
	if x != nil && x.AmplifierType != nil {
		return *x.AmplifierType
	}
	return AmplifierTypeE_AMP_TYPE_OTHER
}

func (x *SystemCapabilities) GetSupportsPowerSupplyRedundancy() bool {
	if x != nil && x.SupportsPowerSupplyRedundancy != nil {
		return *x.SupportsPowerSupplyRedundancy
	}
	return false
}

func (x *SystemCapabilities) GetPowerSupplyRedundancyMode() PwrSupplyRedundancyModeE {
	if x != nil && x.PowerSupplyRedundancyMode != nil {
		return *x.PowerSupplyRedundancyMode
	}
	return PwrSupplyRedundancyModeE_PS_REDUNDANCY_MODE_NONE
}

func (x *SystemCapabilities) GetSupportsPowerSavingMode() bool {
	if x != nil && x.SupportsPowerSavingMode != nil {
		return *x.SupportsPowerSavingMode
	}
	return false
}

func (x *SystemCapabilities) GetSupportsRfConfigFile() bool {
	if x != nil && x.SupportsRfConfigFile != nil {
		return *x.SupportsRfConfigFile
	}
	return false
}

func (x *SystemCapabilities) GetSupportsDebugFile() bool {
	if x != nil && x.SupportsDebugFile != nil {
		return *x.SupportsDebugFile
	}
	return false
}

func (x *SystemCapabilities) GetSupportsRfSpectrumCapture() bool {
	if x != nil && x.SupportsRfSpectrumCapture != nil {
		return *x.SupportsRfSpectrumCapture
	}
	return false
}

type PowerSupplyCapabilities struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Id                            *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	SupportsPowerFactorCorrection *bool                  `protobuf:"varint,2,opt,name=supports_power_factor_correction,json=supportsPowerFactorCorrection" json:"supports_power_factor_correction,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *PowerSupplyCapabilities) Reset() {
	*x = PowerSupplyCapabilities{}
	mi := &file_amps_system_grp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerSupplyCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerSupplyCapabilities) ProtoMessage() {}

func (x *PowerSupplyCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_amps_system_grp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerSupplyCapabilities.ProtoReflect.Descriptor instead.
func (*PowerSupplyCapabilities) Descriptor() ([]byte, []int) {
	return file_amps_system_grp_proto_rawDescGZIP(), []int{1}
}

func (x *PowerSupplyCapabilities) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PowerSupplyCapabilities) GetSupportsPowerFactorCorrection() bool {
	if x != nil && x.SupportsPowerFactorCorrection != nil {
		return *x.SupportsPowerFactorCorrection
	}
	return false
}

type EnclosureStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOpen        *bool                  `protobuf:"varint,1,opt,name=is_open,json=isOpen" json:"is_open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnclosureStatus) Reset() {
	*x = EnclosureStatus{}
	mi := &file_amps_system_grp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnclosureStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnclosureStatus) ProtoMessage() {}

func (x *EnclosureStatus) ProtoReflect() protoreflect.Message {
	mi := &file_amps_system_grp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnclosureStatus.ProtoReflect.Descriptor instead.
func (*EnclosureStatus) Descriptor() ([]byte, []int) {
	return file_amps_system_grp_proto_rawDescGZIP(), []int{2}
}

func (x *EnclosureStatus) GetIsOpen() bool {
	if x != nil && x.IsOpen != nil {
		return *x.IsOpen
	}
	return false
}

type PowerSupplyStatus struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	Id             *uint32                   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Description    *string                   `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	OperStatus     *common_go.OperStatusE    `protobuf:"varint,3,opt,name=oper_status,json=operStatus,enum=scte.common.OperStatusE" json:"oper_status,omitempty"`
	InputVoltage   *uint32                   `protobuf:"varint,4,opt,name=input_voltage,json=inputVoltage" json:"input_voltage,omitempty"`
	InputCurrent   *uint32                   `protobuf:"varint,5,opt,name=input_current,json=inputCurrent" json:"input_current,omitempty"`
	Identification *common_go.Identification `protobuf:"bytes,6,opt,name=identification" json:"identification,omitempty"`
	VersionSummary *common_go.VersionSummary `protobuf:"bytes,7,opt,name=version_summary,json=versionSummary" json:"version_summary,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PowerSupplyStatus) Reset() {
	*x = PowerSupplyStatus{}
	mi := &file_amps_system_grp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowerSupplyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerSupplyStatus) ProtoMessage() {}

func (x *PowerSupplyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_amps_system_grp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerSupplyStatus.ProtoReflect.Descriptor instead.
func (*PowerSupplyStatus) Descriptor() ([]byte, []int) {
	return file_amps_system_grp_proto_rawDescGZIP(), []int{3}
}

func (x *PowerSupplyStatus) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *PowerSupplyStatus) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *PowerSupplyStatus) GetOperStatus() common_go.OperStatusE {
	if x != nil && x.OperStatus != nil {
		return *x.OperStatus
	}
	return common_go.OperStatusE(0)
}

func (x *PowerSupplyStatus) GetInputVoltage() uint32 {
	if x != nil && x.InputVoltage != nil {
		return *x.InputVoltage
	}
	return 0
}

func (x *PowerSupplyStatus) GetInputCurrent() uint32 {
	if x != nil && x.InputCurrent != nil {
		return *x.InputCurrent
	}
	return 0
}

func (x *PowerSupplyStatus) GetIdentification() *common_go.Identification {
	if x != nil {
		return x.Identification
	}
	return nil
}

func (x *PowerSupplyStatus) GetVersionSummary() *common_go.VersionSummary {
	if x != nil {
		return x.VersionSummary
	}
	return nil
}

type OutputRailStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	OperStatus    *common_go.OperStatusE `protobuf:"varint,3,opt,name=oper_status,json=operStatus,enum=scte.common.OperStatusE" json:"oper_status,omitempty"`
	Voltage       *uint32                `protobuf:"varint,4,opt,name=voltage" json:"voltage,omitempty"`
	Current       *uint32                `protobuf:"varint,5,opt,name=current" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputRailStatus) Reset() {
	*x = OutputRailStatus{}
	mi := &file_amps_system_grp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputRailStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputRailStatus) ProtoMessage() {}

func (x *OutputRailStatus) ProtoReflect() protoreflect.Message {
	mi := &file_amps_system_grp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputRailStatus.ProtoReflect.Descriptor instead.
func (*OutputRailStatus) Descriptor() ([]byte, []int) {
	return file_amps_system_grp_proto_rawDescGZIP(), []int{4}
}

func (x *OutputRailStatus) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *OutputRailStatus) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *OutputRailStatus) GetOperStatus() common_go.OperStatusE {
	if x != nil && x.OperStatus != nil {
		return *x.OperStatus
	}
	return common_go.OperStatusE(0)
}

func (x *OutputRailStatus) GetVoltage() uint32 {
	if x != nil && x.Voltage != nil {
		return *x.Voltage
	}
	return 0
}

func (x *OutputRailStatus) GetCurrent() uint32 {
	if x != nil && x.Current != nil {
		return *x.Current
	}
	return 0
}

var File_amps_system_grp_proto protoreflect.FileDescriptor

const file_amps_system_grp_proto_rawDesc = "" +
	"\n" +
	"\x15amps/system_grp.proto\x12\bscte.amp\x1a\x11amps/common.proto\x1a\x1acommon/status_common.proto\x1a\x1acommon/device_common.proto\x1a\x1bcommon/version_common.proto\"\xee\x03\n" +
	"\x12SystemCapabilities\x12A\n" +
	"\x0eamplifier_type\x18\x01 \x01(\x0e2\x1a.scte.amp.amplifier_type_eR\ramplifierType\x12G\n" +
	" supports_power_supply_redundancy\x18\x02 \x01(\bR\x1dsupportsPowerSupplyRedundancy\x12g\n" +
	"\x1cpower_supply_redundancy_mode\x18\x03 \x01(\x0e2&.scte.amp.pwr_supply_redundancy_mode_eR\x19powerSupplyRedundancyMode\x12;\n" +
	"\x1asupports_power_saving_mode\x18\x04 \x01(\bR\x17supportsPowerSavingMode\x125\n" +
	"\x17supports_rf_config_file\x18\x05 \x01(\bR\x14supportsRfConfigFile\x12.\n" +
	"\x13supports_debug_file\x18\x06 \x01(\bR\x11supportsDebugFile\x12?\n" +
	"\x1csupports_rf_spectrum_capture\x18\a \x01(\bR\x19supportsRfSpectrumCapture\"r\n" +
	"\x17PowerSupplyCapabilities\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12G\n" +
	" supports_power_factor_correction\x18\x02 \x01(\bR\x1dsupportsPowerFactorCorrection\"*\n" +
	"\x0fEnclosureStatus\x12\x17\n" +
	"\ais_open\x18\x01 \x01(\bR\x06isOpen\"\xd7\x02\n" +
	"\x11PowerSupplyStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12;\n" +
	"\voper_status\x18\x03 \x01(\x0e2\x1a.scte.common.oper_status_eR\n" +
	"operStatus\x12#\n" +
	"\rinput_voltage\x18\x04 \x01(\rR\finputVoltage\x12#\n" +
	"\rinput_current\x18\x05 \x01(\rR\finputCurrent\x12C\n" +
	"\x0eidentification\x18\x06 \x01(\v2\x1b.scte.common.IdentificationR\x0eidentification\x12D\n" +
	"\x0fversion_summary\x18\a \x01(\v2\x1b.scte.common.VersionSummaryR\x0eversionSummary\"\xb5\x01\n" +
	"\x10OutputRailStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12;\n" +
	"\voper_status\x18\x03 \x01(\x0e2\x1a.scte.common.oper_status_eR\n" +
	"operStatus\x12\x18\n" +
	"\avoltage\x18\x04 \x01(\rR\avoltage\x12\x18\n" +
	"\acurrent\x18\x05 \x01(\rR\acurrentB=\n" +
	"\rorg.scte.ampsP\x01Z*github.com/enshure/scte-go/amps_go;scteamp"

var (
	file_amps_system_grp_proto_rawDescOnce sync.Once
	file_amps_system_grp_proto_rawDescData []byte
)

func file_amps_system_grp_proto_rawDescGZIP() []byte {
	file_amps_system_grp_proto_rawDescOnce.Do(func() {
		file_amps_system_grp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amps_system_grp_proto_rawDesc), len(file_amps_system_grp_proto_rawDesc)))
	})
	return file_amps_system_grp_proto_rawDescData
}

var file_amps_system_grp_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_amps_system_grp_proto_goTypes = []any{
	(*SystemCapabilities)(nil),       // 0: scte.amp.SystemCapabilities
	(*PowerSupplyCapabilities)(nil),  // 1: scte.amp.PowerSupplyCapabilities
	(*EnclosureStatus)(nil),          // 2: scte.amp.EnclosureStatus
	(*PowerSupplyStatus)(nil),        // 3: scte.amp.PowerSupplyStatus
	(*OutputRailStatus)(nil),         // 4: scte.amp.OutputRailStatus
	(AmplifierTypeE)(0),              // 5: scte.amp.amplifier_type_e
	(PwrSupplyRedundancyModeE)(0),    // 6: scte.amp.pwr_supply_redundancy_mode_e
	(common_go.OperStatusE)(0),       // 7: scte.common.oper_status_e
	(*common_go.Identification)(nil), // 8: scte.common.Identification
	(*common_go.VersionSummary)(nil), // 9: scte.common.VersionSummary
}
var file_amps_system_grp_proto_depIdxs = []int32{
	5, // 0: scte.amp.SystemCapabilities.amplifier_type:type_name -> scte.amp.amplifier_type_e
	6, // 1: scte.amp.SystemCapabilities.power_supply_redundancy_mode:type_name -> scte.amp.pwr_supply_redundancy_mode_e
	7, // 2: scte.amp.PowerSupplyStatus.oper_status:type_name -> scte.common.oper_status_e
	8, // 3: scte.amp.PowerSupplyStatus.identification:type_name -> scte.common.Identification
	9, // 4: scte.amp.PowerSupplyStatus.version_summary:type_name -> scte.common.VersionSummary
	7, // 5: scte.amp.OutputRailStatus.oper_status:type_name -> scte.common.oper_status_e
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_amps_system_grp_proto_init() }
func file_amps_system_grp_proto_init() {
	if File_amps_system_grp_proto != nil {
		return
	}
	file_amps_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amps_system_grp_proto_rawDesc), len(file_amps_system_grp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_amps_system_grp_proto_goTypes,
		DependencyIndexes: file_amps_system_grp_proto_depIdxs,
		MessageInfos:      file_amps_system_grp_proto_msgTypes,
	}.Build()
	File_amps_system_grp_proto = out.File
	file_amps_system_grp_proto_goTypes = nil
	file_amps_system_grp_proto_depIdxs = nil
}
